### ISSUE TITLE
Brawl and Fast attack range too short (Range calculations are inaccurate)

### ISSUE THREAD

**Issue by holyschytt** [project-rubika/issues#742] opened 2024-06-24 16:49 UTC
1. Go to 'Any Playfield with Mobs'
Normal Attack works Specials not close enough
![image](https://github.com/project-rubika/issues/assets/7978560/f14bc73d-1f5c-4b84-9bf7-461e8c1bbd4d)

**Comment by TheTinkeringIdiot** [comment] 2024-06-25 12:27
Special attack range is tied to weapon range - which weapon are you using in your main hand? Can you try with a few different weapons and list the results here please?

Does this also happen on Rubi-Ka? The screenshot is in Shadowlands, which is very, very broken at the moment. Please try again on RK and report back.

**Comment by holyschytt** [comment] 2024-06-25 15:09
Yes it happens on Rubi-Ka as well 
![Screenshot 2024-06-25 110429](https://github.com/project-rubika/issues/assets/7978560/6ddfa092-9783-461b-a9e8-caeeae46c369)
![Screenshot 2024-06-25 110657](https://github.com/project-rubika/issues/assets/7978560/f4e29ade-611b-4fad-b01a-483338673d57)

**Comment by holyschytt** [comment] 2024-06-25 15:41
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'Any playfield'
2. Click on 'Any Mob as you would normal Used Weapon "211191" Abhorrent Hammer, "122943" Unbalanced Mace try use a special attack at Normal Anarchy Online Distance for Special Attacks to Work. '
3. Scroll down to '....'
4. See error or Notice this behavior
[15:34:18][Xumiski] Player [Xumiski] is too far away to attack [Clawfinger Bully] with [brawl]
[15:38:56][Xumiski] Player [Xumiski] is too far away to attack [Biofreak Carcass] with [fastattack].
[15:38:56][Xumiski] Player [Xumiski] is too far away to attack [Biofreak Carcass] with [brawl].


**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.
![image](https://github.com/project-rubika/issues/assets/7978560/913b5aa5-34ec-48c5-b3c0-272f7f3e2b20)
![image](https://github.com/project-rubika/issues/assets/7978560/479cc5fd-3f36-41e1-a360-72028cb2d2bc)



**Character info:**

```
Copy/paste the output of /getfull here
```

**Playfield info:**
Xumiski [220 Enforcer]
------------------------------------
    strength 	1166
    stamina 	1166
    agility 	835
    sense 	642
    psychic 	642
    intelligence 	612
    flags 	528961
    monsterscale 	112
    currentnano 	4159497
    headmesh 	40100
    waitstate 	1
    cash 	900160356
    gmlevel 	127
    expansion 	3
    breed 	4
    visualbreed 	4
    profession 	9
    visualprofession 	9
    level 	220
    sex 	1
    visualsex 	1
    health 	14799
    titlelevel 	7
    accountflags 	0
    equippedweapontype 	258
    EquippedRHWeapon 	258
    selectedtarget 	1614
    exitstatel 	-1073740870
    externaldoorinstance 	-418378742
    externalplayfieldinstance 	3082
    selectedtargettype 	0
    charstate 	0
    isfightingme 	0
    currentncu 	113
    xp 	2555840
    currentmovementmode 	3
    bodydevelopment 	1520
    nanoenergypool 	1272
    nanoac 	1943
    firstaid 	1453
    treatment 	1416
    parry 	1314
    duck 	1412
    dodge 	1412
    evade 	1412
    nextxp 	3067008
    lastsavexp 	35100
    onehandbluntweapons 	2056
    lastxp 	2555840
    playfieldtype 	0
    expansionplayfield 	0
    side 	2
    lastsaved 	2555840
    computerliteracy 	1542
    nanoprowessinitiative 	1279
    senseimprovement 	1589
    materialmetamorphose 	1403
    biologicalmetamorphose 	1563
    psychologicalmodification 	1563
    materialcreation 	1453
    materiallocation 	1413
    brawl 	1910
    dimach 	1089
    fastattack 	1451
    metatype 	1750
    meleemultiple 	1773
    closecombatinitiative 	1668
    runspeed 	1803
    secondaryitemtemplate 	207108
    twohandbluntweapons 	630
    onehandedgedweapon 	597
    twohandedgedweapons 	630
    piercing 	589
    meleeenergyweapon 	561
    sneakattack 	501
    martialarts 	529
    physicalprowessinitiative 	553
    concealment 	1331
    breakingentry 	504
    disarmtrap 	1138
    perception 	1417
    maxnanoenergy 	4952
    riposte 	473
    adventuring 	539
    swim 	563
    bow 	437
    bowspecialattack 	486
    throwingknife 	504
    throwngrapplingweapons 	443
    pistol 	189
    assaultrifle 	240
    submachinegun 	253
    shotgun 	241
    rifle 	247
    lr_energyweapon 	217
    flingshot 	208
    aimedshot 	304
    burst 	250
    fullauto 	291
    lr_multipleweapon 	306
    grenade 	178
    mechanicalengineering 	324
    electricalengineering 	1137
    fieldquantumphysics 	156
    weaponsmithing 	511
    pharmaceuticals 	166
    nanoprogramming 	200
    psychology 	445
    chemistry 	1162
    tutoring 	386
    distanceweaponinitiative 	264
    driveair 	457
    driveground 	457
    drivewater 	457
    mapnavigation 	446
    specialization 	15
    aggdef 	100
    petreq1 	14
    nanofocuslevel 	96
    xppool 	2664543
    veteranpoints 	60
    savedxp 	2555840
    debug 	1
    ip 	-7574299
    maxncu 	757
    fatness 	1
    race 	1
    life 	14320
    monsterdata 	0
    VisualFlags 	31
    clan 	0
    healinterval 	1
    nanointerval 	8
    shieldprojectileac 	103
    shieldmeleeac 	116
    shieldenergyac 	103
    shieldchemicalac 	116
    shieldradiationac 	103
    shieldcoldac 	116
    shieldfireac 	103
    shieldpoisonac 	116
    energyac 	2676
    meleedamagemodifier 	176
    projectiledamagemodifier 	137
    colddamagemodifier 	137
    firedamagemodifier 	176
    radiationdamagemodifier 	149
    chemicaldamagemodifier 	169
    poisondamagemodifier 	169
    energydamagemodifier 	149
    shieldnanoac 	80
    projectileac 	3076
    meleeac 	3076
    chemicalac 	3302
    radiationac 	3302
    coldac 	3288
    poisonac 	3341
    fireac 	3490
    reflectmeleeac 	3
    reflectpoisonac 	3
    reflectfireac 	3
    reflectnanoac 	3
    reflectcoldac 	3
    reflectprojectileac 	3
    reflectenergyac 	3
    reflectchemicalac 	3
    reflectradiationac 	3
    dmsmodifier 	488
    team 	0
    amsmodifier 	195
    xpmodifier 	20
    criticalincrease 	3
    npcostmodifier 	-4
    criticaldecrease 	5
    rangeincreaserweapon 	42
    beltslots 	6
    healdelta 	121
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    attackspeed 	5
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
    reflectreturnedradiationac 	0
    reflectreturnedmeleeac 	0
    damageoverridetype 	0
------------------------------------

.getfull succeeded - Listed all stats for Xumiski.

```
Copy/paste the output of Shift+F9 here
```
- zone: 26, area: "Junkyard"
Server id: 137733, character id: 50000:1614, time: 2024-06-25 15:32:37 (UTC)
Version: 00.6.1_EP1, map id: 18.8.62.0_02.06.2023_15.50.17, build: 52606.

----

**Comment by RaggyLP** [comment] 2024-06-25 16:45
Confirmed. Brawl is supposed to be a 3m range at all times as per the 'Brawl Item' in the RDB: (https://portal.project-rk.com/server/Ithaca/item/211403) and Fast Attack is supposed to conform to the range of the weapon. Both seem to be hovering around the 1-2m mark currently.

Following further testing, there appears to be a wider issue with Range interpretation and how the server handles distance vs target which has a knock on effect on how special attacks with short ranges such as FA/Brawl (and I assume SA), operate.

Using Beast as a test point for this, the clients interpretation of 'in range' as denoted by the red markers shown on the health bar, doesn't match that of the servers as no attack animations are triggered.

![image](https://github.com/project-rubika/issues/assets/156821187/750bdd5d-21ae-440c-b6d0-35e28e787047)
![image](https://github.com/project-rubika/issues/assets/156821187/88b77d7c-f75f-4e8f-8a23-6a22a920fadc)

It required me to be practically under the target before swings start taking place

![image](https://github.com/project-rubika/issues/assets/156821187/64597cbd-bdd9-467c-a4fa-f3721f8d0bc2)

Further to this, changing a targets 'monsterscale' ID results in the client reporting range based on the percieved increased size of the entity, but this is not reflected by attacks, requiring you to be stood at the exact same distance regardless.

**Comment by prkdrake** [comment] 2024-08-18 22:56
Duplicate of #756

**Closed by prkdrake** 2024-08-18 22:56 UTC
Labels: duplicate
