### ISSUE TITLE
Leveling items can be used while equipped

### ISSUE THREAD

**Issue by prkdrake** [project-rubika/issues#384] opened 2023-12-25 01:47 UTC
See also: #337 

**Describe the bug**
Certain items have both "Use" and "Wield" functions. For example, Barrow Strength is a ToTW drop which can be equipped and used, but there are many examples. There are, however, also leveling items which can be used to level them up. To equip usable gear, you must manually click on it and click on the equipment slot to put it in.

Right clicking these items when they are equipped should use the items, rather than unequip them. However, in the case of leveling items, the "use" action deletes them and creates a new one. This should not be allowed while the item is equipped. At present, when such an item is right clicked, they are leveled as normal, leading to strange behaviour where a new item appears in the inventory but the original item still shows as equipped until zoning.

**To Reproduce**
1. Get a Morphing Memory (/item 202726 202727 1)
2. Right click the morphing memory, it should level up.
3. Equip the Morphing Memory (CTRL+1 and click on it, then click on Deck 1 while wearing a belt)
4. Right click the Morphing Memory
5. Notice the memory is still equipped, and a "new" one appears in your inventory
6. Zone or re-log.
7. Notice the phantom equipped memory is gone.

**Expected behavior**
When a leveling item is used, only a "You can't do this" warning message should be printed to the user's chat. The item should not be deleted and a new item should not be created.

**Comment by TheTinkeringIdiot** [comment] 2024-01-28 15:36
Confirmed. 

The leveling item is usable while equipped, and the next level of the item appears in the player's inventory while apparently remaining equipped. The chat window displays the message "Items must be unequipped before they can be deleted!". 

Attempting to unequip the equipped leveling item after upgrading it displays the equip delay timer, but at the end the item does not unequip. Relogging the character causes the equipped item to vanish, and the upgraded one remains in the player's inventory. 

This appears to be a synchronization issue between the client's and server's view of the player's equipped items.

![image](https://github.com/project-rubika/issues/assets/96996793/d9d923a9-7c02-4e8b-95a7-d783656cd10c)

**Comment by RaggyLP** [comment] 2024-08-15 23:58
Since the recent item refactor changes, this bug is now slightly different. While you are able to still 'Use' the levelling item whilst it is equipped, it now generates a 'duplicate' in the inventory. The duplicate is treated as its own item by the client, until zoning, at which point, the server sends the correct inventory packets and updates the player wear window, to reflect that the used item is now infact unequipped.

Attempting to 'hide' the duplicate by placing it in a bag, another wear slot etc, doesn't work as the server is smart and is tracking the item at all times. 

`.get maxnxu` reflects the item being 'removed' on use, despite it still showing as equipped and replacing the 'original' item with its 'duplicate' results in the client misrepresenting the amount of NCU available. However, the server is updating correctly.

**Comment by prkdrake** [comment] 2024-08-26 14:36
Should be fixed in the latest update.

**Comment by Dezzyx** [comment] 2024-08-26 21:01
Related issue. Right-clicking beginner faction shoulderpads does not change their modifier (Add Off/Def, Nano), rather equips it. I see that in DB it's listed as 3 different items (QL 1/2/3) depending on modifier. I'm not sure how the code stuff works but I'd figure it should change to the proper "item" then, on right-click, regardless of which item was spawned via command.

**Comment by RaggyLP** [comment] 2024-08-27 19:51
Confirmed. It's no longer possible to 'use' levelling items that are currently equipped. Closing as fixed as of 27/08/2024
![image](https://github.com/user-attachments/assets/7493d6c1-9d9f-425a-a361-dad403fd3f22)

**Closed by RaggyLP** 2024-08-27 19:51 UTC
Labels: bug, fixed-please-verify, priority-4
