### ISSUE TITLE
Container Supplier NPC in the Borealis Subway is spawning on top of the counter

### ISSUE THREAD

**Issue by StormlashTV** [project-rubika/issues#829] opened 2024-09-01 10:15 UTC
### Reproduction steps

```bash
1. Go to:
Extended location information:
- 203.6, 301.7, 107.6 (203.6 301.7 y 107.6 127)
- Pf Proxy: Model=51100:127 GS=0 SG=0 R=127, resource: 127
- zone: 7, area: "Abandoned Mall", room: "Shopping Arcade"
Server id: 1, character id: 50000:2252, time: 2024-09-01 10:11:41 (UTC)
Version: 00.6.3_EP1, map id: NOT FOUND, build: 52606.
```

### Expected results

```bash
Container Supplier NPC in the Borealis Subway should spawn behind the counter
```

### Actual results

```bash
Container Supplier NPC spawns on top of the counter
```

### Bug prevalence

Every time

### Description

```bash
I was passing through and noticed she wasn't where she was supposed to be. That's it.
```

### Report link

https://pastebin.com/Wzup6N3u

**Comment by prkdrake** [comment] 2024-09-01 20:02
Duplicate of #831

**Closed by prkdrake** 2024-09-01 20:02 UTC
Labels: bug, needs-verification
