### ISSUE TITLE
Hot swapping weapon mid combat result in weird stuff

### ISSUE THREAD

**Issue by loysaranne** [project-rubika/issues#875] opened 2024-09-09 17:21 UTC
### Reproduction steps

```bash
1. Have two weapons you can equip
2. Start combat with one of them
3. Hot Swap during combat
4. Keep combat going
```

### Expected results

```bash
Character should stop firing weapon for the duration of the equip time and when equip is done it should start attacking with the new weapon statistics.
```

### Actual results

```bash
Character keeps firing the weapon whole equip time and when weapon is equipped, only damage type changes. Attack speed, damage and clip size is retained from the old weapon.
```

### Bug prevalence

Everytime

### Description

```bash
You can reset the weapon state by stopping combat and starting again. After that weapon damage and attack cycle is correct with the weapon equipped.
```

### Report link

https://pastebin.com/PHdrgQBi

**Comment by kajoriEU** [comment] 2024-09-09 17:44
Duplicate of #845 ?

**Comment by kajoriEU** [comment] 2024-09-28 07:15
Can confirm 👍 

```bash
1. Enter combat.
2. Confirm that the Attack/Recharge cycle functions properly.
3. Equip or unequip an item.
```


### Expected results

```bash
Combat should continue with minimal interruption, pausing only for the item equip delay.
```


### Actual results

```bash
Equipping or unequipping an item halts the attack cycle until you exit and re-enter combat.
```


### Bug prevalence

Every time.

###

# Current behavior on PRK




https://github.com/user-attachments/assets/fbb353ed-7189-4478-bab1-d4f55e791af6


# Current behavior on Live

https://github.com/user-attachments/assets/8521afb6-1b4a-4c87-996d-b49346c599da

**Comment by portalerprk** [comment] 2024-10-01 03:41
Can someone test this again? I thought we resolved this when we saw it with the bow swapping

**Comment by kajoriEU** [comment] 2024-10-01 04:04
This seems to be fixed as I can not reproduce this issue anymore.

👍

**Closed by kajoriEU** 2024-10-01 04:04 UTC
Labels: bug, needs-verification
