### ISSUE TITLE
Steps of Madness mobs all have 35 total health

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#570] opened 2024-01-28 02:30 UTC
**Describe the bug**
Mobs in Steps of Madness all have 35 health. This makes them trivial to defeat even for the intended level range of this dungeon. 

**To Reproduce**
1. Enter Steps of Madness
2. Target a mob
3. `.get health`
4. It's 35

**Expected behavior**
Mobs should vary in health and difficulty as the dungeon goes on. None should be single-hit kills for an average player. 

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/96996793/bd508a7c-e122-46f5-95d5-a2a0e15f43df)

![image](https://github.com/project-rubika/issues/assets/96996793/b54a687d-7e1a-4968-81ec-686f37b15f7a)

**Playfield info:**

```
Extended location information:
- 85.9, 120.5, 27.0 (85.9 120.5 y 27.0 1933)
- Pf Proxy: Model=51100:1933 GS=0 SG=0 R=1933, resource: 1933
- zone: 11, area: "Steps of Madness", room: "Dragonhead Room"
Server id: 100027, character id: 50000:1130, time: 2024-01-28 02:30:37 (UTC)
Version: 00.4.7_EP1, map id: NOT FOUND, build: 52606.

```
----

**Comment by RaggyLP** [comment] 2024-01-28 20:27
Confirmed. All mobs excepting bosses are set to 35hp.
![image](https://github.com/project-rubika/issues/assets/156821187/a9421feb-29d0-420f-8c2e-ff2bd537405b)
![image](https://github.com/project-rubika/issues/assets/156821187/9229d78e-1dbe-4430-b600-a6efe0bc93e3)
![image](https://github.com/project-rubika/issues/assets/156821187/180b61ce-d6be-4c29-b9f0-6daa613a6f55)

**Comment by prkdrake** [comment] 2024-02-05 00:43
This one is probably worth a quick check again since we fixed the same problem with guards/subway NPCs

**Comment by RaggyLP** [comment] 2024-02-05 01:39
Confirmed as fixed, however, still missing textures on some of the mobs as mentioned in #396.
closing as fixed as of 01:39 UTC - 05/02/24

![image](https://github.com/project-rubika/issues/assets/156821187/24c1a7bd-04ac-40c9-bffb-a246ce3ef2f6)

**Closed by RaggyLP** 2024-02-05 01:39 UTC
Labels: bug, Fixed - Needs Verification, priority-3
