### ISSUE TITLE
Can't launch game (DirectDraw issue)

### ISSUE THREAD

**Issue by bitnykk** [project-rubika/issues#993] opened 2024-09-24 23:58 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'game launcher'
2. Click on 'play'

**Error message**
We were unable to allocate DirectDraw.
Try restarting the computer.
(which i did, no change)

**Expected behavior**
Start the game as official client does on same OS.

**File info:**
I noticed the client folder contains dgVoodoo based .dlls that ain't in official folder.
D3Dim.dll D3Dim700.dll D3DImm.dll DDraw.dll
Just for trying, i renamed them to disable temporarly and that fixed it.

**Comment by kajoriEU** [comment] 2024-09-25 08:52
We are unable to reproduce the issue. Could you please provide more details about your hardware and platform, such as your operating system?

**Comment by kajoriEU** [comment] 2024-09-30 05:17
As we haven't received additional details, we're closing this issue for now. Please feel free to reopen it with more information about your hardware, operating system, and any other relevant details that could help us investigate further.

**Closed by kajoriEU** 2024-09-30 05:17 UTC
Labels: bug, needs-verification, needs-refinement
