### ISSUE TITLE
Fixer grid elevator buttons are way too large

### ISSUE THREAD

**Issue by loysaranne** [project-rubika/issues#933] opened 2024-09-14 21:26 UTC
### Reproduction steps

```bash
1. Go to Fixer grid
2. Walk to elevator button
3. Get teleported multiple times without moving
```

### Expected results

```bash
Should teleport one floor and then you have to walk again on the button
```

### Actual results

```bash
You teleport and before you can move you get teleported again
```

### Bug prevalence

All the time

### Description

```bash
Would be nice if I could control this stuff
```

### Report link

https://pastebin.com/2gweVJyh

**Comment by kajoriEU** [comment] 2024-09-15 04:32
Confirmed 👍 

When you use the platform inside the Fixer grid intended to take you up one floor, it instead teleports you multiple floors. An effective workaround is to quickly step off the platform and then jump to reach your desired floor.

https://github.com/user-attachments/assets/ffe27a2b-0217-4e86-a004-c92d04238549

**Comment by kajoriEU** [comment] 2024-09-15 22:41
Recent updates have fixed this issue. 

Closing this as fixed as of 15/09/2024 👍

**Closed by kajoriEU** 2024-09-15 22:41 UTC
Labels: bug, priority-3
