### ISSUE TITLE
It isn’t possible to stand after sitting

### ISSUE THREAD

**Issue by S4ff0** [project-rubika/issues#379] opened 2023-12-24 15:15 UTC
**Describe the bug**
if you press x to crouch the toon stays crouched ;  pressing x again don't stand it up; 
relogging unstuck this but if you crouch again it stucks; i tried this in jobe platform;

**Comment by prkdrake** [comment] 2023-12-25 02:02
I can't reproduce this, it works fine for me. Needs more information about the situation in which this occurred. Please provide Shift+F9 debug info with tickets please :)

**Comment by S4ff0** [comment] 2023-12-25 02:20
i could not reproduce it either; dunno maybe it s something else that blocked that situation ?_? dunno

**Comment by portalerprk** [comment] 2023-12-25 14:51
This happens when there is an exception in the playfield or players heartbeat loops that stop processing of messages. When this happens at PF level all players impacted. When player heartbeat exception its just the one player.

**Comment by prkdrake** [comment] 2023-12-26 15:16
Thanks Portaler, so I guess we need to find all the potential places where the heartbeat could have an unhandled exception and handle it

**Comment by RaggyLP** [comment] 2024-08-15 23:45
There have not been any further reports of this for some time, closing as fixed for the moment.

**Closed by RaggyLP** 2024-08-15 23:45 UTC
Labels: bug, cant-reproduce
