### ISSUE TITLE
Tank armor sleeves!

### ISSUE THREAD

**Issue by slythai** [project-rubika/issues#700] opened 2024-04-05 00:25 UTC
**Describe the bug**
So far, this only works on level 73 worn tank armor and from Superior Armor Vendors.

**To Reproduce**
1. While shopping for armor I had clicked on the medium tank armor while checking stats. Right click to remove from shop and my sleeve was removed and was not able to put back on and up zoning it was back.
2. I returned to the and tried other tank armor, but it seems that only the ql 73 worn tank armor would reproduce the sleeve removal.
3. Open shop and add the tank armor to be purchased
4. Remove tank armor by right clicking it form shop window
5. Sleeve is now removed and shop is still open.
6. Add the tank armor again and confirm purchase
7. You will see the tank armor in your inventory and sleeve
8. Put on sleeve and if you see the pink medium armor skin it worked.
9. Zone out of the shop and you will see that you now have armor in your sleeve slot.

**Expected behavior**

**Screenshots**
![Screenshot 2024-04-04 182502](https://github.com/project-rubika/issues/assets/166081278/ebca9de8-7501-4b7f-8bb1-945f208d2895)

**Character info:**

```
Copy/paste the output of /getfull here

.getfull succeeded - Listed all stats for Lilbrute.
Lilbrute [25 Enforcer]
------------------------------------
    strength 	162
    stamina 	171
    agility 	116
    sense 	99
    psychic 	94
    intelligence 	94
    flags 	528961
    monsterscale 	112
    currentnano 	737525
    headmesh 	40100
    waitstate 	1
    cash 	897679934
    gmlevel 	127
    expansion 	3
    breed 	4
    visualbreed 	4
    profession 	9
    visualprofession 	9
    level 	25
    sex 	1
    visualsex 	1
    health 	1928
    titlelevel 	2
    accountflags 	0
    equippedweapontype 	66
    EquippedRHWeapon 	66
    selectedtarget 	1446
    currentncu 	217
    selectedtargettype 	0
    onehandbluntweapons 	100
    exitstatel 	-1073740637
    externaldoorinstance 	0
    externalplayfieldinstance 	0
    charstate 	0
    isfightingme 	0
    xp 	228150
    treatment 	84
    nextxp 	249650
    lastsavexp 	18800
    currentmovementmode 	3
    computerliteracy 	82
    bodydevelopment 	160
    dodge 	162
    evade 	182
    psychology 	25
    lastxp 	228150
    playfieldtype 	1
    fastattack 	104
    materialmetamorphose 	63
    expansionplayfield 	0
    nanoenergypool 	58
    firstaid 	25
    senseimprovement 	87
    psychologicalmodification 	80
    martialarts 	49
    parry 	33
    runspeed 	786
    closecombatinitiative 	59
    nanoac 	64
    aggdef 	100
    lastsaved 	228150
    brawl 	101
    riposte 	26
    dimach 	44
    adventuring 	35
    swim 	39
    onehandedgedweapon 	56
    piercing 	55
    twohandbluntweapons 	73
    twohandedgedweapons 	61
    meleeenergyweapon 	53
    sneakattack 	46
    meleemultiple 	81
    throwingknife 	30
    grenade 	26
    throwngrapplingweapons 	33
    bow 	29
    pistol 	27
    assaultrifle 	34
    submachinegun 	36
    shotgun 	33
    rifle 	27
    lr_energyweapon 	24
    flingshot 	29
    aimedshot 	24
    burst 	35
    fullauto 	41
    bowspecialattack 	28
    lr_multipleweapon 	26
    distanceweaponinitiative 	24
    physicalprowessinitiative 	24
    nanoprowessinitiative 	26
    duck 	75
    mechanicalengineering 	26
    electricalengineering 	29
    fieldquantumphysics 	23
    weaponsmithing 	32
    pharmaceuticals 	24
    nanoprogramming 	23
    chemistry 	33
    tutoring 	23
    biologicalmetamorphose 	63
    materialcreation 	67
    materiallocation 	44
    concealment 	38
    breakingentry 	26
    disarmtrap 	25
    perception 	24
    driveair 	25
    driveground 	25
    drivewater 	25
    mapnavigation 	24
    specialization 	15
    maxnanoenergy 	254
    secondaryitemtemplate 	214789
    maxncu 	192
    fatness 	1
    side 	0
    race 	1
    life 	1928
    monsterdata 	0
    VisualFlags 	31
    clan 	0
    projectileac 	5529
    meleeac 	5529
    energyac 	5488
    chemicalac 	5207
    radiationac 	5219
    coldac 	5274
    fireac 	5507
    poisonac 	5212
    shieldprojectileac 	2
    shieldmeleeac 	2
    shieldenergyac 	2
    shieldchemicalac 	2
    shieldradiationac 	2
    shieldcoldac 	2
    shieldnanoac 	2
    shieldfireac 	2
    shieldpoisonac 	2
    reflectmeleeac 	0
    reflectpoisonac 	0
    reflectfireac 	0
    reflectnanoac 	0
    reflectcoldac 	0
    reflectprojectileac 	0
    reflectenergyac 	0
    reflectchemicalac 	0
    reflectradiationac 	0
    team 	0
    npcostmodifier 	58
    healinterval 	24
    nanointerval 	26
    beltslots 	5
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    attackspeed 	5
    metatype 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
    xpmodifier 	0
------------------------------------

.getfull succeeded - Listed all stats for Lilbrute.

```

**Playfield info:**
Bore Fair Trade Shop
Pos: 198.5, 142.2, 5.0, Area: Area. Time: 2024-04-05 00:21:04 (UTC)
Suppression field at 75 Wildlife may attack you.

```
Copy/paste the output of Shift+F9 here

Extended location information:
- 198.5, 142.2, 5.0 (198.5 142.2 y 5.0 1187)
- Pf Proxy: Model=51100:1187 GS=0 SG=0 R=1187, resource: 1187
- zone: 0, area: "Area", room: "Neutral_Advanced_1"
Server id: 1446, character id: 50000:1446, time: 2024-04-05 00:21:05 (UTC)
Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.
```
----

**Comment by RaggyLP** [comment] 2024-04-05 22:53
Confirmed using the above repro steps (very well written, thank you!).

![image](https://github.com/project-rubika/issues/assets/156821187/0568f0d6-7a82-4005-b005-8094b85d8706)

In the process of testing this, I found a few other candidates

**Steel Ribbed Armor Boots** - Seems to remove the Waist Implant/symb.
![image](https://github.com/project-rubika/issues/assets/156821187/96043e9f-ce35-49fb-8911-733700b64d03)

**Nadir Steel-Ribbed Armor Sleeves** - Seems to remove the Left Wrist.
![image](https://github.com/project-rubika/issues/assets/156821187/b022525f-b2f6-41af-baac-29ab4a722623)

**Nadir Steel-Ribbed Armor Pants** - Seems to remove the Left Finger.
![image](https://github.com/project-rubika/issues/assets/156821187/6ddb86be-d52e-46e7-b04d-91acc5334879)

Overall, it appears there is a disconnect between the shop interface and the client inventory.

**Comment by RaggyLP** [comment] 2024-04-05 22:59
![image](https://github.com/project-rubika/issues/assets/156821187/10906caa-2574-4614-98d7-7509cfca5d9d)

Further to this, the stats are actually being accepted by the server and is not a purely client side oddity.

**Comment by RaggyLP** [comment] 2024-04-06 02:05
Further testing:

The QL range of impact is QL70-QL81~
Seems to be limited solely to the Superior Armour terminal
This only affects items in the shop inventory, items added to the sell portion and then retruned dont seem to yield the bug outcome.
The shifting of items only occurs on the right-click action to remove an item from the 'bought Items' portion of the shop interface.
This isn't limited to items in the equip window, using a QL81 pair Basic Flowers Tech Armor Pants I could move items around my inventory.

![image](https://github.com/project-rubika/issues/assets/156821187/573261ab-d298-4445-b46d-4dab750f488b)
![image](https://github.com/project-rubika/issues/assets/156821187/cdba690b-917e-42c4-9e9a-f446548b09f9)
![image](https://github.com/project-rubika/issues/assets/156821187/40a8465f-6650-47f4-a9c6-0bb3ddba5ce2)

**Comment by 7RO11** [comment] 2024-04-16 01:40
encountered something possibly related with health rechargers, to reproduce
1. have 2 weapons equipped, go into a store
2. queue up a treatment laboratory and nano recharger
3. remove them
4. add them again
5. the item in your right hand should unequipped to your inventory
6. equip the "weapon" you had previously equpped
7. zone
8. laboratory recharger weapon
![heal](https://github.com/project-rubika/issues/assets/73971287/b8ef5c87-0d9a-43b1-ad1a-a4182883afc3)
also have a video doing it

https://github.com/project-rubika/issues/assets/73971287/8006f2de-2ade-433e-998e-15fbf3fc56eb
you notice some other mix ups as well in it, once the rechargers are added to inventory, the health one activates the nano rech, the nano does nothing

**Comment by Unknownprk** [comment] 2024-06-27 15:58
This should now be fixed, thanks for all the information it really does help!

**Comment by RaggyLP** [comment] 2024-06-30 11:58
Attempted to repro using our previous steps, tested all of the QL ranges that worked last time and it yielded no outcome, seems it's fixed! Nice one Unknown! Closeing as fixed as of 30/06/24

**Closed by RaggyLP** 2024-06-30 11:58 UTC
Labels: bug, Fixed - Needs Verification, priority-1
