### ISSUE TITLE
Disharmony perks 'index out of range' exception on Player Portal

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#594] opened 2024-02-02 02:51 UTC
**Describe the bug**
The Disharmony perk line cannot be viewed in the Player Portal database. Attempting to bring up any of them results in the error:

`Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')`

**To Reproduce**
1. Go Player Portal
2. Search 'Disharmony'
3. Select any of the without an icon (these are the perks themselves) - 211792 is the ID I tested
4. Error

**Expected behavior**
The item should come up. 

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/96996793/e1eb1b5b-e6f4-469a-9ea0-98d5187006f1)

**Comment by RaggyLP** [comment] 2024-02-02 19:37
Confirmed. 

![image](https://github.com/project-rubika/issues/assets/156821187/bb960b85-a605-4464-9fed-c9183438057e)

**Comment by prkdrake** [comment] 2024-08-18 23:27
Seems to be working now.

**Comment by RaggyLP** [comment] 2024-08-25 01:11
https://site.project-rk.com/server/Ithaca/item/211792

Confirmed that this now appears to be solved. Closing as fixed as of 25/08/2024.

**Closed by RaggyLP** 2024-08-25 01:11 UTC
Labels: bug, fixed-please-verify, priority-4, portal
