### ISSUE TITLE
Workman Strikers' Brawl attack can do a disproportionate amount of damage

### ISSUE THREAD

**Issue by Zolarix** [project-rubika/issues#599] opened 2024-02-02 18:09 UTC
**Describe the bug**
So far this has been confirmed with Brawling from Workman Strikers in the Subway.

```
Workman Striker hit you for 11 points of melee damage.
Workman Striker hit you for 11 points of melee damage.
Workman Striker hit you for 11 points of melee damage.
Workman Striker hit you for 11 points of melee damage.
Workman Striker hit you for 136 points of Brawling damage.
Workman Striker hit you for 11 points of melee damage.
You hit Workman Striker for 11 points of energy damage.
Workman Striker hit you for 11 points of melee damage.
```

**To Reproduce**
1. Go to the Subway
2. Begin combat with a Workman Striker
3. Wait for them to use the Brawling attack on you

Observe -> The damage is about 10x their regular damage.

**Expected behavior**
Most special attack damage should be within about 1-3x the regular attack damage.

**Character info:**

```
Workman Striker [14 Enforcer]
------------------------------------
    life 	360
    currentnano 	360
    fatness 	1
    race 	1
    monsterdata 	203854
    profession 	9
    accountflags 	0
    expansion 	3
    runspeed 	58
    losheight 	0
    visualprofession 	15
    sex 	1
    breed 	4
    monsterscale 	96
    clan 	149
    npc_type 	80001
    side 	3
    cash 	85
    health 	360
    energy 	360
    xp 	0
    aggdef 	100
    attitude 	1
    breedhostility 	30
    healinterval 	27
    healdelta 	6
    strength 	42
    agility 	33
    stamina 	42
    intelligence 	33
    sense 	42
    psychic 	33
    martialarts 	83
    brawl 	85
    riposte 	84
    dimach 	85
    onehandbluntweapons 	85
    onehandedgedweapon 	84
    piercing 	84
    twohandedgedweapons 	85
    twohandbluntweapons 	85
    meleeenergyweapon 	84
    parry 	78
    sneakattack 	83
    meleemultiple 	84
    fastattack 	84
    throwingknife 	77
    grenade 	77
    throwngrapplingweapons 	77
    bow 	84
    pistol 	84
    assaultrifle 	84
    submachinegun 	84
    shotgun 	84
    rifle 	84
    lr_energyweapon 	84
    flingshot 	83
    aimedshot 	85
    burst 	84
    fullauto 	85
    bowspecialattack 	84
    lr_multipleweapon 	83
    closecombatinitiative 	77
    distanceweaponinitiative 	77
    physicalprowessinitiative 	77
    nanoprowessinitiative 	77
    swim 	78
    bodydevelopment 	10
    duck 	72
    dodge 	72
    evade 	72
    projectileac 	21
    meleeac 	21
    energyac 	21
    chemicalac 	21
    radiationac 	21
    fireac 	21
    coldac 	21
    nanoac 	58
    poisonac 	21
    firstaid 	73
    treatment 	72
    mechanicalengineering 	72
    electricalengineering 	72
    fieldquantumphysics 	72
    weaponsmithing 	73
    pharmaceuticals 	72
    nanoprogramming 	72
    computerliteracy 	72
    psychology 	73
    chemistry 	73
    tutoring 	72
    materialmetamorphose 	76
    biologicalmetamorphose 	76
    psychologicalmodification 	76
    materialcreation 	76
    materiallocation 	76
    senseimprovement 	76
    nanoenergypool 	76
    flags 	0
    concealment 	77
    breakingentry 	76
    disarmtrap 	77
    perception 	77
    driveground 	73
    driveair 	73
    mapnavigation 	73
    proximityrangeindoors 	13
    proximityrangeoutdoors 	25
    aggressiveness 	0
    conformity 	20
    stability 	100
    extroverty 	0
    headmesh 	40127
    level 	14
    equippedweapontype 	0
    EquippedRHWeapon 	0
    VisualFlags 	31
    isfightingme 	0
    currentmovementmode 	3
    HasKnuBotData 	0
    waitstate 	2
    maxnanoenergy 	188
    titlelevel 	1
    nanointerval 	28
    selectedtarget 	1084
    selectedtargettype 	0
    amsmodifier 	0
    damageoverridetype 	0
    meleedamagemodifier 	0
------------------------------------

.getfull succeeded - Listed all stats for Workman Striker.

```

**Playfield info:**

```
Extended location information:
- 321.2, 203.0, 100.8 (321.2 203.0 y 100.8 127)
- Pf Proxy: Model=51100:127 GS=0 SG=0 R=127, resource: 127
- zone: 19, area: "Condemned Subway", room: "Subway Station"
Server id: 1084, character id: 50000:1084, time: 2024-02-02 18:09:12 (UTC)
Version: 00.5.2_EP1, map id: NOT FOUND, build: 52606.
```
----

**Comment by TheTinkeringIdiot** [comment] 2024-02-06 01:28
Confirmed, sort of. 

It appears this has been adjusted since the issue was reported, and mob special attacks no longer do a disproportionately large amount of damage. 

They now do a disproportionately small amount (outside of Subway, which seems OK). Specials do 1-2 damage regardless of mob level and attack power. 

Workman Striker in Subway:
![image](https://github.com/project-rubika/issues/assets/96996793/059dc0cc-e206-47c7-9fba-0c4eeaa8959f)

Cultist in ToTW:
![image](https://github.com/project-rubika/issues/assets/96996793/3a58f610-383e-4d30-8d3f-8db7fa1f08e0)

Security Officer in Foremans:
![image](https://github.com/project-rubika/issues/assets/96996793/35c24b54-4b8c-4576-a985-5f1374a02cfe)

**Comment by Zolarix** [comment] 2024-07-09 17:45
Just got this on my first encounter with a Workman Striker in the subway in this session:
![image](https://github.com/project-rubika/issues/assets/96363854/c2f48417-bb76-4215-9729-f4b000d0161e)

Listing my character's stats in case it's something to do with them:
```
Bang [11 Soldier]
------------------------------------
    strength 	54
    stamina 	53
    agility 	55
    sense 	36
    psychic 	36
    intelligence 	40
    flags 	8917569
    monsterscale 	100
    currentnano 	188
    headmesh 	40111
    cash 	252203
    gmlevel 	127
    expansion 	3
    breed 	4
    visualbreed 	4
    profession 	1
    visualprofession 	1
    level 	11
    sex 	1
    visualsex 	1
    titlelevel 	1
    health 	111
    equippedweapontype 	2068
    EquippedRHWeapon 	2068
    selectedtarget 	1084
    exitstatel 	-1073348481
    externaldoorinstance 	0
    externalplayfieldinstance 	0
    playfieldtype 	0
    currentncu 	0
    bodydevelopment 	73
    nanoenergypool 	67
    submachinegun 	62
    assaultrifle 	87
    treatment 	117
    burst 	68
    computerliteracy 	59
    fullauto 	86
    distanceweaponinitiative 	69
    pistol 	11
    shotgun 	13
    rifle 	11
    bow 	11
    aimedshot 	24
    flingshot 	13
    bowspecialattack 	11
    lr_multipleweapon 	12
    selectedtargettype 	0
    charstate 	0
    isfightingme 	0
    xp 	50192
    nextxp 	53350
    lastsavexp 	7000
    runspeed 	75
    firstaid 	106
    currentmovementmode 	3
    waitstate 	1
    lastxp 	45650
    dodge 	32
    evade 	47
    senseimprovement 	31
    materialmetamorphose 	44
    biologicalmetamorphose 	30
    psychologicalmodification 	30
    materialcreation 	70
    materiallocation 	50
    nanoprowessinitiative 	27
    gang_dog_tags 	12
    lastperkresettime 	1706451445
    tutoring 	18
    perception 	24
    duck 	17
    lr_energyweapon 	18
    maxnanoenergy 	182
    nanoac 	17
    swim 	13
    accountflags 	0
    currentplayfield 	800
    grenade 	11
    throwngrapplingweapons 	13
    maxncu 	35
    side 	0
    fatness 	1
    race 	1
    life 	473
    monsterdata 	0
    VisualFlags 	31
    clan 	0
    healinterval 	28
    nanointerval 	28
    team 	0
    coldac 	192
    meleeac 	144
    energyac 	131
    projectileac 	173
    poisonac 	66
    radiationac 	61
    chemicalac 	38
    fireac 	61
    beltslots 	3
    aggdef 	100
    closecombatinitiative 	14
    physicalprowessinitiative 	14
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    martialarts 	17
    meleemultiple 	18
    onehandbluntweapons 	18
    onehandedgedweapon 	18
    piercing 	18
    twohandbluntweapons 	18
    twohandedgedweapons 	18
    meleeenergyweapon 	16
    throwingknife 	17
    drivewater 	15
    mechanicalengineering 	16
    electricalengineering 	16
    disarmtrap 	15
    adventuring 	18
    driveair 	15
    mapnavigation 	14
    brawl 	18
    riposte 	16
    dimach 	14
    parry 	17
    sneakattack 	16
    fastattack 	16
    fieldquantumphysics 	14
    weaponsmithing 	16
    pharmaceuticals 	15
    nanoprogramming 	15
    psychology 	14
    chemistry 	16
    concealment 	15
    breakingentry 	15
    driveground 	15
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    attackspeed 	5
    metatype 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
    xpmodifier 	0
------------------------------------

.getfull succeeded - Listed all stats for Bang.

```

**Comment by prkdrake** [comment] 2024-08-18 23:22
I believe this is fixed now

**Comment by RaggyLP** [comment] 2024-08-25 13:51
Confirmed. Workman Strikers are now solely using their weapon template as they should. Closing as fixed as of 25/08/2024.

**Closed by RaggyLP** 2024-08-25 13:51 UTC
Labels: bug, fixed-please-verify, priority-3
