### ISSUE TITLE
Brandon Thorn gives duplicate starter items

### ISSUE THREAD

**Issue by StormlashTV** [project-rubika/issues#818] opened 2024-08-30 23:21 UTC
### Reproduction steps

```bash
1. Create a new character
2. Walk to Brandon Thorn
3. Talk to him
4. Finish the mission
```

### Expected results

```bash
I was NOT expecting to get duplicate starter items
```

### Actual results

```bash
I got duplicate starter items
```

### Bug prevalence

Everytime I create a new character and finish the first mission

### Description

```bash
Extended location information:
- 934.9, 758.6, 24.4 (934.9 758.6 y 24.4 4582)
- Pf Proxy: Model=51100:4582 GS=0 SG=0 R=4582, resource: 4582
- zone: 923, area: "ICC Shuttleport"
Server id: 1, character id: 50000:2252, time: 2024-08-30 23:18:09 (UTC)
Version: 00.6.3_EP1, map id: NOT FOUND, build: 52606.


It appears NOT to duplicate NODROP/UNIQUE items
It also does NOT duplicate other items (I looted some mobs before talking to Brandon to see if it would duplicate those items too and it did NOT)
```

### Report link

https://pastebin.com/pJpVgyZC

**Comment by RaggyLP** [comment] 2024-08-31 00:29
Duplicate of #796.

**Closed by RaggyLP** 2024-08-31 00:29 UTC
Labels: bug, needs-verification
