### ISSUE TITLE
Steps of Madness

### ISSUE THREAD

**Issue by Rasuru2** [project-rubika/issues#506] opened 2024-01-17 16:18 UTC
**Describe the bug**
The instance NPCs all die in 1 hit and their loot tables seem to be broken. Giving 5 creds or not droping the correct items - like the items needed to upgrade the ring/robe. Neleb is the only mob in the instance that doesn't die in 1 hit, but his loot table is also broken - only droping 1 item. 

**To Reproduce**
4. See error or Notice this behavior

**Expected behavior**

**Screenshots**

**Character info:**

```
Copy/paste the output of /getfull here
```

**Playfield info:**

```
Copy/paste the output of Shift+F9 here
```
----

**Comment by prkdrake** [comment] 2024-01-17 16:31
Duplicate of #393

**Comment by prkdrake** [comment] 2024-01-25 18:00
This issue is unworkable in the current state and needs refinement. If anyone has some time to test out SoM and raise separate issues for any of the above that would be helpful!

**Comment by TheTinkeringIdiot** [comment] 2024-01-28 02:38
Broken up into #568,  #569, and #570 each with more detail. Closing this one.

**Closed by TheTinkeringIdiot** 2024-01-28 02:38 UTC
Labels: needs-splitting, needs-refinement
