### ISSUE TITLE
mob attack speeds too fast/slow

### ISSUE THREAD

**Issue by 7RO11** [project-rubika/issues#1010] opened 2024-09-27 00:51 UTC
**Describe the bug**
attack speed on some mobs in totw isn't tuned quite right

**To Reproduce**
1. Go to totw
2. Fight reverend hyuan
3. Notice it attacks significantly faster than live
or
2. Fight a hammer cultist
3. Notice it attacks significantly slower than live

**Expected behavior**
attack speeds should be appropriate for the difficulty of the mob, hammer cultists are very easy for their level, skull mobs are significantly harder

all the skull mobs i have looked at so far have faster attacks, exarchs, windcallers, re-animator
the few other named mobs that use hammers are also very slow, oran the faithful

PRK vs Live Skull mobs

https://github.com/user-attachments/assets/db8b6bc8-4b46-46b4-adfb-873bec76f626

PRK VS Live Hammer mobs

https://github.com/user-attachments/assets/0e72c1e5-cf33-4db1-8ed0-6b6335386647

**Comment by RaggyLP** [comment] 2024-09-27 19:34
Ok so, this one led me on a merry goose chase to figure out what is going on. 

It would appear that our mobs are not using their monsterequip templates as they should be and instead are inheriting the Attack/Recharge of the visual weapons they have equipped.

![image](https://github.com/user-attachments/assets/c79697af-3303-4eba-b721-78a663e6dc28)

This is the weapon in use as a visual weapon for our Hammer Cultists and Gumeaters vid clearly shows that our Cultist is swinging at a speed equal to that of the visual weapon.

![image](https://github.com/user-attachments/assets/850901bf-579e-4a02-83b9-a3ae7426e60f)
https://site.project-rk.com/server/Ithaca/item/144742

Is the monsterweapon that the Cultist *should* be using for the Attack/Recharge stats.

***HOWEVER***
On further digging, it appears that all of our ToTW Weapon Templates have incorrect *Attack* speeds on them. For comparison:
Here is some excerpts, compared to Auno.

Yatilla boss weapons:

![image](https://github.com/user-attachments/assets/a28d953f-1422-4511-84f8-15b1abc67700)
![image](https://github.com/user-attachments/assets/e606f926-9872-432e-a8a0-17400435bb46)
![image](https://github.com/user-attachments/assets/a8f01fe5-1223-4ef8-820c-bb7033669e61)
![image](https://github.com/user-attachments/assets/85a35efa-666e-4767-aff2-f48255de92db)


And for our Cultist friend:

![image](https://github.com/user-attachments/assets/a0dae220-5ef5-40c4-b45d-c3eeb53c6e31)
![image](https://github.com/user-attachments/assets/afeaf8ef-fc21-4dfd-8a8f-c9d7bc7fd203)


So this issue is twofold:

NPC/Mobs are inheriting visual weapon stats for A/R *. *AND* our ToTw A/R templates are wrong.

**Comment by RaggyLP** [comment] 2024-09-27 19:59
Ok, so, even more testing. This seems to be totally systemic.

![image](https://github.com/user-attachments/assets/4b93f7e4-71d4-4c02-b856-08f032c14c6f)
![image](https://github.com/user-attachments/assets/aab6ae4d-3ecc-47a6-b82e-c8e777dfd3c4)
![image](https://github.com/user-attachments/assets/431a8e4d-9eb1-4486-9f7a-e245f2f28697)

1/1 Attack Speed Beast anyone?

![image](https://github.com/user-attachments/assets/4aecb0b1-1366-4845-83f8-d05905a0e922)
![image](https://github.com/user-attachments/assets/d7f804a7-5f27-4f31-b5dc-915e65a0f4ef)
![image](https://github.com/user-attachments/assets/0f42f132-2d7e-4b90-a5ee-5e3f0e959895)

How about 1/1 Hecklers!

*It's alllll bad*

**Comment by RaggyLP** [comment] 2024-09-28 01:29
Confirmed this is now fixed as of 28/09/2024.

**Closed by RaggyLP** 2024-09-28 01:29 UTC
Labels: bug, priority-1
