### ISSUE TITLE
MP Pet Casting Bug - Lesser Anger Manifestation

### ISSUE THREAD

**Issue by rsandersjr** [project-rubika/issues#956] opened 2024-09-19 15:13 UTC
**Describe the bug**
When trying to cast Lesser Anger Manifestation if you don't have a target it won't cast the pet.

**To Reproduce**
1.Dont have an enemy selected
2.try to cast pet (in this case it was Lesser Anger Manifestation)
3.it won't cast, it will say your target can't be attacked

**Expected behavior**
you should be able to cast your pet regardless if you have anything selected or not.

**Screenshots**

**Character info:**
```
Copy/paste the output of /getfull here
```

**Playfield info:**
Extended location information:
- 935.4, 758.6, 24.3 (935.4 758.6 y 24.3 4582)
- Pf Proxy: Model=51100:4582 GS=0 SG=0 R=4582, resource: 4582
- zone: 923, area: "ICC Shuttleport"
Server id: 1, character id: 50000:2578, time: 2024-09-19 15:11:46 (UTC)
Version: 00.6.5_EP1, map id: NOT FOUND, build: 52606.

```
Copy/paste the output of Shift+F9 here
```
Extended location information:
- 935.4, 758.6, 24.3 (935.4 758.6 y 24.3 4582)
- Pf Proxy: Model=51100:4582 GS=0 SG=0 R=4582, resource: 4582
- zone: 923, area: "ICC Shuttleport"
Server id: 1, character id: 50000:2578, time: 2024-09-19 15:11:46 (UTC)
Version: 00.6.5_EP1, map id: NOT FOUND, build: 52606.

**Comment by kajoriEU** [comment] 2024-09-19 17:31
Confirmed. 👍 

It currently looks like you have to target yourself to execute self-only 'On User' Nanos.

I'll update the title in the future to better reflect the core issue of this problem.

**Comment by kajoriEU** [comment] 2024-09-19 17:48
Finally, I found the open issues I was looking for. This issue is a duplicate of #843 and #459. Couldn't find them earlier - closing this as duplicate.

**Closed by kajoriEU** 2024-09-19 17:48 UTC
Labels: bug, needs-verification
