### ISSUE TITLE
Reconstruction perk puts engineer on their pet's hate list (and kills the pet if on guard)

### ISSUE THREAD

**Issue by Nephima** [project-rubika/issues#944] opened 2024-09-16 12:05 UTC
### Reproduction steps

```bash
1. Have a pet as engineer, set it on follow or guard
2. Get pet to be below 100% health
3. Use Reconstruction perk from Gadgeteer 2 on the pet
4. Use /pet guard
```

### Expected results

```bash
No issues.
```

### Actual results

```bash
When pet is on guard (important aspect) and the player ends up being on it's hate list as a result of using Reconstruction perk on it, the pet will gradually take Unknown damage until it dies or until we use .hate clear.
```

### Bug prevalence

Every time.

### Description

```bash
Important to note:
- If we use /pet guard at the beginning and then use perk and be on pet's hate list, it will already start taking damage the moment we use the perk
- If we use the perk and be on pet's hate list but pet is on follow, then all is good. It will start taking damage the moment we do /pet guard

So, issue is definitely tied to being on pet's hate list while it's on guard.
```

### Report link

https://pastebin.com/GYKHuJym

**Comment by kajoriEU** [comment] 2024-09-16 18:29
Something funny is going on here. With the above reproduction steps it looks like sooner or later the pets adding itself to the hatelist?

![{E3813D6F-04C1-4347-A165-A752506B8723}](https://github.com/user-attachments/assets/45081d42-3cec-4a2c-994f-76534a16ef39)

![{41F975DD-9195-424E-8B1F-87154C584912}](https://github.com/user-attachments/assets/bead22a8-5d97-46c8-8300-76935af26a43)

**Comment by Nephima** [comment] 2024-09-16 19:01
Issue specifically seems to be that /pet guard damages the pet if I am on its hatelist. And I provided the only 100% certain way of putting myself on pet's hatelist - by using Reconstruction perk on it (which is kind of another bug itself).

**Comment by prkdrake** [comment] 2024-09-16 19:09
My guess is that since the pet 'hates' you, for whatever reason, it's trying to fight you, but it can't. Then it goes to defend you from itself and starts attacking itself. But that's just speculation

**Comment by kajoriEU** [comment] 2024-09-27 11:32
I can not reproduce this issue anymore. 

![{7594FA4E-9E63-4280-B91F-30AC36798252}](https://github.com/user-attachments/assets/ef7dedf8-d7b2-491f-8131-2b7ee2e6e641)


Closing this as fixed. 👍

**Closed by kajoriEU** 2024-09-27 11:32 UTC
Labels: bug, fixed-please-verify, priority-3
