### ISSUE TITLE
Unable to wear Clan Merits - Blossoms of Summer board

### ISSUE THREAD

**Issue by reiserFSs** [project-rubika/issues#1004] opened 2024-09-26 13:05 UTC
### Reproduction steps

```bash
1. Upgrade your token board to LVL 3 - Blossoms of Summer
2. Try to wear it.
```

### Expected results

```bash
Being able to wear it in the neck slot.
```

### Actual results

```bash
Your no LDBintern (2002:60) is required to be at least 1!
Your %s is required to be at least %d!
You're unable to wear this item..
```

### Bug prevalence

Always

### Description

```bash
Took my lvl 2 board from my slot and upgraded it to lvl 3.
```

### Report link

https://pastebin.com/3qmeaZGE

**Comment by kajoriEU** [comment] 2024-09-26 17:02
Can not reproduce this issue.

**Comment by reiserFSs** [comment] 2024-09-26 17:18
That's weird. Any more info I could possibly provide?

**Comment by prkdrake** [comment] 2024-09-26 17:19
Is it still happening, and does it happen after you zone? How did you get the original token board?

**Comment by kajoriEU** [comment] 2024-09-26 17:38
I didn't test it with your exact Prof (soldier) and missed the issue! Sorry for that @reiserFSs .

**Comment by kajoriEU** [comment] 2024-09-30 05:26
This issue seems to be fixed now 👍 

![{F2D70107-3F4A-4149-94E4-BE84A9E4DA1A}](https://github.com/user-attachments/assets/2475f2c6-a1e8-4f2a-be16-5291960dd79e)

**Closed by kajoriEU** 2024-09-30 05:26 UTC
Labels: bug, priority-3
