### ISSUE TITLE
NPC Equips are delayed on respawn.

### ISSUE THREAD

**Issue by FuruKatsuragi** [project-rubika/issues#1007] opened 2024-09-26 15:31 UTC
**Describe the bug**
Killed Eumenids, the respawn aggroed me and I was hit with radiation damage:

Attacked by Eumenides!
You were attacked with nanobots for 234 points of unknown damage.
You were attacked with nanobots for 195 points of unknown damage.

**To Reproduce**
1. Kill Eumenides
2. Wait for his respawn timer and stay close to his respawn location to get aggroed immediatly
3. Check your combat log for the damage taken/dealt.

**Expected behavior**
Boss shoud aggro players in vicinity and start regular attacks.
**Screenshots**
was ded too fast ):

**Character info:**

Furu 25, Fixer Deep Subway
Copy/paste the output of /getfull here
```
    disarmtrap 	29

    distanceweaponinitiative 	149

    dmsmodifier 	30

    dodge 	31

    driveair 	27

    driveground 	27

    drivewater 	27

    duck 	26

    electricalengineering 	32

    energyac 	417

    energydamagemodifier 	11

    EquippedRHWeapon 	20

    equippedweapontype 	20

    evade 	137

    exitstatel 	-1073740637

    expansion 	2

    expansionplayfield 	0

    externaldoorinstance 	-1073151434

    externalplayfieldinstance 	566

    fastattack 	27

    fatness 	1

    features 	6

    fieldquantumphysics 	38

    fireac 	376

    firedamagemodifier 	11

    firstaid 	66

    flags 	528961

    flingshot 	29

    fullauto 	30

    globalresearchgoal 	0

    globalresearchlevel 	0

    gmlevel 	127

    gos 	0

    grenade 	27

    headmesh 	40685

    healdelta 	4

    healinterval 	27

    health 	154

    icon 	0

    inplay 	0

    insurancepercentage 	0

    insurancetime 	0

    intelligence 	90

    invaderskilled 	0

    isfightingme 	0

    itemtype 	0

    killedbyinvaders 	0

    lastconcreteplayfieldinstance 	0

    lastmailchecktime 	1283065897

    lastperkresettime 	0

    lastrnd 	86

    lastsaved 	25

    lastsavexp 	208050

    lastxp 	228150

    level 	25

    life 	667

    lr_energyweapon 	32

    lr_multipleweapon 	38

    mapareapart1 	16384

    mapareapart2 	536877120

    mapareapart3 	0

    mapareapart4 	0

    mapflags 	0

    mapnavigation 	27

    mapoptions 	0

    martialarts 	27

    materialcreation 	44

    materiallocation 	132

    materialmetamorphose 	151

    maxnanoenergy 	524

    maxncu 	25

    mechanicalengineering 	27

    meleeac 	433

    meleedamagemodifier 	9

    meleeenergyweapon 	26

    meleemultiple 	27

    members 	999

    mesh 	17530

    metatype 	0

    missionbits1 	1024

    missionbits10 	0

    missionbits11 	0

    missionbits12 	0

    missionbits2 	256

    missionbits3 	0

    missionbits4 	0

    missionbits5 	3998

    missionbits6 	0

    missionbits7 	128

    missionbits8 	992

    missionbits9 	0

    monsterdata 	0

    monsterscale 	100

    monthspaid 	0

    nanoac 	63

    nanodelta 	3

    nanoenergypool 	101

    nanofocuslevel 	0

    nanointerval 	26

    nanoprogramming 	27

    nanoprowessinitiative 	38

    nextxp 	249650

    onehandbluntweapons 	26

    onehandedgedweapon 	26

    otarmedforces 	0

    otfollowers 	0

    otmed 	1234567890

    otoperator 	0

    ottrans 	0

    otunredeemed 	0

    PaidPoints 	0

    parry 	27

    perception 	77

    personalresearchgoal 	0

    personalresearchlevel 	0

    pharmaceuticals 	27

    physicalprowessinitiative 	22

    piercing 	26

    pistol 	35

    playerid 	1234567890

    playeroptions 	0

    playfieldtype 	1

    poisonac 	437

    poisondamagemodifier 	14

    previoushealth 	50

    prevmovementmode 	3

    profession 	4

    projectileac 	439

    projectiledamagemodifier 	11

    psychic 	90

    psychologicalmodification 	145

    psychology 	27

    PVPDuelDeaths 	0

    PVPDuelKills 	0

    PVPDuelScore 	0

    PVPProfessionDuelDeaths 	0

    PVPProfessionDuelKills 	0

    PVPRankedSoloDeaths 	0

    PVPRankedSoloKills 	0

    PVPRankedTeamDeaths 	0

    PVPRankedTeamKills 	0

    PVPSoloScore 	0

    PVPTeamScore 	0

    race 	1

    radiationac 	379

    radiationdamagemodifier 	11

    rifle 	31

    riposte 	27

    rp 	0

    runspeed 	56

    savedxp 	228150

    selectedtarget 	2685

    selectedtargettype 	0

    sense 	90

    senseimprovement 	150

    sessiontime 	0

    sex 	2

    shadowbreed 	0

    shadowbreedtemplate 	0

    shotgun 	27

    side 	0

    sk 	0

    sneakattack 	31

    socialstatus 	0

    specialcondition 	1

    specialization 	0

    stamina 	81

    state 	0

    strength 	88

    submachinegun 	176

    swim 	26

    team 	0

    teamside 	0

    temporaryskillreduction 	0

    tempsaveplayfield 	0

    tempsaveteamid 	0

    tempsavex 	0

    tempsavey 	0

    throwingknife 	35

    throwngrapplingweapons 	27

    titlelevel 	2

    treatment 	153

    tutoring 	22

    twohandbluntweapons 	26

    twohandedgedweapons 	26

    unarmedtemplateinstance 	0

    unreadmailcount 	0

    unsavedxp 	62272

    veteranpoints 	0

    visualbreed 	1

    VisualFlags 	127

    visualprofession 	4

    visualsex 	2

    vp 	0

    waitstate 	1

    weaponsmithing 	27

    xp 	244443

    xpkillrange 	5

    xpmodifier 	2

.getfull succeeded.


**Playfield info:**

```
Copy/paste the output of Shift+F9 here

died before i could get PF info
```
----

**Comment by FuruKatsuragi** [comment] 2024-09-26 16:04
After another kill not being in his vicinity the behaviour can be reproduced.
If you attack him from range he enters combat animation (melee) and does not fire back with his gun.
Instead after a while I got hit with nanobots (this time low dmg) 
You were attacked with nanobots for 30 points of unknown damage.

But I lost way more HP than that. I'm at 700 max hp and dropped down to about 50% nearing the end of the fight (about a 30 sec encounter).

**Comment by FuruKatsuragi** [comment] 2024-09-26 16:10
On third kill he just did nothing, I entered melee range and was not attacked.

**Comment by FuruKatsuragi** [comment] 2024-09-26 16:21
4th kill I sat on him, got 2 ticks of rad dmg
Attacked by Eumenides!
You can't attack yourself.
You were unable to attack the target!
You can't attack yourself.
You were unable to attack the target!
Attacking Eumenides...
You were attacked with nanobots for 34 points of unknown damage.
You hit Eumenides for 93 points of poison damage.
You were attacked with nanobots for 63 points of unknown damage.
You hit Eumenides for 179 points of Burst damage.

Then nothing. Stayed in melee range the entire time.

**Comment by FuruKatsuragi** [comment] 2024-09-26 16:22
5th kill same setup as 4th kill:

Attacked by Eumenides!
You were healed for 40 points.
Attacking Eumenides...
You were attacked with nanobots for 68 points of unknown damage.
You were healed for 41 points.
You hit Eumenides for 69 points of poison damage.
You hit Eumenides for 191 points of Burst damage.
Unable to perform action, Burst skill is locked, able in 00:00:22
Skill burst is still locked.
You hit Eumenides for 135 points of poison damage.
You hit Eumenides for 113 points of poison damage.
Psychology skill available.
You hit Eumenides for 114 points of poison damage.
You hit Eumenides for 108 points of poison damage.
You were healed for 41 points.
You hit Eumenides for 99 points of poison damage.
You hit Eumenides for 16 points of poison damage.
You successfully perform Energize.
You hit Eumenides for 96 points of poison damage.
You were attacked with nanobots for 63 points of unknown damage.
You hit Eumenides for 97 points of poison damage.
Reloading...
You were healed for 36 points.
Reloading completed
You hit Eumenides for 69 points of poison damage.
Burst skill available.
You hit Eumenides for 292 points of Burst damage.
You hit Eumenides for 45 points of poison damage.
You were attacked with nanobots for 64 points of unknown damage.
You hit Eumenides for 110 points of poison damage.
You hit Eumenides for 40 points of poison damage.
You were healed for 38 points.
You hit Eumenides for 80 points of poison damage.
You hit Eumenides for 92 points of poison damage.
You hit Eumenides for 129 points of poison damage.
You hit Eumenides for 100 points of poison damage.
You hit Eumenides for 78 points of poison damage.
You were healed for 36 points.
You hit Eumenides for 74 points of poison damage.
You hit Eumenides for 145 points of poison damage.
You were attacked with nanobots for 34 points of unknown damage.
Burst skill available.
You hit Eumenides for 115 points of poison damage.
You hit Eumenides for 257 points of Burst damage.
You hit Eumenides for 127 points of poison damage.
You were healed for 37 points.
You hit Eumenides for 122 points of poison damage.
This XP was added to the pool of unsaved experience points that you get back through gaining new experience points. Your current pool of unsaved experience is 108873.
You can loot these remains.

**Comment by RaggyLP** [comment] 2024-09-26 16:28
This is a result of a delayed equip on the mob, an unintended side-effect of recent changes to NPC caching. This is directly affecting all mobs currently and isn't specific to any one thing.

**Comment by kajoriEU** [comment] 2024-09-30 07:13
Wasn't able to reproduce this issue again since the latest patch.

Closing this issue as fixed 👍

**Closed by kajoriEU** 2024-09-30 07:13 UTC
Labels: bug, fixed-please-verify, priority-2
