### ISSUE TITLE
Hostile nanos expiring is announced to nearby players.

### ISSUE THREAD

**Issue by 3F1-1009** [project-rubika/issues#510] opened 2024-01-17 21:08 UTC
**Describe the bug**
When a hostile nano expires on NPC, then all players nearby will get notified about it.

**To Reproduce**
1. Go to 444.9 314.9 y 25.0 566
2. Let someone else cast a short duration hostile nano on Newland City guard.
3. Wait for nano to expire
4. When nano expires you get the text in chat.

**Expected behavior**
Onli caster of nano should be notified.

**Screenshots**
![Screenshot_161](https://github.com/project-rubika/issues/assets/103999128/555523f3-2800-42bd-a99f-e601cc43dc08)

**Comment by portalerprk** [comment] 2024-01-22 00:50
Ah! This is not from normal expiration.. this was caused by Peaceful Intentions (a calm) being susceptible to interruption. These spell lines have a flag that we interpret (I think correctly) as BreakOnSpellDamage and BreakOnAttack.

In such scenarios, breaking/interrupting the nano is useful to broadcast. 

If you break a calm on live, does it broadcast?

**Comment by prkdrake** [comment] 2024-01-22 00:52
Nanos breaking on attack etc. is never announced, not even to the caster of the original nano. It is a useful feature to have, though, so I'm not sure if removing it is the right thing to do

**Comment by portalerprk** [comment] 2024-01-22 02:14
Closing. As I think this is more a feature than a bug :-)

**Closed** 2024-01-22 02:14 UTC
Labels: enhancement
