### ISSUE TITLE
Aggressive mobs will attack  from out of LOS.  Most obvious with ranged enemies

### ISSUE THREAD

**Issue by GlitchyGirl** [project-rubika/issues#439] opened 2024-01-12 20:38 UTC
**Describe the bug**
Aggressive mobs will attack from outside of the LOS , either from around corners, or through walls, but the player cannot attack them.

**To Reproduce**
1. Go to an area with an aggressive mob (For example subway, and Muggers) 
2. Gain aggro 
3. Observe that they can attack you through walls, or from around corners and that you cannot return fire with special attacks.  But can attack them if you've already started fighting them using auto attack/"Q" attack.

**Expected behavior**
Enemy will reposition itself so that it is in LoS to attack you.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/43483963/29d7dbb9-069a-4988-904d-b9dbcda9ab8e)

**Comment by lvp12345** [comment] 2024-02-05 06:04
Works with melee as well thru walls, as well as casting nanos thru walls from enemy got rooted constantly in subway from below

**Comment by prkdrake** [comment] 2024-08-18 23:14
Should be re-tested since Portaler's recent changes

**Comment by RaggyLP** [comment] 2024-08-31 11:09
Confirmed as no longer an issue, combination of the NPC AI changes and integration of Line of Sight checks has culled this issue. Closing as fixed as of 31/08/2024.

**Closed by RaggyLP** 2024-08-31 11:09 UTC
Labels: bug, priority-2, needs-verification, npc-behavior
