### ISSUE TITLE
First-Aid Kits / Treatment Labs always heal self, rather than target

### ISSUE THREAD

**Issue by prkdrake** [project-rubika/issues#373] opened 2023-12-24 02:18 UTC
**Describe the bug**
This may apply to other labs and stims, but I noticed it on the startup treatment lab.

When you use it on a target, even if the target is valid, you use it on yourself rather than the target. This is not correct - the lab should be used on your nano target.

**Reproduction steps**

1. Get a treatment lab (`/item 116628 116628 50`)
2. Get a friend to sit down
3. Sit down yourself
4. Target your friend
5. Right click the treatment lab

Notice you use it on yourself, whereas you should use it on your friend.

**Comment by prkdrake** [comment] 2023-12-24 02:24
This also applies for the startup stims at least. It's likely this is also happening for other stims and labs

**Comment by prkdrake** [comment] 2023-12-26 02:15
This is now partially fixed. There is still an issue with the effect originating on the user rather than the target, because we haven't implemented GfxCommand handling yet, which is a separate issue

**Comment by Random823** [comment] 2024-01-09 19:36
Tested, looks like it did heal the other target but it also healed me as well. "You were healed for 1500 points."

**Comment by prkdrake** [comment] 2024-01-09 20:01
Thanks, looks like I’ll need to take another look at this.

**Comment by TheTinkeringIdiot** [comment] 2024-01-27 21:44
This appears to be fixed completely. The visual effect of the nano kit occurs on the player using it, but the healing effect is correctly applied to the targeted sitting player. Healing is not applied to the using player.

**Comment by RaggyLP** [comment] 2024-04-03 00:28
This issue appears to have returned. Using Stims/Kits with your nano target being another player doesn't result in them being healed.

**Comment by RaggyLP** [comment] 2024-08-15 23:49
Confirmed issue remains as of 16/08/2024.

**Comment by RaggyLP** [comment] 2024-09-07 21:39
Confirmed, Kits and stims now hit the target player as expected. Tested with HP/Nano Kits, HP/Nano Stims, Free Movement Stims & Burst of Speed Stims. All hit the target as expected. Closing as fixed as of 07/09/2024.

**Closed by RaggyLP** 2024-09-07 21:39 UTC
Labels: bug, fixed-please-verify, priority-2
