### ISSUE TITLE
AI / Locations - Condemned Subway - AI behavior suspended when following the player down the ramp at "Escalator East"

### ISSUE THREAD

**Issue by Zolarix** [project-rubika/issues#753] opened 2024-07-13 17:11 UTC
**Describe the bug**
- When following the player down the ramp shown in the video, the pet or hostile NPC will stop dead.
- In the case of the pet the state will remain as `PetFollowing`.
- They will not respond to any further commands.
- The pet must be terminated and a new one called to continue.
- This is also confirmed to affect the Uncontrollable Anger when following the player down the same ramp due to hostile alignment. The state of being in combat with the UA will persist.

**To Reproduce**
Steps to reproduce the behaviour:
1. `.tp 246.6 165.0 127` Then turn left and left again to go deeper into the subway.
2. When you reach the intersection with a turn to the left, go straight on (past the uncontrollable anger) and through the doors.
3. You will be faced with a ramp going down towards a Mugger. At this point, cast an MP Pet nano to summon an MP Pet.
4. Walk halfway down the ramp.
Observe -> The pet will follow you until approximately halfway down the ramp before becoming unresponsive.

**Expected behavior**
The pet or hostile NPC should follow the owner down the ramp seamlessly and respond to new commands.

**Screenshots**
[Youtube video](https://youtu.be/wq4kksfFPY0?si=WDKiMcbaHLXeQgIp)

**Character info:**

```
(17:19) iPet [19 None]
------------------------------------
    accountflags 	0
    aggdef 	0
    aggressiveness 	0
    agility 	43
    aimedshot 	82
    assaultrifle 	82
    attitude 	1
    biologicalmetamorphose 	103
    bodydevelopment 	10
    bow 	82
    bowspecialattack 	82
    brawl 	82
    breakingentry 	103
    breed 	7
    breedhostility 	0
    burst 	82
    cash 	0
    charstate 	0
    chemicalac 	44
    chemistry 	97
    clan 	97
    closecombatinitiative 	103
    coldac 	44
    computerliteracy 	97
    concealment 	103
    conformity 	20
    currentmovementmode 	3
    currentnano 	525
    debug 	1
    dimach 	82
    disarmtrap 	103
    distanceweaponinitiative 	103
    dodge 	97
    driveair 	97
    driveground 	97
    duck 	97
    electricalengineering 	97
    energy 	525
    energyac 	34
    EquippedRHWeapon 	0
    equippedweapontype 	0
    evade 	97
    expansion 	3
    extroverty 	100
    fastattack 	82
    fatness 	1
    fieldquantumphysics 	97
    fireac 	44
    firstaid 	97
    flags 	403182081
    flingshot 	82
    fullauto 	82
    grenade 	82
    headmesh 	0
    healdelta 	4
    healinterval 	27
    health 	352
    intelligence 	43
    isfightingme 	0
    level 	19
    life 	352
    losheight 	0
    lr_energyweapon 	82
    lr_multipleweapon 	82
    mapnavigation 	97
    martialarts 	82
    materialcreation 	103
    materiallocation 	103
    materialmetamorphose 	103
    maxnanoenergy 	395
    maxncu 	27
    mechanicalengineering 	97
    meleeac 	34
    meleeenergyweapon 	82
    meleemultiple 	82
    monsterdata 	96195
    monsterscale 	98
    nanoac 	88
    nanoenergypool 	103
    nanointerval 	28
    nanoprogramming 	97
    nanoprowessinitiative 	103
    npc_type 	100001
    npcfamily 	97
    onehandbluntweapons 	82
    onehandedgedweapon 	82
    parry 	103
    perception 	103
    pharmaceuticals 	97
    physicalprowessinitiative 	103
    piercing 	82
    pistol 	82
    poisonac 	44
    profession 	0
    projectileac 	34
    proximityrangeindoors 	13
    proximityrangeoutdoors 	25
    psychic 	43
    psychologicalmodification 	103
    psychology 	97
    race 	1
    radiationac 	44
    rifle 	82
    riposte 	82
    runspeed 	97
    sense 	43
    senseimprovement 	103
    sex 	1
    shotgun 	82
    side 	0
    sneakattack 	82
    stability 	100
    stamina 	43
    strength 	43
    submachinegun 	82
    swim 	103
    throwingknife 	82
    throwngrapplingweapons 	82
    titlelevel 	2
    treatment 	97
    tutoring 	97
    twohandbluntweapons 	82
    twohandedgedweapons 	82
    VisualFlags 	31
    visualprofession 	15
    waitstate 	2
    weaponsmithing 	97
    xp 	0
------------------------------------

(17:19) .getfull succeeded - Listed all stats for iPet.

```

**Playfield info:**

```
(17:12) Extended location information:
(17:12) - 246.6, 165.0, 106.7 (246.6 165.0 y 106.7 127)
(17:12) - Pf Proxy: Model=51100:127 GS=0 SG=0 R=127, resource: 127
(17:12) - zone: 21, area: "Condemned Subway", room: "Escalator East"
(17:12) Server id: 1, character id: 50000:1923, time: 2024-07-13 16:12:15 (UTC)
(17:12) Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.

```
----

**Comment by Zolarix** [comment] 2024-07-13 17:28
Modified to reflect the fact this affects hostile AI following the player, too.

**Comment by Zolarix** [comment] 2024-07-13 17:41
This differs from #630 not just in location but in behaviour. Once the invisible threshold is reached, all behaviour permanently ceases, even on the "side" where it previously worked.

This differs from #652 not only because it isn't a door threshold, but because the pet / mob does not go into the "Leashing" state.

**Comment by TheTinkeringIdiot** [comment] 2024-07-14 20:57
Confirmed.

It takes a few trips up and down the ramp but eventually both a MP attack pet and Crat bot got stuck and became unresponsive. 

![image](https://github.com/user-attachments/assets/a6fc54fb-9608-4558-8dd6-32f5dcbec85f)

![image](https://github.com/user-attachments/assets/5757f2ff-fdb5-4cb7-9d0c-87240a8fbc9d)

**Comment by prkdrake** [comment] 2024-08-18 22:38
Needs to be re-verified since Portaler's behaviour changes

**Comment by RaggyLP** [comment] 2024-08-19 19:31
Sorted! Ran an MP pet up and down for a good few mins, no issues. Closing as fixed as of 19/08/2024.

**Closed by RaggyLP** 2024-08-19 19:31 UTC
Labels: needs-verification, npc-behavior
