### ISSUE TITLE
Inner Sanctum Portal to second room

### ISSUE THREAD

**Issue by Dracarn** [project-rubika/issues#740] opened 2024-05-19 08:51 UTC
**Describe the bug**
After killing Fezael The Watcher, the portal will not spawn for the next room.

**To Reproduce**
1. Go to Inner Sanctum and kill Fezael The Watcher

**Expected behavior**
After killing The Watcher a portal to the next stage should spawn

**Screenshots**
<img width="1280" alt="Inner Sanctum" src="https://github.com/project-rubika/issues/assets/137534514/5c251bad-5875-4832-bb23-5657a15d0e3e">

**Character info:**

Tempest [200 MartialArtist]
------------------------------------
    strength 	11388
    stamina 	11391
    agility 	11323
    sense 	11318
    psychic 	11311
    intelligence 	11314
    flags 	528961
    monsterscale 	112
    currentnano 	28048997
    headmesh 	40283
    waitstate 	1
    cash 	899783520
    gmlevel 	127
    expansion 	0
    breed 	2
    visualbreed 	2
    profession 	2
    visualprofession 	2
    level 	200
    sex 	2
    visualsex 	2
    health 	28245121
    titlelevel 	6
    accountflags 	0
    equippedweapontype 	1
    EquippedRHWeapon 	1
    selectedtarget 	1758
    side 	1
    currentncu 	167
    physicalprowessinitiative 	30979
    nanoenergypool 	14129
    maxnanoenergy 	28042997
    brawl 	30982
    riposte 	31195
    dimach 	30964
    adventuring 	30888
    swim 	30844
    onehandbluntweapons 	30987
    onehandedgedweapon 	30860
    piercing 	30859
    twohandbluntweapons 	30867
    twohandedgedweapons 	30867
    meleeenergyweapon 	30858
    parry 	30937
    sneakattack 	30849
    meleemultiple 	30857
    fastattack 	30850
    throwingknife 	30833
    grenade 	30829
    throwngrapplingweapons 	30837
    bow 	30917
    pistol 	30830
    assaultrifle 	30838
    submachinegun 	30840
    shotgun 	30837
    rifle 	30830
    lr_energyweapon 	30828
    flingshot 	30879
    aimedshot 	30829
    burst 	30839
    fullauto 	30847
    bowspecialattack 	30891
    lr_multipleweapon 	30829
    closecombatinitiative 	30829
    distanceweaponinitiative 	30829
    nanoprowessinitiative 	30952
    dodge 	30944
    evade 	30944
    duck 	30944
    nanoac 	30926
    mechanicalengineering 	30878
    electricalengineering 	30882
    fieldquantumphysics 	30877
    weaponsmithing 	30886
    pharmaceuticals 	30877
    nanoprogramming 	30877
    computerliteracy 	30927
    psychology 	30829
    chemistry 	30887
    tutoring 	30888
    materialmetamorphose 	31115
    biologicalmetamorphose 	31115
    psychologicalmodification 	31115
    materialcreation 	31091
    materiallocation 	31115
    senseimprovement 	31110
    firstaid 	30878
    treatment 	30878
    concealment 	30829
    breakingentry 	30878
    disarmtrap 	30829
    perception 	30829
    driveair 	30878
    driveground 	30878
    drivewater 	30878
    mapnavigation 	30828
    exitstatel 	-1071380597
    externaldoorinstance 	0
    externalplayfieldinstance 	0
    playfieldtype 	1
    selectedtargettype 	0
    xp 	2061253150
    charstate 	0
    isfightingme 	0
    nextxp 	80000
    lastsavexp 	39900
    bodydevelopment 	14146
    runspeed 	17238
    martialarts 	31003
    ip 	8020151
    lastxp 	2061253150
    life 	28145649
    savedxp 	228823
    lastsaved 	2061253150
    secondaryitemtemplate 	207108
    alignment 	1750
    specialization 	15
    maxncu 	28633
    currentmovementmode 	3
    fatness 	1
    race 	1
    monsterdata 	0
    VisualFlags 	31
    clan 	0
    projectileac 	280000
    energyac 	280000
    meleeac 	280000
    coldac 	282835
    fireac 	282834
    chemicalac 	282837
    radiationac 	282837
    poisonac 	282843
    xpmodifier 	0
    projectiledamagemodifier 	0
    meleedamagemodifier 	0
    energydamagemodifier 	0
    chemicaldamagemodifier 	0
    radiationdamagemodifier 	0
    colddamagemodifier 	0
    firedamagemodifier 	0
    poisondamagemodifier 	0
    criticalincrease 	0
    npcostmodifier 	-24
    team 	0
    healdelta 	100143
    reflectprojectileac 	200
    reflectmeleeac 	200
    reflectenergyac 	200
    reflectchemicalac 	200
    reflectradiationac 	200
    reflectcoldac 	200
    reflectfireac 	200
    reflectpoisonac 	200
    nanodelta 	100145
    aggdef 	100
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    attackspeed 	5
    metatype 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    beltslots 	6
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
    healinterval 	1
    nanointerval 	1
    specialattackshield 	0
    dmsmodifier 	0
    reflectreturnedmeleeac 	0
    shieldmeleeac 	0
    amsmodifier 	0
    damageoverridetype 	0
    reflectreturnedcoldac 	0
    shieldcoldac 	0
------------------------------------

**Playfield info:**

Extended location information:
- 182.1, 210.2, 1.0 (182.1 210.2 y 1.0 1943)
- Pf Proxy: Model=51100:1943 GS=0 SG=0 R=1943, resource: 1943
- zone: 0, area: "Area", room: "EntryHall"
Server id: 1758, character id: 50000:1758, time: 2024-05-19 08:51:09 (UTC)
Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.

----

**Comment by RaggyLP** [comment] 2024-05-25 23:17
Duplicate of #525. Thank you for the report, however please check the search to see if an issue has been previously raised.

**Closed by RaggyLP** 2024-05-25 23:17 UTC
Labels: bug, needs-verification
