### ISSUE TITLE
Trying to enter Fixer grid with Data Receptacle warps you into normal Grid

### ISSUE THREAD

**Issue by loysaranne** [project-rubika/issues#947] opened 2024-09-16 16:52 UTC
**Describe the bug**
Trying to get into Fixer grid warps you into normal Grid instead

**To Reproduce**
1. Cast Fixer Grid
2. Use Data Receptacle on Grid Terminal
3. Get warped into normal Grid

**Expected behavior**
Should enter Fixer Grid

**Comment by kajoriEU** [comment] 2024-09-16 17:02
Duplicate of #598

**Closed by kajoriEU** 2024-09-16 17:02 UTC
Labels: bug, duplicate, needs-verification
