### ISSUE TITLE
Doors leading to nowhere in some missions (?)

### ISSUE THREAD

**Issue by GlitchyGirl** [project-rubika/issues#706] opened 2024-04-06 13:27 UTC
**Describe the bug**
When running through a find the NPC mission, I encountered a door that should lead to another room in the building.  But instead is all black like an entrance/exit door.  And approaching it, it is treated as such - giving an error after a bit that an area change was not initiated on the server, to retreat or try again.

**To Reproduce**
1. Pull a mission (I pulled a locate npc mission from borealis so I could run to the building in Newland desert) 
2. Run around the area
3. Encounter a door that is all black
4. Attempt to use the door, and see the resulting error.

**Expected behavior**
Be allowed to enter the next room, or have the door lead somewhere.

**Screenshots**

![image](https://github.com/project-rubika/issues/assets/43483963/537d62a3-f20f-49c1-a239-0eeb00dd4886)

**Character info:**

```
Copy/paste the output of /getfull here - not applicable
```

**Playfield info:**

```
 137.3, 205.0, 5.0 (137.3 205.0 y 5.0 80804)
- Pf Proxy: Model=51103:1888175157 GS=0 SG=0 R=80804, resource: 324
- zone: 7, area: "", room: "clan_shop_1"
Server id: 1, character id: 50000:1380, time: 2024-04-06 05:30:39 (UTC)
Version: 00.6.1_EP1, map id: 18.8.62.0_02.06.2023_15.27.43, build: 52606.

```
----

**Comment by JulianVallee** [comment] 2024-04-06 21:03
Same issue: https://github.com/project-rubika/issues/issues/698

**Comment by TheTinkeringIdiot** [comment] 2024-04-09 22:10
This appears to be a duplicate of #698. Closing as duplicate.

**Closed by TheTinkeringIdiot** 2024-04-09 22:10 UTC
Labels: bug, needs-verification
