### ISSUE TITLE
NoName loot item in Subway

### ISSUE THREAD

**Issue by p-hudz** [project-rubika/issues#692] opened 2024-04-04 03:06 UTC
**Describe the bug**
Mugger in subway drops "NoName" loot.

**To Reproduce**
1. Go to Subway
2. Kill Mugger
3. Loot Mugger
4. He might drop a NoName

**Expected behavior**
Self-explanatory!

**Screenshot**
![image](https://github.com/project-rubika/issues/assets/165852786/5ee6d0a9-416e-4b84-9ce9-20c06cd49969)

**Character info:**

```
Noob [25 Enforcer]
------------------------------------
    strength 	160
    stamina 	150
    agility 	155
    sense 	104
    psychic 	90
    intelligence 	90
    flags 	528961
    monsterscale 	105
    currentnano 	290
    headmesh 	40128
    waitstate 	1
    cash 	899999788
    gmlevel 	127
    expansion 	3
    fatness 	0
    breed 	4
    visualbreed 	4
    profession 	9
    visualprofession 	9
    level 	25
    sex 	1
    visualsex 	1
    health 	2126
    titlelevel 	2
    accountflags 	0
    selectedtarget 	1445
    equippedweapontype 	66
    EquippedRHWeapon 	66
    nextxp 	249650
    xp 	228152
    lastsaved 	228150
    lastxp 	228150
    currentncu 	179
    exitstatel 	-1073348481
    externaldoorinstance 	-1071643872
    externalplayfieldinstance 	800
    nanoenergypool 	116
    maxnanoenergy 	290
    brawl 	292
    riposte 	50
    dimach 	101
    adventuring 	48
    swim 	78
    onehandbluntweapons 	410
    onehandedgedweapon 	98
    piercing 	92
    twohandbluntweapons 	121
    twohandedgedweapons 	81
    meleeenergyweapon 	76
    parry 	53
    sneakattack 	68
    meleemultiple 	174
    fastattack 	260
    throwingknife 	114
    grenade 	30
    throwngrapplingweapons 	49
    bow 	43
    pistol 	33
    assaultrifle 	35
    submachinegun 	37
    shotgun 	39
    rifle 	52
    lr_energyweapon 	23
    flingshot 	41
    aimedshot 	109
    burst 	38
    fullauto 	39
    bowspecialattack 	33
    lr_multipleweapon 	32
    closecombatinitiative 	123
    distanceweaponinitiative 	42
    physicalprowessinitiative 	52
    nanoprowessinitiative 	47
    dodge 	140
    evade 	181
    duck 	150
    nanoac 	50
    mechanicalengineering 	30
    electricalengineering 	30
    fieldquantumphysics 	22
    weaponsmithing 	31
    pharmaceuticals 	25
    nanoprogramming 	22
    computerliteracy 	22
    psychology 	24
    chemistry 	30
    tutoring 	63
    materialmetamorphose 	203
    biologicalmetamorphose 	193
    psychologicalmodification 	166
    materialcreation 	200
    materiallocation 	45
    senseimprovement 	181
    firstaid 	170
    treatment 	169
    concealment 	39
    breakingentry 	30
    disarmtrap 	27
    perception 	95
    driveair 	27
    driveground 	27
    drivewater 	27
    mapnavigation 	24
    bodydevelopment 	311
    runspeed 	920
    martialarts 	133
    currentmovementmode 	3
    maxncu 	252
    selectedtargettype 	0
    playfieldtype 	1
    side 	0
    race 	1
    life 	2126
    monsterdata 	0
    VisualFlags 	31
    isfightingme 	0
    clan 	0
    shieldprojectileac 	13
    shieldmeleeac 	13
    shieldenergyac 	13
    shieldchemicalac 	13
    shieldradiationac 	13
    shieldcoldac 	13
    shieldfireac 	13
    shieldpoisonac 	13
    coldac 	724
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    shieldnanoac 	2
    projectileac 	633
    meleeac 	636
    energyac 	633
    chemicalac 	649
    radiationac 	636
    poisonac 	640
    fireac 	637
    reflectmeleeac 	0
    reflectpoisonac 	0
    reflectfireac 	0
    reflectnanoac 	0
    reflectcoldac 	0
    reflectprojectileac 	0
    reflectenergyac 	0
    reflectchemicalac 	0
    reflectradiationac 	0
    team 	0
    xpmodifier 	7
    meleedamagemodifier 	10
    energydamagemodifier 	10
    projectiledamagemodifier 	10
    beltslots 	6
    criticalincrease 	1
    rangeincreaserweapon 	5
    aggdef 	100
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    lastsavexp 	0
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    attackspeed 	5
    metatype 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    absorbnanoac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
    healinterval 	24
    nanointerval 	26
    npcostmodifier 	0
    nanodamagemultiplier 	0
    firedamagemodifier 	0
    charstate 	0
    amsmodifier 	0
    damageoverridetype 	0
    xppool 	0
    ip 	111
------------------------------------

.getfull succeeded - Listed all stats for Noob.

```

**Playfield info:**

```
Extended location information:
- 276.5, 165.0, 102.8 (276.5 165.0 y 102.8 127)
- Pf Proxy: Model=51100:127 GS=0 SG=0 R=127, resource: 127
- zone: 21, area: "Condemned Subway", room: "Escalator East"
Server id: 1445, character id: 50000:1445, time: 2024-04-04 03:02:02 (UTC)
Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.

```
----

**Comment by RaggyLP** [comment] 2024-04-05 21:45
This is a duplicate of #407. It is a old custom item that was loaded into the Muggers loot table as part of a previous custom content test. You can safely disregard it for the moment :)

**Closed by RaggyLP** 2024-04-05 21:45 UTC
Labels: bug, needs-verification
