### ISSUE TITLE
Bug - Omni-Armed Forces Assault pack - No stats when equipped and equip/unequip bug

### ISSUE THREAD

**Issue by Wargsonth** [project-rubika/issues#1016] opened 2024-09-27 18:09 UTC
### Reproduction steps

```bash
1. Equip Omni-Armed Forces Assault pack anywhere
```

### Expected results

```bash
Give the stats when equipped
ACs and +skills
```

### Actual results

```bash
1. No stats given
2. Unequip it with right click => stay equipped, the action bar trigger, but nothing happens, the backpack stay on the gear window => need to zone to see it in inventory
3. Zoning unequips it when equipped => It means it was never worn (I imagine)
4. If its equipped, it unequips on the new zone automatically
```

### Bug prevalence

Always

### Description

```bash
Nothing more to add
```

### Report link

https://pastebin.com/uXBtBDv2

**Comment by RaggyLP** [comment] 2024-09-27 19:47
Duplicate of #844.

**Closed by RaggyLP** 2024-09-27 19:47 UTC
Labels: bug, needs-verification
