### ISSUE TITLE
Explosif's Polychromatic Pillows can't be changed to other variants

### ISSUE THREAD

**Issue by l00del** [project-rubika/issues#708] opened 2024-04-07 16:31 UTC
The AI Pillows "Explosif's Polychromatic Pillows" (ID 258345 + 258344 + 258343) can't be changed in the other forms by right-click

**Comment by TheTinkeringIdiot** [comment] 2024-04-12 15:12
Confirmed.

The pillows appear to be usable according to the mouse icon when hovering over them, but right clicking does nothing. 

![image](https://github.com/project-rubika/issues/assets/96996793/cdf96e31-6e45-406a-b897-db2bd555930a)

**Comment by prkdrake** [comment] 2024-08-18 23:04
Should re-verify this since recent item changes.

**Comment by TheTinkeringIdiot** [comment] 2024-08-19 01:36
Confirmed fixed. The item now cycles correctly between versions when right clicked. Closing as complete.

**Closed by TheTinkeringIdiot** 2024-08-19 01:36 UTC
Labels: bug, priority-3, needs-verification
