### ISSUE TITLE
Fixer summoned items are not temporary

### ISSUE THREAD

**Issue by galku** [project-rubika/issues#559] opened 2024-01-26 11:30 UTC
**Describe the bug**
Any nanos from the following nanolines (fixer specific) do not create any items in the inventory, but the nano executes succesfully:

Nanolines:

- Summon ammunition
- Summon armor
- Summon melee weapon
- Summon ranged weapon

**To Reproduce for fixer**
1. Create a new character
2. Make it a fixer
3. Grant yourself a level that can cast the nanos (or level up)
4. Grant yourself the fixer nanos to summon items
5. Cast nano (for example: [Bootleg Beamers 'n Bolters (OP-XX)](https://auno.org/ao/db.php?id=155349))
6. Finish casting it and see that no items appear in inventory
7. Attempt to zone to verify that there is no items showing up that way either

**To Reproduce for fixer**
1. Create a new character
2. Make it a Meta-Physicist
3. Grant yourself a level that can cast the nanos (or level up)
4. Grant yourself the MP nanos to summon items

**Expected behavior**
When using summoning nanos the correct item(s) should show up.

**Additional note:** 
Attempted summoning both Shadowweb spinner and grid armor works (all of them)
Attempted rolling a MP to summon all their weapons and all (17) of those items showed up (jesus that was time consuming).

 _removed irrelvant information_

**Comment by prkdrake** [comment] 2024-01-26 11:35
Fixer summon nanos cannot be purchased from the shop

**Comment by galku** [comment] 2024-01-26 11:58
You're right. I corrected it to grant yourself only. As obviously we can't get these from missions at the moment.

**Comment by TheTinkeringIdiot** [comment] 2024-01-29 04:09
Confirmed. 

Using Smuggler Shipment (OP-CC) (`/item 155360 155360 120`) the nano casts, credits are deducted, and chat gives the message "Nano program executed successfully". However no summoned item appears in inventory.

**Comment by RaggyLP** [comment] 2024-08-31 16:03
The items are now created by the nano, however, are not treated as temporary and are able to be sold to the vendor for creds. Raising the priority of this due to the implications of being able to just generate creds!

**Comment by prkdrake** [comment] 2024-09-14 22:25
Should now be fixed.

**Comment by RaggyLP** [comment] 2024-09-14 23:32
![image](https://github.com/user-attachments/assets/4caae781-16eb-41c8-81a6-5d203b345d1f)


Confirmed. Temp items can no longer be sold. Closing as fixed as of 15/09/2024.

**Closed by RaggyLP** 2024-09-14 23:32 UTC
Labels: bug, fixed-please-verify, priority-1
