### ISSUE TITLE
totw Windcaller Donnel won't die

### ISSUE THREAD

**Issue by Splooder24** [project-rubika/issues#501] opened 2024-01-17 11:58 UTC
**Describe the bug**

**To Reproduce**
4. See error or Notice this behavior

**Expected behavior**

**Screenshots**

**Character info:**

```
Copy/paste the output of /getfull here
```

**Playfield info:**

```
Copy/paste the output of Shift+F9 here
```
----

**Comment by prkdrake** [comment] 2024-01-17 11:59
Seems to be another instance of #393

**Comment by Splooder24** [comment] 2024-01-17 12:18
i will delete this post sorry

**Comment by prkdrake** [comment] 2024-01-17 12:19
Closed as duplicate of #393

**Closed by prkdrake** 2024-01-17 12:19 UTC
Labels: bug, duplicate
