### ISSUE TITLE
Enemies seem to warp when you root them while they're running

### ISSUE THREAD

**Issue by superbloom86** [project-rubika/issues#714] opened 2024-04-08 00:45 UTC
**Describe the bug**
When you root a mob that is running towards you, some form of desync (idk the word) happens where the mob telports forward from the area it was originally rooted. Only tested in subway, on an agent using nano program detain suspect.

**To Reproduce**
1.  Go to subway 
2.  Initiate combat 
3.  Root mob running towards you 

**Expected behavior**
Mob should remain rooted in the inital location and not teleport forward.

**Comment by TheTinkeringIdiot** [comment] 2024-04-09 23:01
Confirmed. 

When a mob is running it appears that the client and server are not perfectly synchronized on where that mob is located. Hitting it with a root causes it to update with the server's opinion, which was different from the client and so the mob appears to teleport to the new location. This update only occurs once when landing the root, the rooted mob holds still and does not continue to teleport.

**Comment by prkdrake** [comment] 2024-08-18 23:03
Should be re-tested since Portaler's recent NPC changes.

**Comment by TheTinkeringIdiot** [comment] 2024-08-19 01:49
Confirmed fixed. NPCs behave as expected when rooted, stopping immediately. Closing as complete.

**Closed by TheTinkeringIdiot** 2024-08-19 01:49 UTC
Labels: bug, priority-2, needs-verification, npc-behavior
