### ISSUE TITLE
You must have the Shadowlands Expansion Pack!

### ISSUE THREAD

**Issue by MrBoden** [project-rubika/issues#741] opened 2024-05-25 22:56 UTC
**Describe the bug**
Everything is as though I am a froob.

**To Reproduce**
1. Open launcher
2. Log in
3. Be confined to Rubi-Ka

**Expected behavior**
To be able to play the shadowlands content and engage on a nostalgic and violent trek through Northern Elysium.

**Screenshots**

**Character info:**

```
Copy/paste the output of /getfull here
```
I don't know what to put for this because it's just the way the game is. There's no malfunction, it's simply inaccessible.

**Playfield info:**

```
Copy/paste the output of Shift+F9 here
```
----

 Extended location information:
- 1814.1, 2709.0, 28.8 (1814.1 2709.0 y 28.8 647)
- Pf Proxy: Model=51100:647 GS=0 SG=0 R=647, resource: 647
- zone: 6142, area: "Temple of Three Winds Region"
Server id: 103796, character id: 50000:1778, time: 2024-05-25 22:55:51 (UTC)
Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.

**Comment by RaggyLP** [comment] 2024-05-25 23:07
This is technically not a bug. As it stands, currently, new accounts need to have their expansion flag manually updated via the Account DB to be able to access expansion content. A sweep is done by @3F1-1009 every now and then with an announcement placed on the Discord when it has been done.

Along with this, Shadowlands content is not the current development focus and is secondary to fixes and updates to RK.

**Comment by MrBoden** [comment] 2024-05-25 23:09
Thank you for this, I didn't see it documented anywhere, but having to change the flag makes sense. Sorry if I posted in the wrong area.

**Comment by RaggyLP** [comment] 2024-05-25 23:13
It's fine. I'll leave the ticket open as it is something that does need 'fixing' so to speak, but yeah, for now, just keep an eye on the Discord for when the script gets run. Just as an aside, this will only update account flags to be able to access SLoob related content, despite full expansion content existing within the RDB. This is to keep a narrow focus on issues solely (as as close to) RK-only, without the introduction of whole new sets of variables.

**Comment by RaggyLP** [comment] 2024-06-18 18:44
Now fixed as of 12/06/2024 - @3F1-1009 has updated the account/char creation process now to allow for all new accounts to be SL-ready. 

https://discord.com/channels/631914882731606025/816749335672913920/1250539628805492756

**Closed by RaggyLP** 2024-06-18 18:44 UTC
Labels: priority-4, wishlist
