### ISSUE TITLE
Ergo in Stret West Bank takes only one item (instead of 4)

### ISSUE THREAD

**Issue by Enfodoug** [project-rubika/issues#409] opened 2024-01-09 20:32 UTC
**Describe the bug**
Ergo in Stret West Bank takes only one item (instead of 4). 
One must hand over all 4 items to get the Insipid Ring (Insipid Ring Quest from Ergo on Rubi-Ka)

**To Reproduce**
Talk to Ergo.
"Hello once again."
"I have all items you need"
Trade opens. 

**Expected behavior**
The tradewindow beside the chat should have 4 slots to place the items. 

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156118657/3c6ee0ea-803d-4276-bba5-08c5cd146585)

**Playfield info:**

```
(21:26) Extended location information:
(21:26) - 1501.4, 2713.5, 1.0 (1501.4 2713.5 y 1.0 790)
(21:26) - Pf Proxy: Model=51100:790 GS=0 SG=0 R=790, resource: 790
(21:26) - zone: 4727, area: "East Last Ditch"
(21:26) Server id: 660, character id: 50000:660, time: 2024-01-09 20:26:43 (UTC)
(21:26) Version: 00.4.2_EP1, map id: NOT FOUND, build: 52606.

```
----

**Comment by RaggyLP** [comment] 2024-08-17 19:09
Update. Ergo now takes all 4 items, however, does not actively accept them, instead returning them to your inventory with the `Alas, something is still missing...` response.
Trade (756)

**Comment by prkdrake** [comment] 2024-08-18 22:15
Sorry to be a pain - can this be checked again since the item changes?

**Comment by RaggyLP** [comment] 2024-08-24 11:42
![image](https://github.com/user-attachments/assets/f072fd0b-6ab1-4585-8ede-4791c10b5fb3)
![image](https://github.com/user-attachments/assets/c9b2e793-b888-4d7b-9d1e-bd96ce054af2)

Ergo (752) takes all 4 items (234875, 234877, 234874, 234876) on the trade (465), returns them to the lpayer inventory and outputs 'Alas, something is still missing...'

**Comment by RaggyLP** [comment] 2024-08-24 12:26
Ergo also appears to give you the option [5577] 'Is this very bugged?' immediately, which is meant to be part of a later convo tree:

[5528] -> [5531] -> **[5577]**.

When giving him a Caliginous Ring of the XYZ, he eats the item and doesn't return it, however, given an Insipid Ring of the XYZ, this doesn't occur.

**Comment by prkdrake** [comment] 2024-08-24 17:16
This should now be fixed as of the latest release.

**Comment by RaggyLP** [comment] 2024-08-24 19:22
Confirmed! Ergo now accepts all the relevant Subway items, gives the correct Insipid ring based on the characters set profession and also teleports the player to the correct location when giving him the Insipid ring. Amazing job! 

*However*

When giving him either tha Ely or Scheol rings, he will still send you to the initial Nasc TP point, since he only offers the convo choice [5580]. The additional 'Yes' convo options: [5589] (Nasc), [5788] (Scheol), [5790] (Ely), [5791] (Ely), [5792] (Ely), [5793] (Ely). These should become available based on the ring given, however, I am unsure on how the various teleport locations are determined.

**Comment by prkdrake** [comment] 2024-08-24 22:02
The teleportation destination is based on your ring and your character level. If you're level 150 for example he sends you to Elysium, if you're level 220, he sends you to Scheol. I believe this is working as intended.

**Comment by RaggyLP** [comment] 2024-08-25 13:05
Confirmed. Ergo sends you to various places based on level. Closing as fixed as of 25/08/2024.

**Closed by RaggyLP** 2024-08-25 13:05 UTC
Labels: bug, fixed-please-verify, blabot, priority-3, shadowlands
