### ISSUE TITLE
Skill may show a lower value on the client than on the server after levelling up (without zoning), preventing actions that should be possible

### ISSUE THREAD

**Issue by Zolarix** [project-rubika/issues#520] opened 2024-01-18 14:01 UTC
**Describe the bug**
Matter Metamorphosis is displaying as 4 on the client (with a red debuff indicator), preventing execution of nano programs, despite showing as 42 on the server (correct value). Reopening the IP window does not resolve the issue.

My current theory is that trickle from base stats is being subtracted from this skill on the client rather than added.

I think it may be related to the following issue, as I did have the Skills window open before I zoned, however this issue stacks every time you level up in the same zone and I know this is not the behavior of Live: https://github.com/project-rubika/issues/issues/511

**To Reproduce**
1. Open the Skills window <u>.
2. Enter the Borealis subway at level 6.
3. Attack monsters in order to level up.
4. Add IP into all abilities to keep them maxed out.
Observe -> when levelling up that the Matter Metamorphosis is decreasing each time.
5. At level 10, activate the Enhance DNA perk.
Observe -> Matter Metamorphosis increases by one on the client as expected.

**Expected behavior**
I expected Matter Metamorphosis to slowly increase in line with my other nanoskills without allocating IP to them, from Ability trickle.

**Screenshots**
![Screenshot 2024-01-18 135556](https://github.com/project-rubika/issues/assets/96363854/4222a31e-14eb-4c76-8cb7-1e58956a5519)

**Character info:**
```
(13:47) Fast [12 Fixer]
------------------------------------
    strength 	40
    stamina 	43
    agility 	52
    sense 	47
    psychic 	40
    intelligence 	43
    flags 	528961
    monsterscale 	100
    currentnano 	223
    headmesh 	223868
    cash 	32934
    gmlevel 	127
    expansion 	3
    fatness 	0
    breed 	2
    visualbreed 	2
    profession 	4
    visualprofession 	4
    level 	12
    sex 	3
    visualsex 	3
    titlelevel 	1
    health 	222
    equippedweapontype 	20
    EquippedRHWeapon 	20
    selectedtarget 	873
    currentmovementmode 	8
    waitstate 	2
    currentncu 	4
    submachinegun 	89
    burst 	67
    exitstatel 	-1073348481
    externaldoorinstance 	-1071643872
    externalplayfieldinstance 	800
    playfieldtype 	1
    bodydevelopment 	62
    runspeed 	72
    nanoenergypool 	59
    distanceweaponinitiative 	52
    senseimprovement 	39
    treatment 	71
    materialmetamorphose 	42
    biologicalmetamorphose 	39
    psychologicalmodification 	39
    materialcreation 	39
    materiallocation 	40
    lr_multipleweapon 	53
    driveair 	41
    dodge 	47
    evade 	41
    computerliteracy 	70
    breakingentry 	36
    selectedtargettype 	0
    charstate 	0
    isfightingme 	0
    xp 	54939
    nextxp 	61650
    lastsavexp 	7700
    firstaid 	26
    psychology 	30
    lastxp 	15650
    maxncu 	14
    side 	0
    race 	1
    accountflags 	1234567890
    life 	261
    monsterdata 	0
    VisualFlags 	31
    clan 	0
    projectiledamagemodifier 	2
    meleedamagemodifier 	2
    poisondamagemodifier 	2
    team 	0
    chemicalac 	4
    coldac 	4
    energyac 	16
    fireac 	4
    meleeac 	19
    poisonac 	4
    projectileac 	19
    radiationac 	4
    beltslots 	2
    healinterval 	27
    maxnanoenergy 	223
    nanointerval 	28
    aggdef 	100
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    nanoac 	5
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    martialarts 	16
    meleemultiple 	16
    onehandbluntweapons 	15
    onehandedgedweapon 	16
    piercing 	16
    twohandbluntweapons 	15
    twohandedgedweapons 	15
    meleeenergyweapon 	15
    throwingknife 	17
    grenade 	17
    throwngrapplingweapons 	16
    bow 	16
    pistol 	17
    rifle 	17
    shotgun 	16
    assaultrifle 	16
    drivewater 	16
    closecombatinitiative 	16
    physicalprowessinitiative 	16
    bowspecialattack 	17
    mechanicalengineering 	16
    electricalengineering 	16
    lr_energyweapon 	15
    disarmtrap 	16
    perception 	16
    adventuring 	16
    swim 	16
    mapnavigation 	16
    tutoring 	15
    brawl 	15
    riposte 	17
    dimach 	16
    parry 	16
    sneakattack 	17
    fastattack 	17
    nanoprowessinitiative 	17
    flingshot 	18
    aimedshot 	16
    duck 	17
    fieldquantumphysics 	15
    weaponsmithing 	15
    pharmaceuticals 	16
    nanoprogramming 	15
    chemistry 	15
    concealment 	17
    driveground 	16
    fullauto 	15
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    attackspeed 	5
    metatype 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
    npcostmodifier 	0
    amsmodifier 	0
    damageoverridetype 	0
    xpmodifier 	0
    xppool 	0
    ip 	12732
    dmsmodifier 	0
    reflectreturnedmeleeac 	0
    reflectmeleeac 	0
    shieldmeleeac 	0
    reflectreturnedprojectileac 	0
    reflectprojectileac 	0
    shieldprojectileac 	0
    specialattackshield 	0
    gang_dog_tags 	4
------------------------------------

(13:47) .getfull succeeded.
```

**Playfield info:**
```
(13:57) Extended location information:
(13:57) - 181.5, 310.7, 107.6 (181.5 310.7 y 107.6 127)
(13:57) - Pf Proxy: Model=51100:127 GS=0 SG=0 R=127, resource: 127
(13:57) - zone: 0, area: "Abandoned Mall", room: "Shopping Arcade"
(13:57) Server id: 873, character id: 50000:873, time: 2024-01-18 13:57:52 (UTC)
(13:57) Version: 00.4.5_EP1, map id: NOT FOUND, build: 52606.
```
----

**Comment by Zolarix** [comment] 2024-01-18 14:10
Just found this is also affecting Strength (18 client, 40 server)

**Comment by TheTinkeringIdiot** [comment] 2024-01-31 03:00
Cannot reproduce. I leveled a character using the listed instructions and the issue does not occur. Values in the IP menu and on the server agree. This was likely fixed in a recent update.

**Closed by TheTinkeringIdiot** 2024-01-31 03:00 UTC
Labels: bug, needs-verification
