### ISSUE TITLE
disconnects in subway

### ISSUE THREAD

**Issue by 7RO11** [project-rubika/issues#751] opened 2024-07-11 22:56 UTC
**Describe the bug**
the mob incomplete rebuild in subway causes disconnects during combat

**To Reproduce**
1. Go to incomplete rebuild
2. let it fight you until it casts a nano
3. get disconnected

**Expected behavior**
nanos shouldn't disconnect you

**Character info:**

```
Tombrady [25 Nanotechnician]
------------------------------------
    strength 	700
    stamina 	700
    agility 	700
    sense 	100000
    psychic 	700
    intelligence 	100000
    flags 	528961
    monsterscale 	100
    currentnano 	310991
    headmesh 	40681
    cash 	12308403
    gmlevel 	127
    expansion 	3
    breed 	1
    visualbreed 	1
    profession 	11
    visualprofession 	11
    level 	25
    sex 	2
    visualsex 	2
    titlelevel 	2
    health 	3160
    selectedtarget 	1090
    equippedweapontype 	1044
    EquippedRHWeapon 	1044
    selectedtargettype 	0
    exitstatel 	-1073348481
    externaldoorinstance 	-1071643872
    externalplayfieldinstance 	800
    playfieldtype 	1
    ip 	-2146483648
    nextxp 	249650
    xp 	245294
    lastsaved 	228150
    lastxp 	228150
    bodydevelopment 	1000
    nanoenergypool 	6140
    evade 	13187
    runspeed 	5175
    assaultrifle 	6140
    distanceweaponinitiative 	18552
    firstaid 	18552
    treatment 	18552
    lr_energyweapon 	16070
    burst 	1175
    flingshot 	1175
    duck 	13187
    dodge 	12588
    currentmovementmode 	3
    waitstate 	1
    charstate 	0
    isfightingme 	0
    pistol 	11105
    submachinegun 	3657
    perception 	25012
    accountflags 	0
    psychologicalmodification 	26000
    specialization 	8
    mechanicalengineering 	12597
    electricalengineering 	12597
    fieldquantumphysics 	12597
    weaponsmithing 	12601
    materialcreation 	20041
    materiallocation 	20041
    maxncu 	3124
    monsterdata 	0
    currentncu 	0
    martialarts 	175
    current_mission_instance 	191580642
    currentplayfield 	127
    savedxp 	185730
    lastsavexp 	27800
    fatness 	1
    side 	0
    race 	1
    life 	3160
    VisualFlags 	31
    clan 	0
    team 	0
    aggdef 	100
    closecombatinitiative 	17557
    physicalprowessinitiative 	17557
    nanoprowessinitiative 	15075
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    nanoac 	5145
    maxnanoenergy 	18555
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    meleemultiple 	180
    onehandbluntweapons 	180
    onehandedgedweapon 	180
    piercing 	180
    twohandbluntweapons 	180
    twohandedgedweapons 	180
    meleeenergyweapon 	12592
    throwingknife 	5145
    grenade 	15075
    throwngrapplingweapons 	180
    bow 	10110
    rifle 	10110
    shotgun 	180
    drivewater 	20040
    bowspecialattack 	10110
    senseimprovement 	20040
    materialmetamorphose 	20040
    biologicalmetamorphose 	20040
    lr_multipleweapon 	10110
    disarmtrap 	20040
    adventuring 	180
    swim 	180
    driveair 	20040
    mapnavigation 	22522
    tutoring 	22522
    brawl 	180
    riposte 	12592
    dimach 	20040
    parry 	7627
    sneakattack 	12592
    fastattack 	10110
    aimedshot 	25005
    pharmaceuticals 	20040
    nanoprogramming 	25005
    computerliteracy 	25005
    psychology 	25005
    chemistry 	12592
    concealment 	17557
    breakingentry 	7627
    driveground 	20040
    fullauto 	180
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    radiationac 	175
    attackspeed 	5
    metatype 	0
    fireac 	175
    poisonac 	175
    coldac 	175
    chemicalac 	175
    energyac 	0
    meleeac 	0
    projectileac 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    beltslots 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
    healinterval 	6
    nanointerval 	6
    xpmodifier 	0
    specialattackshield 	0
    dmsmodifier 	0
    npcostmodifier 	0
    amsmodifier 	0
    nanodamagemultiplier 	0
    energydamagemodifier 	0
    xppool 	0
```

**Comment by Starbouy138** [comment] 2024-07-12 23:42
I did see that today some updates were referred to as a possible fix (Portaler) and I have been allowing 3 Incomplete rebuilds to hammer away at my, now level 26 doctor Capscan, for about 15 minutes with no crash.

**Comment by 7RO11** [comment] 2024-07-13 01:46
disconnecting is gone, irs are not casting anymore.

**Comment by Zolarix** [comment] 2024-07-14 10:51
Reopening based on consistent disconnect caused by Architect Striker casting a direct damage nano. Will try to get the name of it.

**Comment by Starbouy138** [comment] 2024-07-15 02:28
I can confirm that on the bridge over the subway station, the Architect Striker Lvl 17 cast a nano on my lvl 25 Doctor "Capscan" and I crashed.
The second time when I reloaded into the game Architect Striker cast a nano with direct damage to me for 62 points and then the second time it cast it, I crashed.
The third time he cast on me 6 times with no crash. Two different kinds of damage were reported in the combat chat window before he cast a seventh nano and there was no chat description before the game closed with a crash.
Fourth time same result as third, this time 8 casts of Proj or Rad dmg nano, then whatever it is crashed me.

Projectile or Radiation are not the problem, it is another.

You were attacked with nanobots from Architect Striker for 72 points of projectile damage.
You were attacked with nanobots from Architect Striker for 29 points of radiation damage.

-Also only one of the two Architect Striker aggros, the other waits until attacked, but both can cast the nano that crashes the game.


Extended location information:
- 335.0, 200.8, 109.0 (335.0 200.8 y 109.0 127)
- Pf Proxy: Model=51100:127 GS=0 SG=0 R=127, resource: 127
- zone: 27, area: "Condemned Subway", room: "Subway Station"
Server id: 1650, character id: 50000:1650, time: 2024-07-15 02:12:39 (UTC)
Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.

**Comment by 7RO11** [comment] 2024-07-18 17:38
checked this out with 2 players, both got disconnected when the architect striker casted the crash nano. also tried it with 1 where the as spawn and 1 at the entrance, both were disconnected

**Comment by Unknownprk** [comment] 2024-07-18 19:20
This should no longer crash the servers, it was trying to cast an AOE that did some bad stuff server side. The AoE is still broken but will be fixed with another update later on

**Comment by Starbouy138** [comment] 2024-07-24 04:41
I just ran through as lv25 Doctor Capscan and let them attack me with no issues, I only had time for one round but I had no disconnects and they both cast several nano attacks while we were on the bridge.

**Comment by Starbouy138** [comment] 2024-07-25 01:55
So I let the 2 Architect Strikers attack me for at least 10 minutes on the bridge over the subway, the Strike Forman respawned three times. I killed only him and they hit me with many Nanos with zero disconnects. I was running a Fixer HOT from the buffs menu, but I wanted to test it with more time. They only did radiation and projectile Nano damage when casting, in addition to melee damage with fists.

Sugartruck [25 Doctor]
------------------------------------
    absorbchemicalac 	0
    absorbcoldac 	0
    absorbenergyac 	0
    absorbfireac 	0
    absorbmeleeac 	0
    absorbnanoac 	0
    absorbpoisonac 	0
    absorbprojectileac 	0
    absorbradiationac 	0
    accountflags 	0
    adventuring 	35
    age 	0
    aggdef 	0
    agility 	104
    aimedshot 	72
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    alignment 	0
    amsmodifier 	0
    apartmentsallowed 	1
    apartmentsowned 	0
    assaultrifle 	51
    attackspeed 	5
    attitude 	0
    autoattackflags 	5
    battlestationrep 	10
    battlestationside 	0
    beltslots 	6
    biologicalmetamorphose 	367
    bodydevelopment 	214
    bow 	49
    bowspecialattack 	48
    brawl 	35
    breakingentry 	82
    breed 	1
    burst 	50
    cash 	897794376
    changesidecount 	0
    charstate 	0
    chemicalac 	1424
    chemicaldamagemodifier 	12
    chemistry 	36
    clan 	0
    clanconserver 	0
    clandevoted 	0
    clangaia 	0
    clanredeemed 	0
    clansentinels 	0
    clanvanguards 	0
    closecombatinitiative 	46
    coldac 	1015
    colddamagemodifier 	2
    computerliteracy 	152
    concealment 	41
    criticalincrease 	1
    currentmass 	0
    currentmovementmode 	3
    currentnano 	946
    currentncu 	196
    currentplayfield 	127
    currentstate 	0
    damageoverridetype 	0
    deadtimer 	0
    dimach 	34
    disarmtrap 	33
    distanceweaponinitiative 	152
    dmsmodifier 	0
    dodge 	261
    driveair 	38
    driveground 	38
    drivewater 	38
    duck 	95
    electricalengineering 	33
    energyac 	1046
    energydamagemodifier 	12
    EquippedRHWeapon 	1028
    equippedweapontype 	1028
    evade 	260
    exitstatel 	-1073348481
    expansion 	3
    expansionplayfield 	0
    externaldoorinstance 	-1071643872
    externalplayfieldinstance 	800
    fastattack 	32
    fatness 	1
    features 	6
    fieldquantumphysics 	32
    fireac 	1084
    firedamagemodifier 	2
    firstaid 	194
    flags 	528961
    flingshot 	168
    fullauto 	55
    globalresearchgoal 	0
    globalresearchlevel 	0
    gmlevel 	127
    gos 	0
    grenade 	47
    headmesh 	40655
    healdelta 	14
    healinterval 	25
    healmultiplier 	0
    health 	2266
    icon 	0
    inplay 	0
    insurancepercentage 	0
    insurancetime 	0
    intelligence 	111
    invaderskilled 	0
    ip 	60326
    isfightingme 	2
    itemtype 	0
    killedbyinvaders 	0
    lastconcreteplayfieldinstance 	0
    lastmailchecktime 	1283065897
    lastperkresettime 	0
    lastsaved 	228150
    lastsavexp 	21500
    lastxp 	228150
    level 	25
    life 	2333
    lr_energyweapon 	48
    lr_multipleweapon 	53
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    mapflags 	0
    mapnavigation 	38
    mapoptions 	0
    martialarts 	33
    materialcreation 	346
    materiallocation 	286
    materialmetamorphose 	371
    maxnanoenergy 	946
    maxncu 	553
    mechanicalengineering 	31
    meleeac 	1041
    meleedamagemodifier 	12
    meleeenergyweapon 	36
    meleemultiple 	34
    members 	999
    mesh 	17530
    metatype 	0
    missionbits1 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    monsterdata 	0
    monsterscale 	112
    monthspaid 	0
    nanoac 	215
    nanodamagemultiplier 	0
    nanoenergypool 	202
    nanofocuslevel 	0
    nanointerval 	26
    nanoprogramming 	27
    nanoprowessinitiative 	171
    nextxp 	249650
    npcostmodifier 	-17
    onehandbluntweapons 	39
    onehandedgedweapon 	36
    otarmedforces 	0
    otfollowers 	0
    otmed 	1234567890
    otoperator 	0
    ottrans 	0
    otunredeemed 	0
    PaidPoints 	0
    parry 	37
    perception 	33
    personalresearchgoal 	0
    personalresearchlevel 	0
    pharmaceuticals 	32
    physicalprowessinitiative 	46
    piercing 	35
    pistol 	211
    playerid 	1234567890
    playeroptions 	0
    playfieldtype 	1
    poisonac 	1018
    poisondamagemodifier 	12
    previoushealth 	50
    prevmovementmode 	3
    profession 	10
    projectileac 	1034
    projectiledamagemodifier 	12
    psychic 	111
    psychologicalmodification 	292
    psychology 	33
    PVPDuelDeaths 	0
    PVPDuelKills 	0
    PVPDuelScore 	0
    PVPProfessionDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedTeamDeaths 	0
    PVPRankedTeamKills 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    race 	1
    radiationac 	1035
    radiationdamagemodifier 	2
    rangeincreaserweapon 	5
    reflectmeleeac 	0
    reflectprojectileac 	0
    reflectradiationac 	0
    reflectreturnedmeleeac 	0
    reflectreturnedprojectileac 	0
    reflectreturnedradiationac 	0
    regainxppercentage 	0
    rifle 	66
    riposte 	33
    rp 	0
    runspeed 	186
    savedxp 	229756
    secondaryitemtemplate 	226994
    selectedtarget 	1650
    selectedtargettype 	0
    sense 	118
    senseimprovement 	293
    sessiontime 	1234567890
    sex 	3
    shadowbreed 	0
    shadowbreedtemplate 	0
    shieldmeleeac 	0
    shieldprojectileac 	0
    shieldradiationac 	0
    shotgun 	49
    side 	0
    sk 	0
    sneakattack 	32
    socialstatus 	0
    specialattackshield 	0
    specialcondition 	1
    specialization 	0
    stamina 	142
    state 	0
    strength 	141
    submachinegun 	51
    swim 	63
    team 	0
    teamside 	0
    temporaryskillreduction 	0
    tempsaveplayfield 	0
    tempsaveteamid 	0
    tempsavex 	0
    tempsavey 	0
    throwingknife 	33
    throwngrapplingweapons 	49
    titlelevel 	2
    treatment 	227
    tutoring 	71
    twohandbluntweapons 	40
    twohandedgedweapons 	40
    unarmedtemplateinstance 	0
    unreadmailcount 	0
    unsavedxp 	0
    veteranpoints 	0
    visualbreed 	1
    VisualFlags 	31
    visualprofession 	10
    visualsex 	3
    vp 	0
    waitstate 	1
    weaponsmithing 	36
    xp 	237419
    xpkillrange 	5
    xpmodifier 	7
    xppool 	169778
------------------------------------

.getfull succeeded - Listed all stats for Sugartruck.

**Closed** 2024-07-25 11:38 UTC
Labels: bug, priority-2
