### ISSUE TITLE
Team Restore Essence does not heal (MA)

### ISSUE THREAD

**Issue by StormlashTV** [project-rubika/issues#979] opened 2024-09-23 17:15 UTC
### Reproduction steps

```bash
1. Get in a team
2. Use a team heal and see if your teammates (or yourself) get healed
```

### Expected results

```bash
I expected team heals to heal the whole team, yourself included
```

### Actual results

```bash
No heals for anyone
```

### Bug prevalence

Every time

### Description

```bash
Tested with a MA with Team Restore Essence
```

### Report link

https://pastebin.com/D3Fq93vt

**Comment by kajoriEU** [comment] 2024-09-23 17:32
Yup, other team healing nanos seem to work fine. 


https://github.com/user-attachments/assets/e0398f11-98f7-42d6-b378-38fa239058b5

**Comment by prkdrake** [comment] 2024-09-23 17:37
I have confirmed this. Seems to be a specific issue with this nano, the [page for it on the portal ](https://site.project-rk.com/server/Ithaca/item/82050)doesn't work either.

**Comment by kajoriEU** [comment] 2024-09-27 10:33
Team Restore Essence is working as expected now.

Closing this as fixed 👍 


https://github.com/user-attachments/assets/60587f19-75d7-4a55-8558-de24fa7e2976

**Closed by kajoriEU** 2024-09-27 10:33 UTC
Labels: bug, fixed-please-verify, priority-3
