### ISSUE TITLE
Muggers HP too high

### ISSUE THREAD

**Issue by playboyfixer** [project-rubika/issues#460] opened 2024-01-15 18:36 UTC
**Describe the bug**
Muggers in subway have over 150 HP, even though they're lvl 5. Lvl 7 looters have a lot less

Mugger [5 Soldier]
    life     182

.getfull succeeded.
Looter [7 Fixer]
    life     35

**To Reproduce**
1. select mugger
2. do .getfull life

**Expected behavior**
Mugger hp should be lower to reflect their level better

**Screenshots**

**Character info:**
Playboyfixer [24 Fixer]
------------------------------------
    strength 	76
    stamina 	79
    agility 	88
    sense 	83
    psychic 	76
    intelligence 	79
    flags 	528961
    monsterscale 	103
    currentnano 	148
    headmesh 	223889
    cash 	898982345
    gmlevel 	127
    expansion 	3
    breed 	2
    visualbreed 	2
    profession 	4
    visualprofession 	4
    level 	24
    sex 	2
    visualsex 	2
    titlelevel 	2
    equippedweapontype 	20
    EquippedRHWeapon 	20
    health 	489
    selectedtarget 	725
    exitstatel 	-1073348481
    externaldoorinstance 	-1070988772
    externalplayfieldinstance 	540
    playfieldtype 	1
    side 	1
    selectedtargettype 	0
    currentncu 	5
    submachinegun 	154
    burst 	130
    nextxp 	228150
    xp 	220112
    lastsaved 	208050
    lastxp 	208050
    waitstate 	1
    bodydevelopment 	110
    runspeed 	142
    nanoenergypool 	110
    nanoac 	91
    distanceweaponinitiative 	115
    senseimprovement 	98
    treatment 	130
    materialmetamorphose 	98
    biologicalmetamorphose 	102
    psychologicalmodification 	98
    nanoprowessinitiative 	100
    dodge 	126
    evade 	112
    computerliteracy 	129
    currentmovementmode 	3
    isfightingme 	1
    charstate 	0
    materiallocation 	93
    firstaid 	30
    swim 	45
    tutoring 	169
    aggdef 	1
    gang_dog_tags 	6
    maxncu 	8
    fatness 	1
    race 	1
    accountflags 	1234567890
    life 	489
    monsterdata 	0
    VisualFlags 	31
    clan 	0
    team 	0
    xpmodifier 	1
    chemicalac 	119
    coldac 	119
    energyac 	171
    fireac 	41
    meleeac 	198
    poisonac 	119
    projectileac 	198
    radiationac 	41
    healinterval 	27
    maxnanoenergy 	412
    nanointerval 	26
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    lastsavexp 	0
    martialarts 	25
    meleemultiple 	25
    onehandbluntweapons 	24
    onehandedgedweapon 	25
    piercing 	25
    twohandbluntweapons 	24
    twohandedgedweapons 	24
    meleeenergyweapon 	24
    throwingknife 	26
    grenade 	26
    throwngrapplingweapons 	25
    bow 	25
    pistol 	26
    rifle 	26
    shotgun 	25
    assaultrifle 	25
    drivewater 	25
    closecombatinitiative 	25
    physicalprowessinitiative 	25
    bowspecialattack 	26
    mechanicalengineering 	25
    electricalengineering 	25
    materialcreation 	24
    lr_energyweapon 	24
    lr_multipleweapon 	26
    disarmtrap 	25
    perception 	25
    adventuring 	25
    driveair 	25
    mapnavigation 	25
    brawl 	24
    riposte 	26
    dimach 	25
    parry 	25
    sneakattack 	26
    fastattack 	26
    flingshot 	27
    aimedshot 	25
    duck 	26
    fieldquantumphysics 	24
    weaponsmithing 	24
    pharmaceuticals 	25
    nanoprogramming 	24
    psychology 	25
    chemistry 	24
    concealment 	26
    breakingentry 	25
    driveground 	25
    fullauto 	24
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    attackspeed 	5
    metatype 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    beltslots 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
    amsmodifier 	0
    damageoverridetype 	0
    projectiledamagemodifier 	0
    xppool 	0
    ip 	896
    npcostmodifier 	0
    specialattackshield 	0
    dmsmodifier 	0
    reflectreturnedprojectileac 	0
    reflectprojectileac 	0
    shieldprojectileac 	0
    reflectreturnedmeleeac 	0
    reflectmeleeac 	0
    shieldmeleeac 	0
------------------------------------

.getfull succeeded.

**Playfield info:**
Extended location information:
- 152.7, 281.7, 107.6 (152.7 281.7 y 107.6 127)
- Pf Proxy: Model=51100:127 GS=0 SG=0 R=127, resource: 127
- zone: 7, area: "Abandoned Mall", room: "Double door Mini"
Server id: 725, character id: 50000:725, time: 2024-01-15 18:30:17 (UTC)
Version: 00.4.4_EP1, map id: NOT FOUND, build: 52606.

----

**Comment by CRMCG-1** [comment] 2024-01-19 11:50
I suspect the Looter, with 35 HP, is the one which is too low. Those Looters are well within the 1hk range for most players at the same level.

**Comment by Zolarix** [comment] 2024-01-28 00:34
Closing as a duplicate of https://github.com/project-rubika/issues/issues/460 as lots of enemies stats don't match their level in the Subway (and possibly elsewhere) at present.

**Closed by Zolarix** 2024-01-28 00:34 UTC
Labels: bug, needs-verification
