### ISSUE TITLE
Abmouth doesn't spawn properly

### ISSUE THREAD

**Issue by portalerprk** [project-rubika/issues#362] opened 2023-12-23 22:39 UTC
We've heard Abmouth is not spawning properly. We need to verify and fix if not working as expected.

**Comment by TheTinkeringIdiot** [comment] 2024-01-17 04:11
I experienced this again just now. He spawns above his pit but seems to get stuck in mid air. Pulling him back out of his pit makes him act normally but he's very buggy (appearing and disappearing) while in it.

**Comment by TheTinkeringIdiot** [comment] 2024-01-17 04:21
He's definitely acting strangely. Standing before his pit, it's as if he's not there. Moving closer either within the pit or along the rim of it causes him to appear and fall into place. Walking away again and he disappears.

**Comment by prkdrake** [comment] 2024-01-17 04:27
Glad to hear he's actually spawning at all, to be honest.

**Comment by TheTinkeringIdiot** [comment] 2024-01-17 04:41
He spawns, but seemingly only when you get close. Then when I hit him he's instantly up on the rim of the pit instead of inside it, and kinda pops in and out of existence until I can pull him back away from the pit area a little bit.

**Comment by TheTinkeringIdiot** [comment] 2024-01-27 15:33
This is confirmed. 

On approach:
![image](https://github.com/project-rubika/issues/assets/96996793/67698025-d6fb-40ad-b12a-adbd3d6fc8da)

Moving closer than this causes him to spawn above the pit and fall in to it. He is not present from further away. 
![image](https://github.com/project-rubika/issues/assets/96996793/aa42913e-e31b-46d7-936f-6f809a7d740d)

One step forward and he's there:
![image](https://github.com/project-rubika/issues/assets/96996793/3f326138-2225-43df-b9b7-0a1c657ee48f)

But only kind of because he "can't see" me this close to agro:
![image](https://github.com/project-rubika/issues/assets/96996793/82c3418f-489a-40c3-87ee-0856a1af6d17)

Then if I stand on him directly, he's gone again:
![image](https://github.com/project-rubika/issues/assets/96996793/8d93a3ea-7b82-4f0d-ae42-249671350f0e)

It appears that he spawns if you are on the ramp (including on the rim), but vanishes if you are anywhere else.

**Comment by TheTinkeringIdiot** [comment] 2024-02-20 02:21
Confirmed. Visually Abmouth spawns in the correct place, but when it becomes aggressive it leaps up and lands on one of the edges of his pit. 

https://gifyu.com/image/SFTGu

**Comment by prkdrake** [comment] 2024-09-15 01:20
Closing this because it's just a pathing issue that we definitely have tracked as another issue.

**Closed by prkdrake** 2024-09-15 01:20 UTC
Labels: bug, priority-2
