### ISSUE TITLE
AI - Pets - MP - Healpet "Heal" and "Follow" behaviours are mutually exclusive and must be manually switched between

### ISSUE THREAD

**Issue by Zolarix** [project-rubika/issues#754] opened 2024-07-13 18:45 UTC
**Describe the bug**
The healpet cannot heal and follow a target simultaneously. This causes confusion, lowers the effectiveness of the healpet overall and increases the APM required to play the MP profession effectively.

Healpets tested:
- Medinos

**To Reproduce**
Steps to reproduce the behaviour:
1. Summon a healpet
Observe -> It follows you but does not heal
2. Instruct it to heal
Observe -> It heals you but does not follow

**Expected behavior**
When summoned, healpet should heal and follow caster simultaneously by default. If instructed to heal another valid target, it should both heal and follow them.

**Screenshots**

https://github.com/user-attachments/assets/dd6e1c0e-b88f-4c87-a27f-fbb3fa8bc31f

**Comment by Zolarix** [comment] 2024-07-14 11:46
I actually suspect this is the same for ATK pet + their fighting target, just a more niché situation. But tl;dr they have a longer range than intended but can't move while in attack mode.

**Comment by prkdrake** [comment] 2024-08-18 22:37
Needs to be reverified since Portaler's changes

**Comment by RaggyLP** [comment] 2024-08-21 17:07
Closing. Confirmed as fixed as of 21/08/2024.

**Closed by RaggyLP** 2024-08-21 17:07 UTC
Labels: priority-2, npc-behavior
