### ISSUE TITLE
Pen nano/weap ineffectivity

### ISSUE THREAD

**Issue by bitnykk** [project-rubika/issues#999] opened 2024-09-25 20:27 UTC
**Describe the bug**
Zone in penumbra and try to buff yourself or hit any mob.

**To Reproduce**
1. Go to 'pen'
2. Click on 'yourself' then buff
OR
2. Click on 'any mob' then Q/attack

**Expected behavior**
Buff yourself OR hit the mob with regular.

**Result**
Buff doesn't land (load bar stays full and no effect)
OR
Mob never get any REGULAR hit (though the SPECIALS seems to work fine)

**Comment by kajoriEU** [comment] 2024-09-26 05:23
I can not reproduce this.

Executing Nanos and combat is working almost as expected with the only thing we're currently experiencing is the Q -> Q to re-engage combat.

Penu does not seem to behave any different than other SL Playfields currently.


https://github.com/user-attachments/assets/a6d61a7b-b4b5-4192-b831-ddd01c2f5e74

**Comment by kajoriEU** [comment] 2024-09-26 05:26
Please use the `.bug` command in-game and fill the template next time. This will help us better understand the issue and provide us with more information to assist you.

**Comment by kajoriEU** [comment] 2024-09-30 05:19
We're closing this issue due to a lack of further details. Please feel free to reopen it if you can provide more information.

**Closed by kajoriEU** 2024-09-30 05:19 UTC
Labels: bug, cant-reproduce, needs-refinement
