### ISSUE TITLE
Weird aggro in Scheol

### ISSUE THREAD

**Issue by bitnykk** [project-rubika/issues#1032] opened 2024-09-30 18:01 UTC
**Describe the bug**
In upper Scheol with a 220 toon, grey mobs aggro me, and when i move upper rock they manage to teleport to me for 5 sec then warp back to their spot. Also hitting them has no expected fear reaction.

**To Reproduce**
1. Go to 'north scheol' with 200+ toon
2. Get near a grey mob (eg : girder)
3. Run up a rock once aggroed
4. Hit one of the mob once

**Expected behavior**
I'd expect mobs to not aggro me first, and secondly if aggroed they shouldn't teleport until me once i'm out of reach, finally they should deaggro and run away once i hit them one time.

**Comment by RaggyLP** [comment] 2024-09-30 18:11
Duplicate of #832 & #547.

The warping is part of the current movement logic, its not perfect however.

**Closed by RaggyLP** 2024-09-30 18:11 UTC
Labels: bug, needs-verification
