### ISSUE TITLE
I can loot more than 1 Copper Wire (NODROP UNIQUE)

### ISSUE THREAD

**Issue by StormlashTV** [project-rubika/issues#830] opened 2024-09-01 11:33 UTC
### Reproduction steps

```bash
1. Loot 1 Copper Wire from the Subway
2. Loot another Copper Wire
```

### Expected results

```bash
I expected it not to let me loot it in the first place since it has the UNIQUE tag and I already had one in my backpack
```

### Actual results

```bash
I was able to loot 2 of them
```

### Bug prevalence

Every time

### Description

```bash
I was just killing random trash mobs around the Subway
```

### Report link

https://pastebin.com/AGpTNxYk

**Comment by prkdrake** [comment] 2024-09-01 11:34
I think the unique tag isn’t checked for items in backpacks or bank.

**Comment by StormlashTV** [comment] 2024-09-01 11:37
I had more UNIQUE items in my backpack and it didn't let me loot those. It only happens with the Copper Wire.

**Comment by prkdrake** [comment] 2024-09-01 19:55
Unable to reproduce this with repro steps.

**Comment by StormlashTV** [comment] 2024-09-01 20:29
![image](https://github.com/user-attachments/assets/7c356dd7-8426-42eb-b667-a8f9665bfe2f)

**Comment by prkdrake** [comment] 2024-09-01 20:55
What we need is reproduction steps, it's not enough for us that it happened to you - I've tried to reproduce it and I can't. You need to figure out what you did to make it happen, test it on another character, find out how it occurs, then update the bug ticket.

**Comment by StormlashTV** [comment] 2024-09-01 21:06
It's happening with Circuit board now too. I dunno what I did. Just playing the game normally. It doesn't seem to happen every time. I tried to loot the Copper wire after today's first server restart and I couldn't. But now I can again. Imma keep trying to loot all these NODROP UNIQUE from the Subway and see what happens.

**Comment by prkdrake** [comment] 2024-09-01 21:32
I have a suspicion that your backpack might be misbehaving in some way. Where did you get it?

**Comment by StormlashTV** [comment] 2024-09-01 21:33
It might be that... I got it from a mission reward iirc @Newbie Island. I know I didn't buy it.

**Comment by prkdrake** [comment] 2024-09-07 11:08
I've reproduced this, though I'm not really sure how. I had a small backpack that I got as a quest reward from Adri, I looted a copper wire from the subway and put it into the backpack. A long whle later - after a death, zoning, logging off, and probably after even a server restart - I was able to loot a second one.

**Comment by kajoriEU** [comment] 2024-09-08 02:03
I could reproduce this issue two times now. I don't think it has to do something with the backpack itself as I did it once with the Adri Afeli Backpack and once without ever doing that mission and grabbing a small backpack from the shopping termin. I tried alot of stuff like moving stuff around inside the backpack, playing with several backpacks and deleting some - nothing worked. My client crashed, I logged in again the first enemy I killed had a copper wire. Suddenly it let me loot it with the 'first' one being in my small backpack. I'll test further.

![{22E3B1AD-6C0C-4A8C-9547-E4805F5CCDD0}](https://github.com/user-attachments/assets/8a4cd32a-9582-4e6a-855b-432c5d4634b9)

![f3db3881-13a1-4cfa-94fe-5a2c66b676b1](https://github.com/user-attachments/assets/6abb2637-1d75-41b2-ae72-46601ff2a0dc)

**Comment by kajoriEU** [comment] 2024-09-08 02:41
I looted a copper wire. I put it into a small backpack. I found another Copper Wire and could NOT loot it. I crashed my client with fast pressing ALT + F4 twice. On Relogging and getting another Copper Wire to drop I am able to loot a second Copper Wire. 

![{2D10EC6B-7F82-46C8-8D43-8C25C2824322}](https://github.com/user-attachments/assets/0495c6e3-3fe1-4ae0-87a8-a19acf178c20)

![{863AC169-CD21-47B5-9FFC-FF70DC55E05F}](https://github.com/user-attachments/assets/b03e210c-9402-4ebf-a22b-42edf0c35142)

**Comment by portalerprk** [comment] 2024-09-08 02:55
Nice work. This helps alot

**Comment by portalerprk** [comment] 2024-09-08 14:10
Should be fixed. Please check when your able, no rush.

**Comment by kajoriEU** [comment] 2024-09-08 14:22
Confirmed. I am no longer able to successful reproduce. Closing as fixed as of 08/09/2024.

**Closed by kajoriEU** 2024-09-08 14:22 UTC
Labels: bug, fixed-please-verify
