### ISSUE TITLE
Calia's Form: Parrot does not enable flight

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#664] opened 2024-03-15 02:27 UTC
**Describe the bug**
Casting Calia's Form: Parrot does not allow an Adventurer to fly. Flurry of Feathers also does not enable flight, but that one doesn't appear to have that flag on it anyway. 

**To Reproduce**
1. Be Adventurer
2. Cast Calia's Form: Parrot
3. Remain grounded

**Expected behavior**
Calia's Form: Parrot carries the EnableFlight spell and should enable the player to fly.

**Comment by RaggyLP** [comment] 2024-03-19 22:22
Confirmed. Calia's Form: Parrot is not setting the carahcter flag for flight on cast.

```Raggyadv [220 Adventurer]
------------------------------------
    strength 	1564
    stamina 	1480
    agility 	1744
    sense 	1712
    psychic 	1548
    intelligence 	1564
    flags 	545788481
    monsterscale 	100
    currentnano 	2067
    headmesh 	223891
    waitstate 	1
    cash 	900000154
    gmlevel 	255
    expansion 	3
    breed 	2
    visualbreed 	2
    profession 	6
    visualprofession 	6
    level 	220
    sex 	2
    visualsex 	2
    health 	2666
    titlelevel 	7
    accountflags 	0
    equippedweapontype 	1028
    EquippedRHWeapon 	1028
    selectedtarget 	1293
    exitstatel 	-1073740870
    externaldoorinstance 	0
    externalplayfieldinstance 	0
    side 	1
    specialization 	15
    nextxp 	3067008
    xp 	2555840
    lastsaved 	2555840
    lastxp 	2555840
    currentncu 	67
    selectedtargettype 	0
    monsterdata 	30365
    charstate 	0
    isfightingme 	0
    nanoenergypool 	1248
    martialarts 	2412
    brawl 	2382
    riposte 	2432
    dimach 	2419
    adventuring 	3907
    swim 	3687
    onehandbluntweapons 	2387
    onehandedgedweapon 	2442
    piercing 	2407
    twohandbluntweapons 	2380
    twohandedgedweapons 	2382
    meleeenergyweapon 	2380
    parry 	2411
    meleemultiple 	2415
    fastattack 	2435
    throwingknife 	2425
    grenade 	2423
    throwngrapplingweapons 	2418
    bow 	2423
    pistol 	2497
    assaultrifle 	2403
    submachinegun 	2401
    shotgun 	2418
    rifle 	2432
    lr_energyweapon 	2404
    flingshot 	2436
    aimedshot 	2428
    burst 	2409
    fullauto 	2382
    bowspecialattack 	2428
    lr_multipleweapon 	2422
    closecombatinitiative 	2416
    distanceweaponinitiative 	2416
    physicalprowessinitiative 	2416
    nanoprowessinitiative 	2431
    dodge 	2594
    evade 	2594
    duck 	2594
    nanoac 	2387
    mechanicalengineering 	2413
    electricalengineering 	2400
    fieldquantumphysics 	2389
    weaponsmithing 	2391
    pharmaceuticals 	2400
    nanoprogramming 	2391
    computerliteracy 	2391
    psychology 	2409
    chemistry 	2380
    tutoring 	2398
    materialmetamorphose 	3330
    biologicalmetamorphose 	3330
    psychologicalmodification 	2398
    materialcreation 	2386
    materiallocation 	2400
    senseimprovement 	2391
    firstaid 	2419
    treatment 	2411
    concealment 	2430
    breakingentry 	2418
    disarmtrap 	2422
    perception 	2416
    driveair 	2422
    driveground 	2422
    drivewater 	2422
    mapnavigation 	2409
    playfieldtype 	0
    currentmovementmode 	3
    bodydevelopment 	1235
    expansionplayfield 	0
    maxncu 	2008
    sneakattack 	2425
    fatness 	1
    race 	1
    life 	5450
    VisualFlags 	31
    runspeed 	2748
    clan 	0
    team 	0
    aggdef 	100
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    maxnanoenergy 	5294
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    lastsavexp 	0
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    radiationac 	20378
    attackspeed 	5
    metatype 	0
    fireac 	20396
    poisonac 	20373
    coldac 	20380
    chemicalac 	20378
    energyac 	20000
    meleeac 	20000
    projectileac 	20000
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    beltslots 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
    healinterval 	1
    nanointerval 	1
    xpmodifier 	0
    npcostmodifier 	0
    amsmodifier 	0
    projectiledamagemodifier 	0
    meleedamagemodifier 	0
    energydamagemodifier 	0
    chemicaldamagemodifier 	0
    radiationdamagemodifier 	0
    colddamagemodifier 	0
    firedamagemodifier 	0
    poisondamagemodifier 	0
    criticalincrease 	0
------------------------------------

.getfull succeeded - Listed all stats for Raggyadv.
```

**Comment by JulianVallee** [comment] 2024-04-09 22:51
Since I captured this before finding this issue, leaving it here
![ao-bug-parrot](https://github.com/project-rubika/issues/assets/6720458/c7f4fd9e-62a1-4d7b-852a-ad8a4e6a50df)

**Comment by portalerprk** [comment] 2024-07-12 02:19
Fixed - please test when you can.

**Comment by JulianVallee** [comment] 2024-07-14 18:03
Seems to be working, flight is enabled immediately and parrot form persists when zoning.

**Comment by RaggyLP** [comment] 2024-07-25 17:44
As above, Calia's Form: Parrot now enables flight immediately. Closing as fixed as of 25/07/24.

**Closed by RaggyLP** 2024-07-25 17:44 UTC
Labels: bug, Fixed - Needs Verification, priority-2
