### ISSUE TITLE
Getting duplicate Attacked by <insertmobnamehere>! in chat

### ISSUE THREAD

**Issue by StormlashTV** [project-rubika/issues#819] opened 2024-08-31 00:08 UTC
### Reproduction steps

```bash
1. Get attacked
2. Look at the chat and see the duplicate message
```

### Expected results

```bash
I expected just a single line in chat NOT two
```

### Actual results

```bash
In chat:
Attacked by Rollerrat!
Attacked by Rollerrat!
```

### Bug prevalence

Every single time I get attacked by a mob

### Description

```bash
Just get attacked by a mob.
No, it was NOT more than one Rollerrat attacking me.
It happens every single time with every single mob.
```

### Report link

https://pastebin.com/PFXEGAdA

**Comment by RaggyLP** [comment] 2024-08-31 00:30
Duplicate of #694.

**Closed by RaggyLP** 2024-08-31 00:30 UTC
Labels: bug, needs-verification
