### ISSUE TITLE
Incorrect HP being reported by the Client Stats Window

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#552] opened 2024-01-25 09:38 UTC
**Describe the bug**
The Stats window is currently displaying an incorrect HP figure, seperate to the HP value held by the server (.getfull life/health). The amount appears to be closely correlated with Max Health/Stamina trickle elements of equipped items. Zoning appears to update the clients held value if you equip or unequip an item with Max Health/Stam, but is still incorrect vs the reported server value.

**To Reproduce**
1. Create a fresh character and set to 220.
2. Level abilities/body dev.
3. Equip items with Max Health/Stamina
4. Notice the client report incorrect maximum HP

**Expected behavior**
The correct value held by the server should be reported by the client.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156821187/2d5b21c0-5bbb-40e1-9306-f354c2bae10d)
![image](https://github.com/project-rubika/issues/assets/156821187/ba7b5cad-fcd3-4e9c-8e14-20c5e5b9e633)

**Character info:**

```
Raggy3 [220 Trader]
------------------------------------
    strength 	764
    stamina 	692
    agility 	956
    sense 	930
    psychic 	920
    intelligence 	1120
    flags 	528961
    monsterscale 	100
    currentnano 	2939
    headmesh 	223891
    cash 	0
    gmlevel 	127
    expansion 	3
    breed 	2
    visualbreed 	2
    profession 	7
    visualprofession 	7
    level 	220
    sex 	2
    visualsex 	2
    health 	6419
    titlelevel 	7
    equippedweapontype 	8196
    EquippedRHWeapon 	8196
    selectedtarget 	1141
    nextxp 	3067008
    xp 	2555840
    lastsaved 	2555840
    lastxp 	2555840
    exitstatel 	-1073740870
    externaldoorinstance 	-418378760
    externalplayfieldinstance 	3064
    bodydevelopment 	1147
    currentncu 	0
    maxnanoenergy 	2939
    shotgun 	2470
    weaponsmithing 	235
    materialcreation 	258
    psychology 	256
    nanoprogramming 	320
    materiallocation 	295
    flingshot 	259
    duck 	379
    electricalengineering 	246
    mapnavigation 	251
    tutoring 	265
    driveair 	243
    nanoprowessinitiative 	235
    chemistry 	226
    computerliteracy 	280
    driveground 	243
    drivewater 	243
    fieldquantumphysics 	255
    perception 	246
    pharmaceuticals 	271
    psychologicalmodification 	270
    senseimprovement 	262
    treatment 	1298
    mechanicalengineering 	259
    concealment 	234
    pistol 	236
    firstaid 	248
    materialmetamorphose 	270
    biologicalmetamorphose 	293
    nanoac 	0
    nanoenergypool 	252
    fullauto 	183
    evade 	268
    dodge 	268
    swim 	189
    adventuring 	243
    piercing 	209
    breakingentry 	234
    parry 	213
    disarmtrap 	243
    throwngrapplingweapons 	219
    submachinegun 	204
    grenade 	244
    assaultrifle 	206
    bowspecialattack 	231
    throwingknife 	228
    aimedshot 	232
    burst 	211
    distanceweaponinitiative 	237
    side 	1
    waitstate 	1
    currentmovementmode 	3
    maxncu 	58
    selectedtargettype 	0
    playfieldtype 	0
    fatness 	1
    race 	1
    accountflags 	1234567890
    life 	6419
    monsterdata 	0
    VisualFlags 	31
    isfightingme 	0
    runspeed 	231
    clan 	0
    team 	0
    meleeac 	2100
    projectileac 	3250
    energyac 	3850
    fireac 	2100
    coldac 	3250
    radiationac 	3850
    chemicalac 	2100
    poisonac 	3250
    npcostmodifier 	-3
    aggdef 	100
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    lastsavexp 	0
    martialarts 	231
    meleemultiple 	223
    onehandbluntweapons 	193
    onehandedgedweapon 	209
    twohandbluntweapons 	187
    twohandedgedweapons 	188
    meleeenergyweapon 	231
    bow 	231
    rifle 	241
    closecombatinitiative 	242
    physicalprowessinitiative 	242
    lr_energyweapon 	246
    lr_multipleweapon 	260
    brawl 	188
    riposte 	240
    dimach 	237
    sneakattack 	255
    fastattack 	241
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    attackspeed 	5
    metatype 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    beltslots 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
    healinterval 	6
    nanointerval 	1
------------------------------------

.getfull succeeded - Listed all stats for Raggy3.
```

**Comment by prkdrake** [comment] 2024-01-25 09:40
Duplicate of #544

**Closed by prkdrake** 2024-01-25 09:40 UTC
Labels: bug, needs-verification
