### ISSUE TITLE
Can't use Coils in SL Gardens

### ISSUE THREAD

**Issue by Hexmyth** [project-rubika/issues#1009] opened 2024-09-26 22:09 UTC
### Reproduction steps

```bash
1. Earn a Coil of Health or Nano Regeneration.
2. Go to the garden of Aban zone
3. Sit down and try to use the Coil targeting yourself
```

### Expected results

```bash
I use the coil and start healing health or nano.
```

### Actual results

```bash
System channel output:

Could not use item because you do not meet the requirements.
Your expansionplayfield is required to be at least 1!
Your flags is required to be at least 0!
```

### Bug prevalence

Always

### Description

```bash
Note - you can't use RK kits either in the garden.
```

### Report link

https://pastebin.com/bFJNKyDY

**Comment by RaggyLP** [comment] 2024-09-26 22:14
Duplicate of #841.

**Closed by RaggyLP** 2024-09-26 22:14 UTC
Labels: bug, needs-verification
