### ISSUE TITLE
weapon switching mid-fight keeps damage of first weapon

### ISSUE THREAD

**Issue by 7RO11** [project-rubika/issues#567] opened 2024-01-28 01:42 UTC
**Describe the bug**
switching or unequipping your weapon while in combat keeps the damage stats of the weapon you started combat with

**To Reproduce**
0. make sure your martial arts skill is low, base value is fine
1. equip a weapon that does a lot of damage, or at least noticeably different
2. start combat with something
3. unequip your weapon
4. your fists will do about as much damage as your weapon you started the fight with

**Expected behavior**
swapping weapons mid-fight should set your damage to reflect your new weapon

**Screenshots**

**Character info:**

```
Damarhamlin [1 Keeper]
------------------------------------
    lr_energyweapon 	1175
    burst 	1175
    flingshot 	1175
    duck 	775
    dodge 	775
    evade 	775
    twohandedgedweapons 	2175
    dimach 	1175
    parry 	1175
    riposte 	1175
    selectedtargettype 	0
    isfightingme 	1
    xp 	1287
    brawl 	8912487
    healdelta 	7818
    charstate 	10
    fastattack 	4066
    strength 	700
    stamina 	700
    agility 	700
    sense 	700
    psychic 	700
    intelligence 	700
    flags 	528961
    monsterscale 	100
    currentnano 	4335
    headmesh 	40111
    waitstate 	1
    cash 	7620
    gmlevel 	127
    expansion 	3
    fatness 	2
    breed 	4
    visualbreed 	4
    profession 	14
    visualprofession 	14
    level 	1
    sex 	1
    visualsex 	1
    health 	3124818
    titlelevel 	1
    equippedweapontype 	130
    EquippedRHWeapon 	130
    selectedtarget 	1186
    exitstatel 	-1071380597
    externaldoorinstance 	0
    externalplayfieldinstance 	0
    playfieldtype 	0
    bodydevelopment 	781453
    runspeed 	891289504
    assaultrifle 	1175
    distanceweaponinitiative 	1175
    firstaid 	1175
    treatment 	1175
    nanoenergypool 	1175
    maxncu 	8
    side 	0
    race 	1
    accountflags 	1234567890
    life 	3125843
    monsterdata 	0
    VisualFlags 	31
    currentmovementmode 	3
    clan 	0
    team 	0
    aggdef 	100
    nextxp 	1450
    lastxp 	0
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    nanoac 	5
    maxnanoenergy 	2360
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    lastsavexp 	0
    martialarts 	180
    meleemultiple 	180
    onehandbluntweapons 	180
    onehandedgedweapon 	180
    piercing 	180
    twohandbluntweapons 	180
    meleeenergyweapon 	180
    throwingknife 	180
    grenade 	180
    throwngrapplingweapons 	180
    bow 	180
    pistol 	180
    rifle 	180
    submachinegun 	180
    shotgun 	180
    drivewater 	180
    closecombatinitiative 	180
    physicalprowessinitiative 	180
    bowspecialattack 	180
    senseimprovement 	180
    mechanicalengineering 	180
    electricalengineering 	180
    materialmetamorphose 	180
    biologicalmetamorphose 	180
    psychologicalmodification 	180
    materialcreation 	180
    materiallocation 	180
    lr_multipleweapon 	180
    disarmtrap 	180
    perception 	180
    adventuring 	180
    swim 	180
    driveair 	180
    mapnavigation 	180
    tutoring 	180
    healinterval 	6
    nanointerval 	6
    sneakattack 	180
    nanoprowessinitiative 	180
    aimedshot 	180
    fieldquantumphysics 	180
    weaponsmithing 	180
    pharmaceuticals 	180
    nanoprogramming 	180
    computerliteracy 	180
    psychology 	180
    chemistry 	180
    concealment 	180
    breakingentry 	180
    driveground 	180
    fullauto 	180
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    radiationac 	0
    attackspeed 	5
    metatype 	0
    fireac 	0
    poisonac 	0
    coldac 	0
    chemicalac 	0
    energyac 	0
    meleeac 	600
    projectileac 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    beltslots 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
    currentncu 	0
    amsmodifier 	0
    damageoverridetype 	0
    meleedamagemodifier 	0
    xpmodifier 	0
    xppool 	0
    ip 	-2147483648
    energydamagemodifier 	0
    dmsmodifier 	0
    reflectreturnedmeleeac 	0
    reflectmeleeac 	0
    shieldmeleeac 	0
    nanodamagemultiplier 	0
    reflectreturnedenergyac 	0
    reflectenergyac 	0
    shieldenergyac 	0
------------------------------------
```

**Playfield info:**
tested on blind cultist punching bag and mobs around totw
```
Extended location information:
- 1804.8, 2697.5, 28.8 (1804.8 2697.5 y 28.8 647)
- Pf Proxy: Model=51100:647 GS=0 SG=0 R=647, resource: 647
- zone: 6142, area: "Temple of Three Winds Region"
Server id: 124581, character id: 50000:1186, time: 2024-01-28 01:31:04 (UTC)
Version: 00.4.7_EP1, map id: NOT FOUND, build: 52606.

```
----

 a video that shows off the bug, switching between a few more weapons

https://github.com/project-rubika/issues/assets/73971287/4699f90c-79b8-448d-b46f-e989c0139d12

**Comment by Zolarix** [comment] 2024-01-28 21:18
Confirmed - Swapping midway through the fight from MTI UMP22 QL16 to unarmed on a level 10 with no points in Martial Arts Results in average damage over 16 hits within margin of error of using the weapon the entire fight. In contrast, melee only shows a substantial decrease in average damage.

Fight 1 | MTI UMP22 | Fight 2 | Swap | Fight 3 | Melee only
-- | -- | -- | -- | -- | --
energy | 10 | energy | 12 | melee | 6
energy | 12 | energy | 10 | melee | 6
energy | 13 | energy | 9 | melee | 4
energy | 7 | energy | 9 | melee | 7
energy | 13 | energy | 12 | melee | 4
energy | 12 | energy | 6 | melee | 5
energy | 8 | energy | 8 | melee | 7
energy | 11 | melee | 11 | melee | 5
energy | 7 | melee | 9 | melee | 7
energy | 10 | melee | 8 | melee | 6
energy | 12 | melee | 10 | melee | 7
energy | 13 | melee | 9 | melee | 7
energy | 6 | melee | 10 | melee | 7
energy | 9 | melee | 9 | melee | 4
energy | 13 | melee | 10 | melee | 5
energy | 12 | melee | 10 | melee | 5
Average | 10.5 | Average | 9.5 | Average | 5.75

`.Getfull` results after unequipping the weapon mid-fight:
```
Bang [10 Soldier]
------------------------------------
    sex 	1
    visualsex 	1
    titlelevel 	1
    health 	313
    equippedweapontype 	1
    EquippedRHWeapon 	1
    selectedtarget 	1084
    exitstatel 	-1073348481
    externaldoorinstance 	-1071643872
    externalplayfieldinstance 	800
    playfieldtype 	1
    currentncu 	8
    bodydevelopment 	60
    nanoenergypool 	49
    submachinegun 	74
    assaultrifle 	84
    treatment 	53
    lastsavexp 	6500
    runspeed 	55
    firstaid 	46
    currentmovementmode 	3
    waitstate 	1
    lastxp 	38650
    dodge 	29
    evade 	29
    senseimprovement 	29
    materialmetamorphose 	37
    biologicalmetamorphose 	29
    psychologicalmodification 	29
    materialcreation 	53
    materiallocation 	45
    nanoprowessinitiative 	25
    gang_dog_tags 	7
    lastperkresettime 	1706451445
    strength 	45
    stamina 	40
    agility 	36
    sense 	33
    psychic 	33
    intelligence 	33
    flags 	528961
    monsterscale 	100
    currentnano 	126
    headmesh 	40111
    cash 	95475
    gmlevel 	127
    expansion 	3
    breed 	4
    visualbreed 	4
    profession 	1
    visualprofession 	1
    level 	10
    burst 	74
    computerliteracy 	53
    fullauto 	75
    distanceweaponinitiative 	63
    pistol 	28
    shotgun 	29
    rifle 	28
    bow 	29
    aimedshot 	28
    flingshot 	29
    bowspecialattack 	28
    lr_multipleweapon 	28
    selectedtargettype 	0
    charstate 	10
    isfightingme 	1
    xp 	40324
    nextxp 	45650
    maxncu 	8
    fatness 	1
    side 	0
    race 	1
    accountflags 	1234567890
    life 	325
    monsterdata 	0
    VisualFlags 	31
    clan 	0
    team 	0
    chemicalac 	28
    coldac 	21
    energyac 	26
    fireac 	10
    meleeac 	38
    poisonac 	26
    projectileac 	36
    radiationac 	10
    aggdef 	100
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    nanoac 	5
    maxnanoenergy 	126
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    martialarts 	14
    meleemultiple 	14
    onehandbluntweapons 	15
    onehandedgedweapon 	14
    piercing 	14
    twohandbluntweapons 	15
    twohandedgedweapons 	15
    meleeenergyweapon 	14
    throwingknife 	14
    grenade 	13
    throwngrapplingweapons 	14
    drivewater 	13
    closecombatinitiative 	13
    physicalprowessinitiative 	13
    mechanicalengineering 	13
    electricalengineering 	13
    lr_energyweapon 	13
    disarmtrap 	13
    perception 	13
    adventuring 	14
    swim 	15
    driveair 	13
    mapnavigation 	13
    tutoring 	13
    brawl 	15
    riposte 	13
    dimach 	13
    parry 	14
    sneakattack 	13
    fastattack 	13
    duck 	13
    fieldquantumphysics 	13
    weaponsmithing 	14
    pharmaceuticals 	13
    nanoprogramming 	13
    psychology 	13
    chemistry 	14
    concealment 	13
    breakingentry 	13
    driveground 	13
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    attackspeed 	5
    metatype 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    beltslots 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
    healinterval 	28
    nanointerval 	28
    dmsmodifier 	0
    reflectreturnedprojectileac 	0
    reflectprojectileac 	0
    shieldprojectileac 	0
    amsmodifier 	0
    damageoverridetype 	0
    energydamagemodifier 	0
    xpmodifier 	0
    xppool 	0
    ip 	4527
```

**Comment by RaggyLP** [comment] 2024-08-31 16:38
This no longer seems to be an issue, mostly due to #778. However, checking the weapon template of the character after un-equipping the weapon doesn't show the previous items template. Closing as fixed as of 31/08/2024.

**Closed by RaggyLP** 2024-08-31 16:38 UTC
Labels: bug, priority-3
