### ISSUE TITLE
Joining team breaks chat

### ISSUE THREAD

**Issue by playboyfixer** [project-rubika/issues#473] opened 2024-01-16 19:43 UTC
**Describe the bug**
After joining a team you stop seeing public chats such as Global, Vicinity, ... including what you type yourself

**To Reproduce**
1. create a team with others (invite them)
2. try to talk

**Expected behavior**
Chat keeps working

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/156527345/a4509404-8f3b-4380-924d-119946855af1)

**Character info:**
Playboyfixer [220 Fixer]
------------------------------------
    bow 	224
    pistol 	233
    assaultrifle 	203
    shotgun 	218
    rifle 	233
    lr_energyweapon 	204
    aimedshot 	228
    bowspecialattack 	228
    lr_multipleweapon 	218
    closecombatinitiative 	217
    physicalprowessinitiative 	217
    duck 	224
    mechanicalengineering 	213
    electricalengineering 	200
    fieldquantumphysics 	189
    weaponsmithing 	191
    pharmaceuticals 	200
    nanoprogramming 	191
    psychology 	209
    chemistry 	180
    concealment 	230
    disarmtrap 	222
    perception 	217
    driveair 	222
    driveground 	222
    drivewater 	222
    mapnavigation 	209
    strength 	765
    stamina 	681
    agility 	945
    sense 	913
    psychic 	749
    intelligence 	765
    flags 	528961
    monsterscale 	103
    currentnano 	10280
    headmesh 	223889
    cash 	100001676
    gmlevel 	127
    expansion 	3
    breed 	2
    visualbreed 	2
    profession 	4
    visualprofession 	4
    level 	220
    sex 	2
    visualsex 	2
    titlelevel 	7
    equippedweapontype 	20
    EquippedRHWeapon 	20
    health 	8545
    selectedtarget 	725
    exitstatel 	-1073348481
    externaldoorinstance 	0
    externalplayfieldinstance 	0
    playfieldtype 	0
    side 	1
    selectedtargettype 	0
    currentncu 	0
    submachinegun 	1312
    burst 	1150
    nextxp 	3067008
    xp 	2555840
    lastsaved 	2555840
    lastxp 	2555840
    waitstate 	1
    bodydevelopment 	1110
    runspeed 	1333
    nanoenergypool 	1130
    nanoac 	940
    distanceweaponinitiative 	1157
    senseimprovement 	1131
    treatment 	1312
    materialmetamorphose 	1130
    biologicalmetamorphose 	970
    psychologicalmodification 	1138
    nanoprowessinitiative 	1171
    dodge 	1324
    evade 	1164
    computerliteracy 	1291
    currentmovementmode 	3
    isfightingme 	0
    charstate 	0
    materiallocation 	980
    firstaid 	234
    swim 	212
    tutoring 	353
    aggdef 	1
    gang_dog_tags 	6
    lastsavexp 	6500
    expansionplayfield 	0
    flingshot 	241
    fullauto 	187
    debug 	0
    age 	99
    onehandbluntweapons 	187
    breakingentry 	1000
    materialcreation 	187
    martialarts 	212
    brawl 	182
    riposte 	232
    dimach 	220
    adventuring 	207
    onehandedgedweapon 	202
    piercing 	207
    twohandbluntweapons 	180
    twohandedgedweapons 	182
    meleeenergyweapon 	180
    parry 	211
    sneakattack 	221
    meleemultiple 	216
    fastattack 	233
    throwingknife 	225
    grenade 	224
    throwngrapplingweapons 	218
    maxncu 	8
    fatness 	1
    race 	1
    accountflags 	1234567890
    life 	5545
    monsterdata 	0
    VisualFlags 	31
    clan 	0
    xpmodifier 	3
    meleeac 	198
    projectileac 	198
    energyac 	171
    chemicalac 	119
    radiationac 	41
    coldac 	119
    fireac 	41
    poisonac 	119
    team 	1324395380
    healinterval 	7
    maxnanoenergy 	4280
    nanointerval 	4
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    attackspeed 	5
    metatype 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    beltslots 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
    projectiledamagemodifier 	0
    meleedamagemodifier 	0
    energydamagemodifier 	0
    chemicaldamagemodifier 	0
    radiationdamagemodifier 	0
    colddamagemodifier 	0
    firedamagemodifier 	0
    poisondamagemodifier 	0
    amsmodifier 	0
    dmsmodifier 	0
------------------------------------

.getfull succeeded.

**Playfield info:**
Extended location information:
- 458.3, 409.9, 15.0 (458.3 409.9 y 15.0 540)
- Pf Proxy: Model=51100:540 GS=0 SG=0 R=540, resource: 540
- zone: 211, area: "Old Athen East"
Server id: 1, character id: 50000:725, time: 2024-01-16 19:42:56 (UTC)
Version: 00.4.4_EP1, map id: NOT FOUND, build: 52606.

----

**Comment by prkdrake** [comment] 2024-01-16 20:15
Still unable to reproduce this issue locally, tried a whole bunch of things and it just seemed to work fine.

**Comment by wowpin** [comment] 2024-01-16 20:44
I just managed to reproduce this:

- Toons A, B and C are in the vicinity - chat works fine
- **A invites B to team**
- Chat (vicinity, teama nd global) continues to work fine for all 3 toons
- **A invites C to team**
- **Chat breaks for A and B, works fine for C**

When I say chat breaks - no chat messages appear in chat window either sent by myself or others in any channels.

Even though "broken" toons cannot see their own messages, others can. E.g. in above scenario - broken A sends "/v TEST", it doesn't appear in A's and B's chat window, but is visible in C's chat window.

**Comment by prkdrake** [comment] 2024-01-16 20:46
Thanks! I'll try to recreate it locally

**Comment by prkdrake** [comment] 2024-01-16 20:46
Can you do .getfull on a, b and c for me as well, please?

**Comment by wowpin** [comment] 2024-01-16 20:50
Sure, here you go:

[A.txt](https://github.com/project-rubika/issues/files/13955593/A.txt)
[B.txt](https://github.com/project-rubika/issues/files/13955594/B.txt)
[C.txt](https://github.com/project-rubika/issues/files/13955595/C.txt)

**Comment by prkdrake** [comment] 2024-09-15 00:42
This should be fixed with the latest update

**Comment by kajoriEU** [comment] 2024-09-15 15:39
Tested this with an team of 6 people and chat didn't break for any client/teammember.

Closing this as fixed as of 15/09/2024

![{3005191A-46F8-4A06-9577-079E8923EC5E}](https://github.com/user-attachments/assets/c36f3b35-d8c1-4555-8b61-bf0a5eba143a)

**Closed by kajoriEU** 2024-09-15 15:39 UTC
Labels: bug, fixed-please-verify
