### ISSUE TITLE
Creating a character with an existing name provides no warning message

### ISSUE THREAD

**Issue by SharpTony** [project-rubika/issues#978] opened 2024-09-23 13:01 UTC
### Reproduction steps

```bash
1.  Create a new character and name it after an already existing toon
2.  Click create character
3.  You will not receive a message that the name is taken, but you will be auto-generated a new name
```

### Expected results

```bash
You should receive a message that the name is taken
```

### Actual results

```bash
You are generated a new name with no message
```

### Bug prevalence

Every time

### Description

```bash
I was making toons
```

### Report link

new toon

**Comment by kajoriEU** [comment] 2024-09-24 10:55
Hmm. Can not reproduce this currently. Maybe something we experienced under high server load?



# Screenshots 

![{5F527ED2-8ABF-40F0-843A-875E7D383BA0}](https://github.com/user-attachments/assets/5a1f3d44-ec6f-41b4-9e00-ef39bd9f1fe2)

![{12C025F3-F528-41C9-9A08-9C0A59E052F3}](https://github.com/user-attachments/assets/4c3566e0-6ac7-40ef-9324-4504d0b5d607)

**Comment by kajoriEU** [comment] 2024-09-30 12:54
Since we couldn't reproduce the issue and it hasn't occurred again, I'm closing this ticket. Please feel free to reopen it if the problem reappears or if more information becomes available for reproduction.

**Closed by kajoriEU** 2024-09-30 12:54 UTC
Labels: bug, needs-verification, needs-refinement
