### ISSUE TITLE
Trade widow get stuck upon accepting

### ISSUE THREAD

**Issue by Xv25Stealthsuit** [project-rubika/issues#669] opened 2024-04-02 19:20 UTC
**Describe the bug**
Sometimes when I trade items, the trade window get stuck and the accept buttom does not go through 

**To Reproduce**
1. Collect items
2. Find a trader / Terminal
3. Put items in the trade window
4. Press Accept

**Expected behavior**
The trade to go through and the money to get exchanged

**Screenshots**

![image](https://github.com/project-rubika/issues/assets/165836925/0c577845-6ec9-4887-961a-f8aa156d4d17)

**Character info:**

```
Copy/paste the output of /getfull here
```

**Playfield info:**

```
Copy/paste the output of Shift+F9 here
```
----

**Comment by RaggyLP** [comment] 2024-04-02 21:29
Closed as duplicate of #513.

**Closed by RaggyLP** 2024-04-02 21:29 UTC
Labels: bug, needs-verification
