### ISSUE TITLE
Players able to re-enter sneak while in combat

### ISSUE THREAD

**Issue by oatbag03** [project-rubika/issues#1034] opened 2024-09-30 19:16 UTC
### Reproduction steps

```bash
1. Attack mob from concealment - I used Aimed Shot
2. continue to attack during Sneak recharge
3. press H to re-enter sneak
4. Aimed shot again without leaving combat
```

### Expected results

```bash
I excepted that it would not be possible to enter sneak again by pressing H while in combat
```

### Actual results

```bash
Pressing H to enter sneak while fighting a mob lets you, and you are able to use Aimed shot throughout combat without leaving.
```

### Bug prevalence

Every time

### Description

```bash
Playing on Agent I attacked a mob from sneak with aimed shot and continued to use aimed shot throughout the fight without ever leaving combat. I did this by pressing H to re-enter sneaking each time.
```

### Report link

https://pastebin.com/KdU5vvKD

**Comment by oatbag03** [comment] 2024-09-30 19:17
![image](https://github.com/user-attachments/assets/55526eae-9cf4-4d0e-8b9f-ede7de65a86f)

**Comment by oatbag03** [comment] 2024-09-30 19:18
Also I hate myself reporting this but it's for the greater good :( :(

**Comment by kajoriEU** [comment] 2024-10-02 02:23
Duplicate of #720 

> Concealment is not being checked against enemy perception. The player is able to engage sneaking while in active combat. Doing so does not stop the combat enemy from pursuing the player or attacking them - the player is not "hidden" while sneaking. However sneak-based attacks like Sneak Attack and Aimed Shot work as if the enemy is unaware of the player's presence.

**Closed by kajoriEU** 2024-10-02 02:23 UTC
Labels: duplicate
