### ISSUE TITLE
Incorrect password on login

### ISSUE THREAD

**Issue by pluto65535** [project-rubika/issues#297] opened 2021-06-22 20:52 UTC
**Describe the bug**
Error message too generic, is it a server issue or incorrect password

**To Reproduce**
1. Open client
2. Insert incorrect credentials

**Expected behavior**
A clear error message explaining that it is a password related issue not a server issue.

**Screenshots**
![Screenshot (2)](https://user-images.githubusercontent.com/85851130/122997631-1e37c200-d3a4-11eb-94be-0eb43ad629de.png)

**Comment by prkdrake** [comment] 2023-12-24 02:50
This should be fixed now!

**Comment by S4ff0** [comment] 2023-12-26 13:37
i used a wrong username and a wrong password to login


Bad Password

Project Rubi-Ka has two different types of accounts, a site account and a game account. The password on your game account does not match the password you have entered.

Manage your account at portal.project-rk.com.

**Comment by prkdrake** [comment] 2023-12-26 13:39
that’s intended behaviour, though the error message could be clearer I guess. It’s bad practise to tell potential hackers “this is a valid username but the password was wrong”

**Closed** 2024-01-06 05:25 UTC
Labels: bug, low-priority-bug
