### ISSUE TITLE
Procs currently hit current nano target, instead of combat target.

### ISSUE THREAD

**Issue by RaggyLP** [project-rubika/issues#593] opened 2024-02-01 17:41 UTC
**Describe the bug**
The Accumulator proc is currently hitting the nano target instead of the combat target, allowing for 'AoE' damage.

**To Reproduce**
1. Enter combat with something.
2. Immediately swap target with tab.
3. Be in combat until Accumulator procs.
4. Notice the proc damage hitting the 2nd target.

**Expected behavior**
Accumulator damage should be limited to the current fight target.

**Screenshots**

https://github.com/project-rubika/issues/assets/156821187/7f3ba833-2c13-45c1-bae4-f5b05a79b5ce

**Character info:**

```
Raggy [15 Trader]
------------------------------------
    strength 	842
    stamina 	826
    agility 	1133
    sense 	1100
    psychic 	919
    intelligence 	931
    flags 	528961
    monsterscale 	100
    currentnano 	10462
    headmesh 	223891
    cash 	22139
    gmlevel 	127
    expansion 	3
    breed 	2
    visualbreed 	2
    profession 	7
    visualprofession 	7
    level 	15
    sex 	2
    visualsex 	2
    titlelevel 	2
    health 	8833
    equippedweapontype 	8196
    EquippedRHWeapon 	8196
    selectedtarget 	1028
    nextxp 	90550
    xp 	90146
    lastsaved 	80150
    treatment 	1471
    lastxp 	80150
    currentncu 	0
    runspeed 	1760
    senseimprovement 	1472
    biologicalmetamorphose 	1452
    psychologicalmodification 	1540
    materialcreation 	1493
    materiallocation 	1508
    nanoprowessinitiative 	1567
    shotgun 	1784
    distanceweaponinitiative 	1127
    computerliteracy 	1682
    nanoenergypool 	1552
    martialarts 	257
    brawl 	213
    riposte 	284
    dimach 	270
    adventuring 	387
    swim 	414
    onehandbluntweapons 	221
    onehandedgedweapon 	243
    piercing 	333
    twohandbluntweapons 	213
    twohandedgedweapons 	213
    meleeenergyweapon 	224
    parry 	332
    sneakattack 	271
    meleemultiple 	258
    fastattack 	284
    throwingknife 	350
    grenade 	506
    throwngrapplingweapons 	446
    bow 	2516
    pistol 	614
    assaultrifle 	503
    submachinegun 	497
    rifle 	319
    lr_energyweapon 	347
    flingshot 	613
    aimedshot 	365
    burst 	336
    fullauto 	435
    bowspecialattack 	360
    lr_multipleweapon 	298
    closecombatinitiative 	297
    physicalprowessinitiative 	297
    dodge 	1515
    evade 	1515
    duck 	690
    nanoac 	345
    mechanicalengineering 	608
    electricalengineering 	674
    fieldquantumphysics 	651
    weaponsmithing 	561
    pharmaceuticals 	497
    nanoprogramming 	732
    psychology 	563
    chemistry 	504
    tutoring 	530
    materialmetamorphose 	529
    firstaid 	477
    concealment 	697
    breakingentry 	362
    disarmtrap 	366
    perception 	542
    driveair 	548
    driveground 	548
    drivewater 	548
    mapnavigation 	528
    maxnanoenergy 	8982
    side 	1
    selectedtargettype 	0
    charstate 	0
    exitstatel 	-1073348481
    externaldoorinstance 	-1070988772
    externalplayfieldinstance 	540
    playfieldtype 	1
    isfightingme 	0
    life 	8833
    waitstate 	1
    bodydevelopment 	1146
    expansionplayfield 	0
    secondaryitemtemplate 	207108
    specialization 	15
    alignment 	1750
    shadowbreedtemplate 	215411
    maxncu 	680
    fatness 	1
    race 	1
    accountflags 	1234567890
    monsterdata 	0
    VisualFlags 	31
    currentmovementmode 	3
    clan 	0
    healdelta 	204
    nanodelta 	129
    procinitiative1 	4
    procnano1 	210950
    procchance1 	25
    meleedamagemodifier 	146
    poisondamagemodifier 	175
    firedamagemodifier 	165
    nanodamagemodifier 	80
    colddamagemodifier 	146
    projectiledamagemodifier 	193
    energydamagemodifier 	156
    chemicaldamagemodifier 	405
    radiationdamagemodifier 	165
    team 	0
    meleeac 	5810
    projectileac 	7760
    energyac 	9510
    fireac 	6766
    coldac 	8443
    radiationac 	10193
    chemicalac 	6493
    poisonac 	7760
    amsmodifier 	66
    dmsmodifier 	423
    xpmodifier 	24
    criticalincrease 	4
    reflectreturnedchemicalac 	20
    reflectchemicalac 	2
    shieldmeleeac 	10
    shieldprojectileac 	10
    shieldenergyac 	10
    shieldfireac 	10
    shieldcoldac 	10
    shieldchemicalac 	10
    shieldradiationac 	10
    shieldpoisonac 	10
    beltslots 	6
    npcostmodifier 	-25
    skilllockmodifier 	-35
    rangeincreaserweapon 	9
    rangeincreasernf 	31
    interruptmodifier 	-25
    aggdef 	100
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    lastsavexp 	0
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    attackspeed 	5
    metatype 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
    healinterval 	2
    nanointerval 	1
    damageoverridetype 	0
    xppool 	0
    ip 	-24488753
    nanodamagemultiplier 	0
    reflectreturnedprojectileac 	0
    reflectprojectileac 	0
    specialattackshield 	0
------------------------------------

.getfull succeeded - Listed all stats for Raggy.

```

**Comment by TheTinkeringIdiot** [comment] 2024-02-02 02:17
Confirmed. 

Accumulator procs damage the current nano target as described, even when the fighting target is different. 

![image](https://github.com/project-rubika/issues/assets/96996793/cca11773-a37c-41c0-9d77-d4c2a5a99ca4)

**Comment by RaggyLP** [comment] 2024-02-20 23:23
Further testing shows that this isn't just unique to the Accumulator proc line, but is that case for *all* current weapon-based procs. For example in the picture below, the Mudulurgu Acid Spitter proc lands on the current nano target, not the combat target.

![image](https://github.com/project-rubika/issues/assets/156821187/b7248fd0-9709-46d0-9bc0-bd82b7adc554)

**Comment by TheTinkeringIdiot** [comment] 2024-02-21 03:38
Confirmed this isn't just happening with harmful procs. The Keeper nano "Evangelical Reaper" causes an on-hit proc to damage the fighting target and heal the Keeper for a portion of the damage. It instead heals the current nano target, including the fighting target if selected. 

This is the combat log of a second player targeted by a Keeper fighting another target. The heals for 420 are the Keeper's proc. 
![image](https://github.com/project-rubika/issues/assets/96996793/912930e9-f252-4114-b3fd-afaab5bbf408)

**Comment by RaggyLP** [comment] 2024-02-24 00:58
Partly fixed. Weapon Procs still hit your nano target, however, perk based and nano based procs will now hit the combat target as expected.

![image](https://github.com/project-rubika/issues/assets/156821187/994b7df6-8404-4f02-aa69-ec231af63fff)

**Comment by portalerprk** [comment] 2024-02-24 14:20
Should be good now.

**Comment by TheTinkeringIdiot** [comment] 2024-02-26 02:35
Honed Edge of Tarasque's proc is casting Bite of the Tarasque on the player regardless of targeting. Previously this effect was similarly affected as other procs. 

![image](https://github.com/project-rubika/issues/assets/96996793/6d9793f2-180e-4fcd-8ea7-00b43d54bf45)

**Comment by portalerprk** [comment] 2024-03-06 00:28
Fixed.

**Comment by RaggyLP** [comment] 2024-03-06 00:48
Sadly still the case for the Acid Spitter. However the proc itself isn't affecting the listed ACs on the player. It _is_ on the mob though. So it seems the Acid spitter's nano isn't working correctly on player targets. Either way, it's still landing on current nano target ):

![image](https://github.com/project-rubika/issues/assets/156821187/71697790-b368-4571-83d3-3c0162f344ae)

And Honed Edge of Tarasque also still drops the debuff on nano target, this however _does_ damage the player.

![image](https://github.com/project-rubika/issues/assets/156821187/46d0675d-638e-467c-b240-26420dc08869)

**Comment by portalerprk** [comment] 2024-03-07 03:47
Give it another shot.

**Comment by TheTinkeringIdiot** [comment] 2024-03-07 04:15
Bite of the Tarasque is correct affecting Fight Target regardless of targeting.

![image](https://github.com/project-rubika/issues/assets/96996793/577dd61b-a124-413b-b231-50c60eed7145)

Acid Spitter also seems to be performing correctly.

![image](https://github.com/project-rubika/issues/assets/96996793/47ce3212-6358-43f0-bcc2-8689919efce0)

Closing as fixed.

**Closed by TheTinkeringIdiot** 2024-03-07 04:15 UTC
Labels: bug, Fixed - Needs Verification, priority-2
