### ISSUE TITLE
Shop statel spawned on top of shop NPC

### ISSUE THREAD

**Issue by JulianVallee** [project-rubika/issues#702] opened 2024-04-05 01:18 UTC
**Describe the bug**
Saw a shop statel on the same position as a shop NPC. After leaving and entering the instance again the shop disappeared.

**To Reproduce**
1. Go into the "Emporium Guns & Ammo" building near the Borealis grid exit (Pos: 613.1, 683.7)
2. Hopefully see the shop

**Expected behavior**
There should only be the NPC and no shop.

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/6720458/cbf63019-e1a3-4150-824c-53b2b23764bb)

**Playfield info:**
(taken after leaving and entering again unfortunately)
```
- 211.1, 189.1, 5.0 (211.1 189.1 y 5.0 2070)
- Pf Proxy: Model=51100:2070 GS=0 SG=0 R=2070, resource: 2070
- zone: 0, area: "Area"
Server id: 1, character id: 50000:1456, time: 2024-04-05 01:13:26 (UTC)
Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.
```

**Comment by RaggyLP** [comment] 2024-04-05 01:25
Closed as duplicate of #310.

**Closed by RaggyLP** 2024-04-05 01:25 UTC
Labels: bug, needs-verification
