### ISSUE TITLE
/pet guard doesnt function

### ISSUE THREAD

**Issue by SharpTony** [project-rubika/issues#769] opened 2024-08-13 18:59 UTC
**Describe the bug**
Using /pet gard doesnt work.

**To Reproduce**
1. Go to a pet prof
2. Click on /pet guard
3. Scroll down to your chat window and pet
4. See error or Notice this behavior - pet dont do nothin

**Expected behavior**
The pet is supposed to automatically attack anything that aggros you.

**Screenshots**
![image](https://github.com/user-attachments/assets/ab1da96d-75a9-4ac9-b9e0-4a9ca3ca250d)
It doesn't help the problem, but MPs are cute.

**Character info:**

```
Sharetherdb [4 Metaphysicist]
------------------------------------
    absorbchemicalac 	0
    absorbcoldac 	0
    absorbenergyac 	0
    absorbfireac 	0
    absorbmeleeac 	0
    absorbnanoac 	0
    absorbpoisonac 	0
    absorbprojectileac 	0
    absorbradiationac 	0
    accountflags 	0
    adventuring 	7
    age 	0
    aggdef 	100
    agility 	9
    aimedshot 	8
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    alignment 	0
    apartmentsallowed 	1
    apartmentsowned 	0
    assaultrifle 	7
    attackspeed 	5
    attitude 	0
    autoattackflags 	5
    battlestationrep 	10
    battlestationside 	0
    beltslots 	0
    biologicalmetamorphose 	20
    bodydevelopment 	15
    bow 	7
    bowspecialattack 	7
    brawl 	15
    breakingentry 	8
    breed 	3
    burst 	7
    cash 	2068
    changesidecount 	0
    charstate 	0
    chemicalac 	11
    chemistry 	8
    clan 	0
    clanconserver 	0
    clandevoted 	0
    clangaia 	0
    clanredeemed 	0
    clansentinels 	0
    clanvanguards 	0
    closecombatinitiative 	8
    coldac 	5
    computerliteracy 	20
    concealment 	7
    currentmass 	0
    currentmovementmode 	3
    currentnano 	107
    currentplayfield 	4582
    currentstate 	0
    deadtimer 	0
    dimach 	8
    disarmtrap 	8
    distanceweaponinitiative 	8
    dodge 	8
    driveair 	8
    driveground 	8
    drivewater 	8
    duck 	8
    electricalengineering 	8
    energyac 	12
    EquippedRHWeapon 	66
    equippedweapontype 	66
    evade 	16
    expansion 	3
    fastattack 	13
    fatness 	1
    features 	6
    fieldquantumphysics 	9
    fireac 	4
    firstaid 	16
    flags 	8917569
    flingshot 	7
    fullauto 	7
    globalresearchgoal 	0
    globalresearchlevel 	0
    gmlevel 	255
    gos 	0
    grenade 	8
    headmesh 	40185
    healinterval 	29
    health 	60
    icon 	0
    inplay 	0
    insurancepercentage 	0
    insurancetime 	0
    intelligence 	21
    invaderskilled 	0
    isfightingme 	0
    itemtype 	0
    killedbyinvaders 	0
    lastconcreteplayfieldinstance 	0
    lastmailchecktime 	1283065897
    lastperkresettime 	0
    lastsavexp 	3100
    lastxp 	7150
    level 	4
    life 	60
    lr_energyweapon 	8
    lr_multipleweapon 	8
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    mapflags 	0
    mapnavigation 	9
    mapoptions 	0
    martialarts 	7
    materialcreation 	19
    materiallocation 	19
    materialmetamorphose 	20
    maxnanoenergy 	107
    maxncu 	8
    mechanicalengineering 	8
    meleeac 	18
    meleeenergyweapon 	8
    meleemultiple 	13
    members 	999
    mesh 	17530
    metatype 	0
    missionbits1 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	6
    missionbits6 	0
    missionbits7 	128
    missionbits8 	0
    missionbits9 	0
    monsterdata 	0
    monsterscale 	100
    monthspaid 	0
    nanoac 	9
    nanoenergypool 	18
    nanofocuslevel 	0
    nanointerval 	28
    nanoprogramming 	10
    nanoprowessinitiative 	17
    nextxp 	11150
    npcostmodifier 	0
    onehandbluntweapons 	15
    onehandedgedweapon 	7
    otarmedforces 	0
    otfollowers 	0
    otmed 	1234567890
    otoperator 	0
    ottrans 	0
    otunredeemed 	0
    PaidPoints 	0
    parry 	7
    perception 	8
    personalresearchgoal 	0
    personalresearchlevel 	0
    pharmaceuticals 	9
    physicalprowessinitiative 	8
    piercing 	7
    pistol 	7
    playerid 	1234567890
    playeroptions 	0
    playfieldtype 	0
    poisonac 	10
    previoushealth 	50
    prevmovementmode 	3
    profession 	12
    projectileac 	18
    psychic 	16
    psychologicalmodification 	17
    psychology 	9
    PVPDuelDeaths 	0
    PVPDuelKills 	0
    PVPDuelScore 	0
    PVPProfessionDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedTeamDeaths 	0
    PVPRankedTeamKills 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    race 	1
    radiationac 	5
    rifle 	7
    riposte 	7
    rp 	0
    runspeed 	15
    savedxp 	0
    selectedtarget 	2075
    selectedtargettype 	0
    sense 	12
    senseimprovement 	17
    sessiontime 	0
    sex 	2
    shadowbreed 	0
    shadowbreedtemplate 	0
    shotgun 	7
    side 	0
    sk 	0
    sneakattack 	8
    socialstatus 	0
    specialcondition 	1
    specialization 	0
    stamina 	9
    state 	0
    strength 	9
    submachinegun 	7
    swim 	7
    team 	0
    teamside 	0
    temporaryskillreduction 	0
    tempsaveplayfield 	0
    tempsaveteamid 	0
    tempsavex 	0
    tempsavey 	0
    throwingknife 	7
    throwngrapplingweapons 	7
    titlelevel 	1
    treatment 	16
    tutoring 	9
    twohandbluntweapons 	7
    twohandedgedweapons 	7
    unarmedtemplateinstance 	0
    unreadmailcount 	0
    unsavedxp 	0
    veteranpoints 	0
    visualbreed 	3
    VisualFlags 	31
    visualprofession 	12
    visualsex 	2
    vp 	0
    waitstate 	1
    weaponsmithing 	8
    xp 	7324
    xpkillrange 	5
    xpmodifier 	0
------------------------------------

.getfull succeeded - Listed all stats for Sharetherdb.

```

**Playfield info:**

```
Extended location information:
- 875.1, 745.2, 21.6 (875.1 745.2 y 21.6 4582)
- Pf Proxy: Model=51100:4582 GS=0 SG=0 R=4582, resource: 4582
- zone: 921, area: "ICC Shuttleport"
Server id: 2075, character id: 50000:2075, time: 2024-08-13 18:59:19 (UTC)
Version: 00.6.1_EP1, map id: NOT FOUND, build: 52606.

```
----

**Comment by RaggyLP** [comment] 2024-08-16 00:05
Duplicate of #724.

**Closed by RaggyLP** 2024-08-16 00:05 UTC
Labels: bug, needs-verification
