### ISSUE TITLE
Saving in SL gardens provides no visual or text update

### ISSUE THREAD

**Issue by SharpTony** [project-rubika/issues#926] opened 2024-09-13 17:22 UTC
### Reproduction steps

```bash
1.  Go to a garden and save at tree or whatever you call the omni version
2.  Notice the absence of text or character animation for saving
3.  Go and die elsewhere and you'll return to the garden, but you are given no notice that you saved there
```

### Expected results

```bash
At least for Clan gardens, you are given a message saying that your character was saved and you get an animation of your character kinda elevating a bit(unless you have Blessed by the Spirits running in your NCU)
```

### Actual results

```bash
Nothing happens, but the character is saved
```

### Bug prevalence

Every time

### Description

```bash
I was crankin that Soljaboi
```

### Report link

savedbois

**Comment by RaggyLP** [comment] 2024-09-13 17:23
Duplicate of #840

**Closed by RaggyLP** 2024-09-13 17:23 UTC
Labels: bug, needs-verification
