### ISSUE TITLE
Guards have 25 health

### ISSUE THREAD

**Issue by TheTinkeringIdiot** [project-rubika/issues#578] opened 2024-01-29 03:21 UTC
**Describe the bug**
Guard NPCs in major cities have 25 health, hardly enough to defend the citizenry from the dangers of Rubi-Ka. This holds true for Tir, ICC, Old Athen, and Trade, and likely other places as well. 

**To Reproduce**
1. Target a guard
2. `/get health`
3. It's 25. 

**Expected behavior**
Guards should have a reasonable health pool for their level. 

**Screenshots**
![image](https://github.com/project-rubika/issues/assets/96996793/bcda83a4-0db6-4a30-b5c9-6e64cb274b8b)

**Comment by 3F1-1009** [comment] 2024-01-30 04:32
Confirmed. Many guards have 25 health regardless of their level. Tested on ICC guards in ICC and various clan guards in Old Athen.

**Comment by prkdrake** [comment] 2024-02-02 11:45
This should be fixed now, please test it and let us know :)

**Comment by prkdrake** [comment] 2024-02-02 11:50
Actually,  just going to close this one as a duplicate of #427!

**Closed by prkdrake** 2024-02-02 11:50 UTC
Labels: bug, Fixed - Needs Verification, priority-3
