### ISSUE TITLE
Vagabond Cloak does not display properly on the character while wearing armor

### ISSUE THREAD

**Issue by StormlashTV** [project-rubika/issues#827] opened 2024-09-01 09:14 UTC
### Reproduction steps

```bash
1. Get a Vagabond Cloak (and some armor pieces)
2. Equip them
3. The Vagabond Cloak looks weird on the character model if you have armor pieces equipped
```

### Expected results

```bash
I was hoping to see the cloak hide the armor pieces and not blend in with them
```

### Actual results

```bash
It blends in with the armor
```

### Bug prevalence

Every time

### Description

```bash
I was using the Joint Clan Newcomer's Body Armor set when this happened
Zoning doesn't fix it either
```

### Report link

https://pastebin.com/pP2rLBkM

**Comment by StormlashTV** [comment] 2024-09-01 09:18
![image](https://github.com/user-attachments/assets/844bac2f-e9d5-44ff-9620-c013039f6c35)
![image](https://github.com/user-attachments/assets/81c7ce0a-bba0-44d6-aca5-3941cc9f123b)
![image](https://github.com/user-attachments/assets/03a4762c-6ba3-401a-a288-2164b2d2b568)

**Comment by RaggyLP** [comment] 2024-09-01 11:35
Duplicate of #668.

**Closed by RaggyLP** 2024-09-01 11:35 UTC
Labels: bug, needs-verification
