### ISSUE TITLE
Sold Items reappear in inventory after relog

### ISSUE THREAD

**Issue by barteli** [project-rubika/issues#466] opened 2024-01-16 07:10 UTC
**Describe the bug**
After selling items to a store you can quit to windows and then immediately login again and they will be back in your inventory but the creds you go will still be there

**To Reproduce**
1. Sell items to a store. I sold them by ctrl+right clicking them.
2. Hit F10, Click "Quit to Windows" twice.
3. Login back in with the same character
4. The items should now be back in your inventory and the CREDS as well.

**Expected behavior**
The items should stay gone.

**Screenshots**
![scrn0002](https://github.com/project-rubika/issues/assets/48361532/ce62d193-2eba-475d-9680-c95341c66412)
![scrn0003](https://github.com/project-rubika/issues/assets/48361532/92812106-19eb-4749-a158-f06129955833)
![scrn0004](https://github.com/project-rubika/issues/assets/48361532/d3a0f648-9599-4bfc-9bfa-7db13439e406)

**Character info:**

```
Glatzi [3 Doctor]
------------------------------------
    strength 	15
    stamina 	15
    agility 	15
    sense 	15
    psychic 	15
    intelligence 	15
    flags 	528961
    monsterscale 	100
    currentnano 	91
    headmesh 	40696
    cash 	1608
    gmlevel 	1
    expansion 	3
    breed 	1
    visualbreed 	1
    profession 	10
    visualprofession 	10
    level 	3
    sex 	2
    visualsex 	2
    titlelevel 	1
    health 	88
    equippedweapontype 	1028
    EquippedRHWeapon 	1028
    selectedtarget 	754
    currentmovementmode 	3
    waitstate 	2
    exitstatel 	-1073740870
    externaldoorinstance 	-418378760
    externalplayfieldinstance 	3064
    selectedtargettype 	0
    isfightingme 	0
    charstate 	0
    xp 	6813
    nextxp 	7150
    lastsavexp 	2600
    lastxp 	4050
    bodydevelopment 	20
    runspeed 	21
    nanoenergypool 	23
    pistol 	20
    senseimprovement 	20
    treatment 	23
    materialmetamorphose 	23
    biologicalmetamorphose 	23
    psychologicalmodification 	20
    materialcreation 	20
    materiallocation 	20
    nanoprowessinitiative 	23
    dodge 	20
    evade 	20
    computerliteracy 	23
    maxncu 	8
    playfieldtype 	0
    fatness 	1
    side 	0
    race 	1
    accountflags 	1234567890
    life 	88
    monsterdata 	0
    VisualFlags 	31
    clan 	0
    team 	0
    healinterval 	29
    maxnanoenergy 	91
    nanointerval 	28
    aggdef 	100
    state 	0
    unarmedtemplateinstance 	0
    invaderskilled 	0
    killedbyinvaders 	0
    vp 	0
    unsavedxp 	0
    nanofocuslevel 	0
    specialization 	0
    shadowbreedtemplate 	0
    shadowbreed 	0
    lastperkresettime 	0
    socialstatus 	0
    playeroptions 	0
    tempsaveteamid 	0
    tempsaveplayfield 	0
    tempsavex 	0
    tempsavey 	0
    PVPDuelKills 	0
    PVPDuelDeaths 	0
    PVPProfessionDuelKills 	0
    PVPProfessionDuelDeaths 	0
    PVPRankedSoloKills 	0
    PVPRankedSoloDeaths 	0
    PVPRankedTeamKills 	0
    PVPRankedTeamDeaths 	0
    PVPSoloScore 	0
    PVPTeamScore 	0
    PVPDuelScore 	0
    unreadmailcount 	0
    lastmailchecktime 	1283065897
    savedxp 	0
    features 	6
    apartmentsallowed 	1
    apartmentsowned 	0
    nanoac 	5
    lastconcreteplayfieldinstance 	0
    mapoptions 	0
    mapareapart1 	0
    mapareapart2 	0
    mapareapart3 	0
    mapareapart4 	0
    missionbits1 	0
    missionbits2 	0
    missionbits3 	0
    missionbits4 	0
    missionbits5 	0
    missionbits6 	0
    missionbits7 	0
    missionbits8 	0
    missionbits9 	0
    missionbits10 	0
    missionbits11 	0
    missionbits12 	0
    sessiontime 	1234567890
    autoattackflags 	5
    personalresearchlevel 	0
    globalresearchlevel 	0
    personalresearchgoal 	0
    globalresearchgoal 	0
    battlestationside 	0
    battlestationrep 	10
    members 	999
    veteranpoints 	0
    monthspaid 	0
    PaidPoints 	0
    xpkillrange 	5
    inplay 	0
    attitude 	0
    alignment 	0
    icon 	0
    mesh 	17530
    deadtimer 	0
    martialarts 	8
    meleemultiple 	8
    onehandbluntweapons 	8
    onehandedgedweapon 	8
    piercing 	8
    twohandbluntweapons 	8
    twohandedgedweapons 	8
    meleeenergyweapon 	8
    throwingknife 	8
    grenade 	8
    throwngrapplingweapons 	8
    bow 	8
    rifle 	8
    submachinegun 	8
    shotgun 	8
    assaultrifle 	8
    drivewater 	8
    closecombatinitiative 	8
    distanceweaponinitiative 	8
    physicalprowessinitiative 	8
    bowspecialattack 	8
    firstaid 	8
    mechanicalengineering 	8
    electricalengineering 	8
    lr_energyweapon 	8
    lr_multipleweapon 	8
    disarmtrap 	8
    perception 	8
    adventuring 	8
    swim 	8
    driveair 	8
    mapnavigation 	8
    tutoring 	8
    brawl 	8
    riposte 	8
    dimach 	8
    parry 	8
    sneakattack 	8
    fastattack 	8
    burst 	8
    flingshot 	8
    aimedshot 	8
    duck 	8
    fieldquantumphysics 	8
    weaponsmithing 	8
    pharmaceuticals 	8
    nanoprogramming 	8
    psychology 	8
    chemistry 	8
    concealment 	8
    breakingentry 	8
    driveground 	8
    fullauto 	8
    currentmass 	0
    itemtype 	0
    previoushealth 	50
    currentstate 	0
    age 	0
    radiationac 	0
    attackspeed 	5
    metatype 	0
    fireac 	0
    poisonac 	0
    coldac 	0
    chemicalac 	0
    energyac 	0
    meleeac 	0
    projectileac 	0
    rp 	0
    specialcondition 	1
    sk 	0
    clanredeemed 	0
    clanconserver 	0
    clandevoted 	0
    otunredeemed 	0
    otoperator 	0
    otfollowers 	0
    gos 	0
    clanvanguards 	0
    ottrans 	0
    clangaia 	0
    otmed 	1234567890
    clansentinels 	0
    otarmedforces 	0
    playerid 	1234567890
    alienlevel 	0
    aliennextxp 	1500
    alienxp 	0
    insurancepercentage 	0
    prevmovementmode 	3
    teamside 	0
    beltslots 	0
    absorbprojectileac 	0
    absorbmeleeac 	0
    absorbenergyac 	0
    absorbchemicalac 	0
    absorbradiationac 	0
    absorbcoldac 	0
    absorbnanoac 	0
    absorbfireac 	0
    absorbpoisonac 	0
    temporaryskillreduction 	0
    insurancetime 	0
    mapflags 	0
    changesidecount 	0
------------------------------------

.getfull succeeded.

```

**Playfield info:**

```
- 229.4, 84.8, 6.0 (229.4 84.8 y 6.0 954)
- Pf Proxy: Model=51100:954 GS=0 SG=0 R=954, resource: 954
- zone: 21, area: "Junkyard"
Server id: 1, character id: 50000:754, time: 2024-01-16 07:09:57 (UTC)
Version: 00.4.4_EP1, map id: NOT FOUND, build: 52606.
```
----

**Comment by barteli** [comment] 2024-01-16 07:23
The items even reappear when I zone, no need to relog.

**Comment by 3F1-1009** [comment] 2024-01-16 07:43
#458

**Comment by prkdrake** [comment] 2024-01-16 13:52
This should be fixed now, please check and let us know :)

**Comment by Random823** [comment] 2024-01-16 15:30
Tested, this works as intended. You can close my issue that 3F1 mentioned. Thanks

**Closed** 2024-01-16 17:33 UTC
Labels: bug, Fixed - Needs Verification
