### ISSUE TITLE
Ammunition Number disappearing after shooting for a while or after reloading

### ISSUE THREAD

**Issue by FuruKatsuragi** [project-rubika/issues#986] opened 2024-09-24 13:17 UTC
### Reproduction steps

```bash
1. Equip a ranged weapon with a full "magazine"
2. Put said weapon onto your action bar to veriy it is full (Ot Kerans should show 120 for example)
3. Shoot your weapon, at some point the number indicating the amount of ammo left disappears
4. You can trigger this manually by pressing V and reloading (disappears too)
```

### Expected results

```bash
The amount of ammo should go down after every shot taken.
```

### Actual results

```bash
After some shots the number disappears.
After a reload the number disappears.
```

### Bug prevalence

Always

### Description

```bash
Additional info: A reload should trigger a progress bar. Hitting V or spamming it does a reload indicated by the message in the chat but no bar is shown.
```

### Report link

https://pastebin.com/Q9uK4kes

**Comment by FuruKatsuragi** [comment] 2024-09-24 14:13
Seems to be solved with the latest patch.

**Comment by FuruKatsuragi** [comment] 2024-09-24 15:56
It happened again but just once.
A lot better after the last restart and I cannot reproduce it now reliably.

**Comment by kajoriEU** [comment] 2024-09-27 10:20
I can not reproduce this at the moment. I tried with the mentioned Kerans above and also with another weapon (Perennium Blaster)

Ammo count seems to be slightly out of sync but a reload fixes it.

https://github.com/user-attachments/assets/1f8690fd-8ead-41dc-97cf-a1ef99905446


https://github.com/user-attachments/assets/53b04b0c-d526-4686-ad22-af2e7faf96de

**Comment by kajoriEU** [comment] 2024-09-30 07:03
We're closing this issue due to the inability to reproduce it. If you can provide additional information, please feel free to reopen it.

**Closed by kajoriEU** 2024-09-30 07:03 UTC
Labels: bug, needs-verification, needs-refinement
